import { CanvasTemplate, TextElement, ImageElement, ShapeElement } from '@/store/useCanvasStore';

// Helper to create text elements
const createText = (
    overrides: Partial<TextElement> & { id: string; x: number; y: number; text: string }
): TextElement => ({
    type: 'text',
    width: 200,
    height: 30,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    fontSize: 24,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    lineHeight: 1.4,
    letterSpacing: 0,
    ...overrides,
});

// Helper to create shape elements
const createShape = (
    overrides: Partial<ShapeElement> & { id: string; x: number; y: number; width: number; height: number }
): ShapeElement => ({
    type: 'shape',
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    shapeType: 'rectangle',
    fill: '#ffffff',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    ...overrides,
});

// Helper to create image placeholder elements
const createImagePlaceholder = (
    overrides: Partial<ImageElement> & { id: string; x: number; y: number; width: number; height: number }
): ImageElement => ({
    type: 'image',
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    src: '', // Will be replaced when user uploads
    ...overrides,
});

export const canvasTemplates: CanvasTemplate[] = [
    // 1. Fashion Designer CV - Dark & Bold (inspired by user's reference)
    {
        id: 'fashion-dark',
        name: 'Fashion Dark',
        thumbnail: '/templates/fashion-dark.png',
        category: 'creative',
        backgroundColor: '#1a1a2e',
        backgroundGradient: {
            start: '#1a1a2e',
            end: '#16213e',
            direction: 180,
        },
        elements: [
            // Large hero image placeholder (left side)
            createImagePlaceholder({
                id: 'hero-image',
                x: 0,
                y: 0,
                width: 280,
                height: 842,
            }),
            // Coral accent bar
            createShape({
                id: 'accent-bar',
                x: 280,
                y: 300,
                width: 315,
                height: 4,
                fill: '#ff6b6b',
            }),
            // Name
            createText({
                id: 'name',
                x: 310,
                y: 120,
                width: 260,
                height: 60,
                text: 'SARAH\nMITCHELL',
                fontSize: 42,
                fontFamily: 'Playfair Display',
                fontWeight: 'bold',
                fill: '#ffffff',
                lineHeight: 1.1,
            }),
            // Job title
            createText({
                id: 'job-title',
                x: 310,
                y: 240,
                width: 260,
                height: 30,
                text: 'FASHION DESIGNER',
                fontSize: 14,
                fontFamily: 'Inter',
                fontWeight: 'normal',
                fill: '#ff6b6b',
                letterSpacing: 3,
            }),
            // About section header
            createText({
                id: 'about-header',
                x: 310,
                y: 340,
                width: 200,
                height: 25,
                text: 'ABOUT ME',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ff6b6b',
                letterSpacing: 2,
            }),
            // About text
            createText({
                id: 'about-text',
                x: 310,
                y: 370,
                width: 260,
                height: 100,
                text: 'Creative fashion designer with 8+ years of experience in haute couture and ready-to-wear collections. Passionate about sustainable fashion and innovative textile design.',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#a0a0a0',
                lineHeight: 1.6,
            }),
            // Contact icons section
            createText({
                id: 'contact-header',
                x: 310,
                y: 500,
                width: 200,
                height: 25,
                text: 'CONTACT',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ff6b6b',
                letterSpacing: 2,
            }),
            createText({
                id: 'email',
                x: 310,
                y: 530,
                width: 260,
                height: 20,
                text: 'sarah@designstudio.com',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#ffffff',
            }),
            createText({
                id: 'phone',
                x: 310,
                y: 555,
                width: 260,
                height: 20,
                text: '+1 (555) 123-4567',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#ffffff',
            }),
            createText({
                id: 'location',
                x: 310,
                y: 580,
                width: 260,
                height: 20,
                text: 'New York, NY',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#ffffff',
            }),
            // Skills
            createText({
                id: 'skills-header',
                x: 310,
                y: 640,
                width: 200,
                height: 25,
                text: 'EXPERTISE',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ff6b6b',
                letterSpacing: 2,
            }),
            createText({
                id: 'skills-list',
                x: 310,
                y: 670,
                width: 260,
                height: 120,
                text: '• Pattern Making\n• Textile Design\n• Adobe Creative Suite\n• 3D Fashion Design\n• Sustainable Materials',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#a0a0a0',
                lineHeight: 1.8,
            }),
            // Decorative elements
            createShape({
                id: 'sparkle-1',
                x: 540,
                y: 80,
                width: 30,
                height: 30,
                shapeType: 'star',
                fill: '#ff6b6b',
                innerRadius: 0.4,
                opacity: 0.6,
            }),
        ],
    },

    // 2. Minimalist Creative
    {
        id: 'minimal-creative',
        name: 'Minimal Creative',
        thumbnail: '/templates/minimal-creative.png',
        category: 'minimal',
        backgroundColor: '#fafafa',
        elements: [
            // Accent sidebar
            createShape({
                id: 'sidebar',
                x: 0,
                y: 0,
                width: 8,
                height: 842,
                fill: '#2d3436',
            }),
            // Name
            createText({
                id: 'name',
                x: 50,
                y: 80,
                width: 500,
                height: 50,
                text: 'ALEX JOHNSON',
                fontSize: 48,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#2d3436',
                letterSpacing: 2,
            }),
            // Title line
            createShape({
                id: 'title-line',
                x: 50,
                y: 145,
                width: 60,
                height: 3,
                fill: '#00cec9',
            }),
            // Job title
            createText({
                id: 'job-title',
                x: 50,
                y: 160,
                width: 300,
                height: 25,
                text: 'UX/UI DESIGNER',
                fontSize: 14,
                fontFamily: 'Inter',
                fill: '#636e72',
                letterSpacing: 4,
            }),
            // Profile image placeholder
            createImagePlaceholder({
                id: 'profile-image',
                x: 420,
                y: 60,
                width: 140,
                height: 140,
            }),
            // Summary
            createText({
                id: 'summary',
                x: 50,
                y: 220,
                width: 500,
                height: 80,
                text: 'Passionate UX/UI designer creating intuitive digital experiences. Combining aesthetic sensibility with user-centered design principles to build products that delight.',
                fontSize: 12,
                fontFamily: 'Inter',
                fill: '#636e72',
                lineHeight: 1.7,
            }),
            // Experience header
            createText({
                id: 'exp-header',
                x: 50,
                y: 340,
                width: 200,
                height: 25,
                text: 'EXPERIENCE',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#2d3436',
                letterSpacing: 2,
            }),
            createShape({
                id: 'exp-line',
                x: 50,
                y: 365,
                width: 500,
                height: 1,
                fill: '#dfe6e9',
            }),
            // Experience entries
            createText({
                id: 'exp-1-title',
                x: 50,
                y: 385,
                width: 300,
                height: 22,
                text: 'Senior UX Designer',
                fontSize: 14,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#2d3436',
            }),
            createText({
                id: 'exp-1-company',
                x: 50,
                y: 410,
                width: 300,
                height: 20,
                text: 'Tech Innovations Inc. | 2021 - Present',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#00cec9',
            }),
            createText({
                id: 'exp-1-desc',
                x: 50,
                y: 435,
                width: 500,
                height: 60,
                text: 'Leading design initiatives for flagship products, mentoring junior designers, and establishing design systems that improved development efficiency by 40%.',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#636e72',
                lineHeight: 1.6,
            }),
            // Skills section
            createText({
                id: 'skills-header',
                x: 50,
                y: 540,
                width: 200,
                height: 25,
                text: 'SKILLS',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#2d3436',
                letterSpacing: 2,
            }),
            createShape({
                id: 'skills-line',
                x: 50,
                y: 565,
                width: 500,
                height: 1,
                fill: '#dfe6e9',
            }),
            // Skill pills
            createShape({
                id: 'skill-1-bg',
                x: 50,
                y: 585,
                width: 80,
                height: 28,
                fill: '#00cec9',
                cornerRadius: 14,
                opacity: 0.15,
            }),
            createText({
                id: 'skill-1',
                x: 60,
                y: 590,
                width: 70,
                height: 20,
                text: 'Figma',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#00cec9',
                align: 'center',
            }),
            createShape({
                id: 'skill-2-bg',
                x: 145,
                y: 585,
                width: 100,
                height: 28,
                fill: '#00cec9',
                cornerRadius: 14,
                opacity: 0.15,
            }),
            createText({
                id: 'skill-2',
                x: 155,
                y: 590,
                width: 90,
                height: 20,
                text: 'Prototyping',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#00cec9',
                align: 'center',
            }),
            // Contact
            createText({
                id: 'contact',
                x: 50,
                y: 780,
                width: 500,
                height: 20,
                text: 'alex@design.com  |  +1 555 987 6543  |  portfolio.design.com',
                fontSize: 10,
                fontFamily: 'Inter',
                fill: '#636e72',
                align: 'center',
            }),
        ],
    },

    // 3. Bold & Modern
    {
        id: 'bold-modern',
        name: 'Bold Modern',
        thumbnail: '/templates/bold-modern.png',
        category: 'bold',
        backgroundColor: '#0a0a0a',
        elements: [
            // Large name
            createText({
                id: 'first-name',
                x: 40,
                y: 60,
                width: 520,
                height: 100,
                text: 'MARCUS',
                fontSize: 80,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ffffff',
                letterSpacing: -2,
            }),
            createText({
                id: 'last-name',
                x: 40,
                y: 150,
                width: 520,
                height: 100,
                text: 'RIVERA',
                fontSize: 80,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#8b5cf6',
                letterSpacing: -2,
            }),
            // Job title with line
            createShape({
                id: 'title-line',
                x: 40,
                y: 260,
                width: 100,
                height: 4,
                fill: '#8b5cf6',
            }),
            createText({
                id: 'job-title',
                x: 155,
                y: 252,
                width: 300,
                height: 25,
                text: 'FULL STACK DEVELOPER',
                fontSize: 14,
                fontFamily: 'Inter',
                fill: '#666666',
                letterSpacing: 3,
            }),
            // Profile image
            createImagePlaceholder({
                id: 'profile-image',
                x: 400,
                y: 320,
                width: 160,
                height: 200,
            }),
            // About
            createText({
                id: 'about',
                x: 40,
                y: 320,
                width: 340,
                height: 120,
                text: 'Building digital products that scale. 10+ years crafting web applications, leading engineering teams, and turning complex problems into elegant solutions.',
                fontSize: 13,
                fontFamily: 'Inter',
                fill: '#999999',
                lineHeight: 1.7,
            }),
            // Stats row
            createText({
                id: 'stat-1',
                x: 40,
                y: 480,
                width: 100,
                height: 50,
                text: '50+',
                fontSize: 36,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#8b5cf6',
            }),
            createText({
                id: 'stat-1-label',
                x: 40,
                y: 520,
                width: 100,
                height: 20,
                text: 'PROJECTS',
                fontSize: 10,
                fontFamily: 'Inter',
                fill: '#666666',
                letterSpacing: 1,
            }),
            createText({
                id: 'stat-2',
                x: 160,
                y: 480,
                width: 100,
                height: 50,
                text: '10+',
                fontSize: 36,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#8b5cf6',
            }),
            createText({
                id: 'stat-2-label',
                x: 160,
                y: 520,
                width: 100,
                height: 20,
                text: 'YEARS EXP',
                fontSize: 10,
                fontFamily: 'Inter',
                fill: '#666666',
                letterSpacing: 1,
            }),
            // Skills
            createText({
                id: 'skills-header',
                x: 40,
                y: 590,
                width: 200,
                height: 25,
                text: 'TECH STACK',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ffffff',
                letterSpacing: 2,
            }),
            createText({
                id: 'skills',
                x: 40,
                y: 625,
                width: 500,
                height: 80,
                text: 'React • Node.js • TypeScript • Python • AWS • PostgreSQL • GraphQL • Docker • Kubernetes',
                fontSize: 12,
                fontFamily: 'Inter',
                fill: '#666666',
                lineHeight: 2,
            }),
            // Contact bar at bottom
            createShape({
                id: 'contact-bar',
                x: 0,
                y: 770,
                width: 595,
                height: 72,
                fill: '#8b5cf6',
            }),
            createText({
                id: 'contact-info',
                x: 40,
                y: 795,
                width: 515,
                height: 22,
                text: 'marcus@dev.io    •    github.com/marcus    •    +1 555 123 4567',
                fontSize: 12,
                fontFamily: 'Inter',
                fill: '#ffffff',
                align: 'center',
            }),
        ],
    },

    // 4. Elegant Professional
    {
        id: 'elegant-pro',
        name: 'Elegant Professional',
        thumbnail: '/templates/elegant-pro.png',
        category: 'professional',
        backgroundColor: '#ffffff',
        elements: [
            // Header background
            createShape({
                id: 'header-bg',
                x: 0,
                y: 0,
                width: 595,
                height: 200,
                fill: '#1e3a5f',
            }),
            // Profile image circle
            createImagePlaceholder({
                id: 'profile-image',
                x: 247,
                y: 130,
                width: 100,
                height: 100,
            }),
            // Name
            createText({
                id: 'name',
                x: 50,
                y: 50,
                width: 495,
                height: 45,
                text: 'ELIZABETH PARKER',
                fontSize: 32,
                fontFamily: 'Playfair Display',
                fontWeight: 'bold',
                fill: '#ffffff',
                align: 'center',
                letterSpacing: 3,
            }),
            // Job title
            createText({
                id: 'job-title',
                x: 50,
                y: 95,
                width: 495,
                height: 25,
                text: 'Marketing Director',
                fontSize: 14,
                fontFamily: 'Inter',
                fill: '#7fb3d5',
                align: 'center',
                letterSpacing: 2,
            }),
            // Contact row
            createText({
                id: 'contact',
                x: 50,
                y: 260,
                width: 495,
                height: 20,
                text: 'elizabeth@company.com  •  +1 555 234 5678  •  LinkedIn: /in/eparker',
                fontSize: 10,
                fontFamily: 'Inter',
                fill: '#666666',
                align: 'center',
            }),
            // Divider
            createShape({
                id: 'divider-1',
                x: 200,
                y: 295,
                width: 195,
                height: 1,
                fill: '#1e3a5f',
            }),
            // Summary
            createText({
                id: 'summary-header',
                x: 50,
                y: 320,
                width: 495,
                height: 22,
                text: 'PROFESSIONAL SUMMARY',
                fontSize: 11,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#1e3a5f',
                align: 'center',
                letterSpacing: 2,
            }),
            createText({
                id: 'summary',
                x: 50,
                y: 350,
                width: 495,
                height: 70,
                text: 'Results-driven marketing director with 12+ years of experience leading brand strategy and digital transformation initiatives. Proven track record of increasing market share and driving revenue growth through innovative campaigns.',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#444444',
                align: 'center',
                lineHeight: 1.7,
            }),
            // Two column layout
            // Left column - Experience
            createText({
                id: 'exp-header',
                x: 50,
                y: 450,
                width: 240,
                height: 22,
                text: 'EXPERIENCE',
                fontSize: 11,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#1e3a5f',
                letterSpacing: 2,
            }),
            createShape({
                id: 'exp-underline',
                x: 50,
                y: 475,
                width: 240,
                height: 2,
                fill: '#1e3a5f',
            }),
            createText({
                id: 'exp-1',
                x: 50,
                y: 495,
                width: 240,
                height: 100,
                text: 'Marketing Director\nGlobal Brands Inc.\n2019 - Present\n\nLed rebranding initiative resulting in 40% increase in brand recognition.',
                fontSize: 10,
                fontFamily: 'Inter',
                fill: '#444444',
                lineHeight: 1.6,
            }),
            // Right column - Skills & Education
            createText({
                id: 'skills-header',
                x: 305,
                y: 450,
                width: 240,
                height: 22,
                text: 'SKILLS',
                fontSize: 11,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#1e3a5f',
                letterSpacing: 2,
            }),
            createShape({
                id: 'skills-underline',
                x: 305,
                y: 475,
                width: 240,
                height: 2,
                fill: '#1e3a5f',
            }),
            createText({
                id: 'skills',
                x: 305,
                y: 495,
                width: 240,
                height: 100,
                text: '• Strategic Planning\n• Brand Management\n• Digital Marketing\n• Team Leadership\n• Data Analytics',
                fontSize: 10,
                fontFamily: 'Inter',
                fill: '#444444',
                lineHeight: 1.8,
            }),
            // Education
            createText({
                id: 'edu-header',
                x: 305,
                y: 620,
                width: 240,
                height: 22,
                text: 'EDUCATION',
                fontSize: 11,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#1e3a5f',
                letterSpacing: 2,
            }),
            createShape({
                id: 'edu-underline',
                x: 305,
                y: 645,
                width: 240,
                height: 2,
                fill: '#1e3a5f',
            }),
            createText({
                id: 'education',
                x: 305,
                y: 665,
                width: 240,
                height: 60,
                text: 'MBA, Marketing\nHarvard Business School\n2010',
                fontSize: 10,
                fontFamily: 'Inter',
                fill: '#444444',
                lineHeight: 1.6,
            }),
        ],
    },

    // 5. Creative Gradient
    {
        id: 'creative-gradient',
        name: 'Creative Gradient',
        thumbnail: '/templates/creative-gradient.png',
        category: 'creative',
        backgroundColor: '#0f0c29',
        backgroundGradient: {
            start: '#0f0c29',
            end: '#302b63',
            direction: 135,
        },
        elements: [
            // Decorative circles
            createShape({
                id: 'circle-1',
                x: -50,
                y: -50,
                width: 200,
                height: 200,
                shapeType: 'circle',
                fill: '#00dc82',
                opacity: 0.1,
            }),
            createShape({
                id: 'circle-2',
                x: 450,
                y: 600,
                width: 250,
                height: 250,
                shapeType: 'circle',
                fill: '#8b5cf6',
                opacity: 0.15,
            }),
            // Profile image
            createImagePlaceholder({
                id: 'profile-image',
                x: 50,
                y: 80,
                width: 120,
                height: 120,
            }),
            // Name and title
            createText({
                id: 'name',
                x: 200,
                y: 90,
                width: 350,
                height: 45,
                text: 'JORDAN CHEN',
                fontSize: 38,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ffffff',
            }),
            createText({
                id: 'title',
                x: 200,
                y: 140,
                width: 350,
                height: 25,
                text: 'CREATIVE DIRECTOR',
                fontSize: 14,
                fontFamily: 'Inter',
                fill: '#00dc82',
                letterSpacing: 4,
            }),
            // Gradient line
            createShape({
                id: 'gradient-line',
                x: 200,
                y: 175,
                width: 200,
                height: 3,
                fill: '#00dc82',
            }),
            // About
            createText({
                id: 'about',
                x: 50,
                y: 240,
                width: 500,
                height: 80,
                text: 'Award-winning creative director specializing in brand identity, motion graphics, and immersive digital experiences. Blending artistic vision with strategic thinking to create memorable brand narratives.',
                fontSize: 12,
                fontFamily: 'Inter',
                fill: '#a0aec0',
                lineHeight: 1.7,
            }),
            // Two columns
            // Experience
            createText({
                id: 'exp-header',
                x: 50,
                y: 360,
                width: 250,
                height: 25,
                text: 'EXPERIENCE',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#00dc82',
                letterSpacing: 2,
            }),
            createText({
                id: 'exp-1-title',
                x: 50,
                y: 395,
                width: 250,
                height: 22,
                text: 'Creative Director',
                fontSize: 14,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ffffff',
            }),
            createText({
                id: 'exp-1-company',
                x: 50,
                y: 420,
                width: 250,
                height: 20,
                text: 'Innovation Labs • 2020 - Present',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#718096',
            }),
            createText({
                id: 'exp-1-desc',
                x: 50,
                y: 445,
                width: 250,
                height: 60,
                text: 'Leading creative vision for Fortune 500 clients, directing teams of 15+ designers and artists.',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#a0aec0',
                lineHeight: 1.5,
            }),
            createText({
                id: 'exp-2-title',
                x: 50,
                y: 520,
                width: 250,
                height: 22,
                text: 'Senior Designer',
                fontSize: 14,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#ffffff',
            }),
            createText({
                id: 'exp-2-company',
                x: 50,
                y: 545,
                width: 250,
                height: 20,
                text: 'Digital Dreams Agency • 2016 - 2020',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#718096',
            }),
            // Skills
            createText({
                id: 'skills-header',
                x: 330,
                y: 360,
                width: 220,
                height: 25,
                text: 'SKILLS',
                fontSize: 12,
                fontFamily: 'Inter',
                fontWeight: 'bold',
                fill: '#8b5cf6',
                letterSpacing: 2,
            }),
            // Skill bars
            createText({
                id: 'skill-1',
                x: 330,
                y: 395,
                width: 150,
                height: 20,
                text: 'Brand Strategy',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#ffffff',
            }),
            createShape({
                id: 'skill-1-bar-bg',
                x: 330,
                y: 418,
                width: 220,
                height: 6,
                fill: '#2d3748',
                cornerRadius: 3,
            }),
            createShape({
                id: 'skill-1-bar',
                x: 330,
                y: 418,
                width: 200,
                height: 6,
                fill: '#00dc82',
                cornerRadius: 3,
            }),
            createText({
                id: 'skill-2',
                x: 330,
                y: 445,
                width: 150,
                height: 20,
                text: 'Motion Design',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#ffffff',
            }),
            createShape({
                id: 'skill-2-bar-bg',
                x: 330,
                y: 468,
                width: 220,
                height: 6,
                fill: '#2d3748',
                cornerRadius: 3,
            }),
            createShape({
                id: 'skill-2-bar',
                x: 330,
                y: 468,
                width: 190,
                height: 6,
                fill: '#8b5cf6',
                cornerRadius: 3,
            }),
            createText({
                id: 'skill-3',
                x: 330,
                y: 495,
                width: 150,
                height: 20,
                text: 'UI/UX Design',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#ffffff',
            }),
            createShape({
                id: 'skill-3-bar-bg',
                x: 330,
                y: 518,
                width: 220,
                height: 6,
                fill: '#2d3748',
                cornerRadius: 3,
            }),
            createShape({
                id: 'skill-3-bar',
                x: 330,
                y: 518,
                width: 210,
                height: 6,
                fill: '#00dc82',
                cornerRadius: 3,
            }),
            // Contact footer
            createShape({
                id: 'footer-line',
                x: 50,
                y: 750,
                width: 500,
                height: 1,
                fill: '#4a5568',
            }),
            createText({
                id: 'contact',
                x: 50,
                y: 770,
                width: 500,
                height: 30,
                text: 'jordan@creative.io   |   +1 555 789 0123   |   jordanchen.design',
                fontSize: 11,
                fontFamily: 'Inter',
                fill: '#a0aec0',
                align: 'center',
            }),
        ],
    },
];

export default canvasTemplates;
