import { selectContent } from './types';

export interface CommunityContent {
  title: string;
  subtitle: string;
  categories: { value: string; label: string }[];
  browseTab: string;
  myTemplatesTab: string;
  templatesAvailable: string;
  templateAvailable: string;
  createYourOwn: string;
  errorMessage: string;
  tryAgain: string;
  noTemplatesTitle: string;
  noTemplatesSub: string;
  createTemplate: string;
  pageOf: string;
  templatesPosted: string;
  templatePosted: string;
  createNewTemplate: string;
  noPostedTitle: string;
  noPostedSub: string;
  publicLabel: string;
  privateLabel: string;
  noPreview: string;
  downloads: string;
  download: string;
  signInTitle: string;
  signInSub: string;
  signIn: string;
  deleteConfirm: string;
  deleteError: string;
  visibilityError: string;
  makePrivate: string;
  makePublic: string;
  edit: string;
  deleteBtn: string;
}

const en: CommunityContent = {
  title: 'Community Templates',
  subtitle: 'Browse and use templates shared by the community',
  categories: [
    { value: '', label: 'All' },
    { value: 'professional', label: 'Professional' },
    { value: 'creative', label: 'Creative' },
    { value: 'ats', label: 'ATS-Friendly' },
    { value: 'bold', label: 'Bold' },
  ],
  browseTab: 'Browse Templates',
  myTemplatesTab: 'My Templates',
  templatesAvailable: '{count} templates available',
  templateAvailable: '{count} template available',
  createYourOwn: 'Create your own \u2192',
  errorMessage: 'Failed to load templates. Please try again.',
  tryAgain: 'Try Again',
  noTemplatesTitle: 'No templates yet',
  noTemplatesSub: 'Be the first to share a template with the community!',
  createTemplate: 'Create Template',
  pageOf: 'Page {page} of {total}',
  templatesPosted: '{count} templates posted',
  templatePosted: '{count} template posted',
  createNewTemplate: 'Create new template \u2192',
  noPostedTitle: 'No templates posted yet',
  noPostedSub: 'Create a design in the canvas editor and share it with the community!',
  publicLabel: 'Public',
  privateLabel: 'Private',
  noPreview: 'No preview',
  downloads: 'downloads',
  download: 'download',
  signInTitle: 'Sign in to view your templates',
  signInSub: 'You need to be signed in to see and manage your posted templates.',
  signIn: 'Sign In',
  deleteConfirm: 'Are you sure you want to delete this template? This cannot be undone.',
  deleteError: 'Failed to delete template. Please try again.',
  visibilityError: 'Failed to update visibility. Please try again.',
  makePrivate: 'Make private',
  makePublic: 'Make public',
  edit: 'Edit',
  deleteBtn: 'Delete',
};

const es: CommunityContent = {
  title: 'Plantillas de la Comunidad',
  subtitle: 'Explora y usa plantillas compartidas por la comunidad',
  categories: [
    { value: '', label: 'Todas' },
    { value: 'professional', label: 'Profesional' },
    { value: 'creative', label: 'Creativa' },
    { value: 'ats', label: 'Compatible con ATS' },
    { value: 'bold', label: 'Audaz' },
  ],
  browseTab: 'Explorar Plantillas',
  myTemplatesTab: 'Mis Plantillas',
  templatesAvailable: '{count} plantillas disponibles',
  templateAvailable: '{count} plantilla disponible',
  createYourOwn: 'Crea la tuya \u2192',
  errorMessage: 'Error al cargar las plantillas. Int\u00e9ntalo de nuevo.',
  tryAgain: 'Intentar de Nuevo',
  noTemplatesTitle: 'A\u00fan no hay plantillas',
  noTemplatesSub: '\u00a1S\u00e9 el primero en compartir una plantilla con la comunidad!',
  createTemplate: 'Crear Plantilla',
  pageOf: 'P\u00e1gina {page} de {total}',
  templatesPosted: '{count} plantillas publicadas',
  templatePosted: '{count} plantilla publicada',
  createNewTemplate: 'Crear nueva plantilla \u2192',
  noPostedTitle: 'A\u00fan no has publicado plantillas',
  noPostedSub: '\u00a1Crea un dise\u00f1o en el editor de canvas y comp\u00e1rtelo con la comunidad!',
  publicLabel: 'P\u00fablica',
  privateLabel: 'Privada',
  noPreview: 'Sin vista previa',
  downloads: 'descargas',
  download: 'descarga',
  signInTitle: 'Inicia sesi\u00f3n para ver tus plantillas',
  signInSub: 'Debes iniciar sesi\u00f3n para ver y gestionar tus plantillas publicadas.',
  signIn: 'Iniciar Sesi\u00f3n',
  deleteConfirm: '\u00bfEst\u00e1s seguro de que quieres eliminar esta plantilla? Esta acci\u00f3n no se puede deshacer.',
  deleteError: 'Error al eliminar la plantilla. Int\u00e9ntalo de nuevo.',
  visibilityError: 'Error al actualizar la visibilidad. Int\u00e9ntalo de nuevo.',
  makePrivate: 'Hacer privada',
  makePublic: 'Hacer p\u00fablica',
  edit: 'Editar',
  deleteBtn: 'Eliminar',
};

const fr: CommunityContent = {
  title: 'Modèles de la Communauté',
  subtitle: 'Parcourez et utilisez les modèles partagés par la communauté',
  categories: [
    { value: '', label: 'Tous' },
    { value: 'professional', label: 'Professionnel' },
    { value: 'creative', label: 'Créatif' },
    { value: 'ats', label: 'Optimisé ATS' },
    { value: 'bold', label: 'Audacieux' },
  ],
  browseTab: 'Parcourir les modèles',
  myTemplatesTab: 'Mes modèles',
  templatesAvailable: '{count} modèles disponibles',
  templateAvailable: '{count} modèle disponible',
  createYourOwn: 'Créez le vôtre \u2192',
  errorMessage: 'Impossible de charger les modèles. Veuillez réessayer.',
  tryAgain: 'Réessayer',
  noTemplatesTitle: 'Aucun modèle pour le moment',
  noTemplatesSub: 'Soyez le premier à partager un modèle avec la communauté\u00a0!',
  createTemplate: 'Créer un modèle',
  pageOf: 'Page {page} sur {total}',
  templatesPosted: '{count} modèles publiés',
  templatePosted: '{count} modèle publié',
  createNewTemplate: 'Créer un nouveau modèle \u2192',
  noPostedTitle: 'Aucun modèle publié',
  noPostedSub: 'Créez un design dans l\u2019éditeur de canvas et partagez-le avec la communauté\u00a0!',
  publicLabel: 'Public',
  privateLabel: 'Privé',
  noPreview: 'Aucun aperçu',
  downloads: 'téléchargements',
  download: 'téléchargement',
  signInTitle: 'Connectez-vous pour voir vos modèles',
  signInSub: 'Vous devez être connecté pour consulter et gérer vos modèles publiés.',
  signIn: 'Se connecter',
  deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ce modèle\u00a0? Cette action est irréversible.',
  deleteError: 'Impossible de supprimer le modèle. Veuillez réessayer.',
  visibilityError: 'Impossible de modifier la visibilité. Veuillez réessayer.',
  makePrivate: 'Rendre privé',
  makePublic: 'Rendre public',
  edit: 'Modifier',
  deleteBtn: 'Supprimer',
};

const de: CommunityContent = {
  title: 'Community-Vorlagen',
  subtitle: 'Entdecke und nutze Vorlagen, die von der Community geteilt wurden',
  categories: [
    { value: '', label: 'Alle' },
    { value: 'professional', label: 'Professionell' },
    { value: 'creative', label: 'Kreativ' },
    { value: 'ats', label: 'ATS-optimiert' },
    { value: 'bold', label: 'Ausdrucksstark' },
  ],
  browseTab: 'Vorlagen durchsuchen',
  myTemplatesTab: 'Meine Vorlagen',
  templatesAvailable: '{count} Vorlagen verfügbar',
  templateAvailable: '{count} Vorlage verfügbar',
  createYourOwn: 'Eigene erstellen \u2192',
  errorMessage: 'Vorlagen konnten nicht geladen werden. Bitte versuche es erneut.',
  tryAgain: 'Erneut versuchen',
  noTemplatesTitle: 'Noch keine Vorlagen',
  noTemplatesSub: 'Sei der Erste, der eine Vorlage mit der Community teilt!',
  createTemplate: 'Vorlage erstellen',
  pageOf: 'Seite {page} von {total}',
  templatesPosted: '{count} Vorlagen veröffentlicht',
  templatePosted: '{count} Vorlage veröffentlicht',
  createNewTemplate: 'Neue Vorlage erstellen \u2192',
  noPostedTitle: 'Noch keine Vorlagen veröffentlicht',
  noPostedSub: 'Erstelle ein Design im Canvas-Editor und teile es mit der Community!',
  publicLabel: 'Öffentlich',
  privateLabel: 'Privat',
  noPreview: 'Keine Vorschau',
  downloads: 'Downloads',
  download: 'Download',
  signInTitle: 'Melde dich an, um deine Vorlagen zu sehen',
  signInSub: 'Du musst angemeldet sein, um deine veröffentlichten Vorlagen anzuzeigen und zu verwalten.',
  signIn: 'Anmelden',
  deleteConfirm: 'Bist du sicher, dass du diese Vorlage löschen möchtest? Dies kann nicht rückgängig gemacht werden.',
  deleteError: 'Vorlage konnte nicht gelöscht werden. Bitte versuche es erneut.',
  visibilityError: 'Sichtbarkeit konnte nicht geändert werden. Bitte versuche es erneut.',
  makePrivate: 'Privat stellen',
  makePublic: 'Öffentlich stellen',
  edit: 'Bearbeiten',
  deleteBtn: 'Löschen',
};

const ar: CommunityContent = {
  title: 'قوالب المجتمع',
  subtitle: 'تصفّح واستخدم القوالب التي شاركها أعضاء المجتمع',
  categories: [
    { value: '', label: 'الكل' },
    { value: 'professional', label: 'احترافي' },
    { value: 'creative', label: 'إبداعي' },
    { value: 'ats', label: 'متوافق مع ATS' },
    { value: 'bold', label: 'جريء' },
  ],
  browseTab: 'تصفّح القوالب',
  myTemplatesTab: 'قوالبي',
  templatesAvailable: '{count} قوالب متاحة',
  templateAvailable: '{count} قالب متاح',
  createYourOwn: 'أنشئ قالبك الخاص \u2192',
  errorMessage: 'تعذّر تحميل القوالب. يرجى المحاولة مرة أخرى.',
  tryAgain: 'حاول مجدداً',
  noTemplatesTitle: 'لا توجد قوالب بعد',
  noTemplatesSub: 'كن أول من يشارك قالباً مع المجتمع!',
  createTemplate: 'إنشاء قالب',
  pageOf: 'صفحة {page} من {total}',
  templatesPosted: '{count} قوالب منشورة',
  templatePosted: '{count} قالب منشور',
  createNewTemplate: 'إنشاء قالب جديد \u2192',
  noPostedTitle: 'لم تنشر أي قوالب بعد',
  noPostedSub: 'صمّم قالباً في محرر التصميم وشاركه مع المجتمع!',
  publicLabel: 'عام',
  privateLabel: 'خاص',
  noPreview: 'لا توجد معاينة',
  downloads: 'تنزيلات',
  download: 'تنزيل',
  signInTitle: 'سجّل الدخول لعرض قوالبك',
  signInSub: 'يجب تسجيل الدخول لعرض وإدارة القوالب التي نشرتها.',
  signIn: 'تسجيل الدخول',
  deleteConfirm: 'هل أنت متأكد من حذف هذا القالب؟ لا يمكن التراجع عن هذا الإجراء.',
  deleteError: 'تعذّر حذف القالب. يرجى المحاولة مرة أخرى.',
  visibilityError: 'تعذّر تحديث مستوى الظهور. يرجى المحاولة مرة أخرى.',
  makePrivate: 'جعله خاصاً',
  makePublic: 'جعله عاماً',
  edit: 'تعديل',
  deleteBtn: 'حذف',
};

const ja: CommunityContent = {
  title: 'コミュニティテンプレート',
  subtitle: 'コミュニティで共有されたテンプレートを閲覧・利用できます',
  categories: [
    { value: '', label: 'すべて' },
    { value: 'professional', label: 'プロフェッショナル' },
    { value: 'creative', label: 'クリエイティブ' },
    { value: 'ats', label: 'ATS対応' },
    { value: 'bold', label: 'インパクト' },
  ],
  browseTab: 'テンプレートを探す',
  myTemplatesTab: 'マイテンプレート',
  templatesAvailable: '{count}件のテンプレートが利用可能',
  templateAvailable: '{count}件のテンプレートが利用可能',
  createYourOwn: '自分のテンプレートを作成 \u2192',
  errorMessage: 'テンプレートの読み込みに失敗しました。もう一度お試しください。',
  tryAgain: '再試行',
  noTemplatesTitle: 'まだテンプレートがありません',
  noTemplatesSub: 'コミュニティで最初のテンプレートを共有しましょう！',
  createTemplate: 'テンプレートを作成',
  pageOf: '{page} / {total}ページ',
  templatesPosted: '{count}件のテンプレートを公開中',
  templatePosted: '{count}件のテンプレートを公開中',
  createNewTemplate: '新しいテンプレートを作成 \u2192',
  noPostedTitle: 'まだテンプレートを公開していません',
  noPostedSub: 'キャンバスエディタでデザインを作成し、コミュニティと共有しましょう！',
  publicLabel: '公開',
  privateLabel: '非公開',
  noPreview: 'プレビューなし',
  downloads: 'ダウンロード',
  download: 'ダウンロード',
  signInTitle: 'テンプレートを表示するにはログインしてください',
  signInSub: '公開したテンプレートの表示・管理にはログインが必要です。',
  signIn: 'ログイン',
  deleteConfirm: 'このテンプレートを削除してもよろしいですか？この操作は取り消せません。',
  deleteError: 'テンプレートの削除に失敗しました。もう一度お試しください。',
  visibilityError: '公開設定の変更に失敗しました。もう一度お試しください。',
  makePrivate: '非公開にする',
  makePublic: '公開にする',
  edit: '編集',
  deleteBtn: '削除',
};

const it: CommunityContent = {
  title: 'Modelli della Comunità',
  subtitle: 'Esplora e utilizza i modelli condivisi dalla comunità',
  categories: [
    { value: '', label: 'Tutti' },
    { value: 'professional', label: 'Professionale' },
    { value: 'creative', label: 'Creativo' },
    { value: 'ats', label: 'Ottimizzato ATS' },
    { value: 'bold', label: 'Audace' },
  ],
  browseTab: 'Sfoglia Modelli',
  myTemplatesTab: 'I Miei Modelli',
  templatesAvailable: '{count} modelli disponibili',
  templateAvailable: '{count} modello disponibile',
  createYourOwn: 'Crea il tuo \u2192',
  errorMessage: 'Impossibile caricare i modelli. Riprova.',
  tryAgain: 'Riprova',
  noTemplatesTitle: 'Nessun modello ancora',
  noTemplatesSub: 'Sii il primo a condividere un modello con la comunità!',
  createTemplate: 'Crea Modello',
  pageOf: 'Pagina {page} di {total}',
  templatesPosted: '{count} modelli pubblicati',
  templatePosted: '{count} modello pubblicato',
  createNewTemplate: 'Crea nuovo modello \u2192',
  noPostedTitle: 'Non hai ancora pubblicato modelli',
  noPostedSub: 'Crea un design nell\'editor canvas e condividilo con la comunità!',
  publicLabel: 'Pubblico',
  privateLabel: 'Privato',
  noPreview: 'Nessuna anteprima',
  downloads: 'download',
  download: 'download',
  signInTitle: 'Accedi per visualizzare i tuoi modelli',
  signInSub: 'Devi accedere per visualizzare e gestire i modelli che hai pubblicato.',
  signIn: 'Accedi',
  deleteConfirm: 'Sei sicuro di voler eliminare questo modello? L\'azione non può essere annullata.',
  deleteError: 'Impossibile eliminare il modello. Riprova.',
  visibilityError: 'Impossibile aggiornare la visibilità. Riprova.',
  makePrivate: 'Rendi privato',
  makePublic: 'Rendi pubblico',
  edit: 'Modifica',
  deleteBtn: 'Elimina',
};

const ko: CommunityContent = {
  title: '커뮤니티 이력서 템플릿',
  subtitle: '커뮤니티에서 공유한 이력서 템플릿을 둘러보고 바로 활용하세요',
  categories: [
    { value: '', label: '전체' },
    { value: 'professional', label: '프로페셔널' },
    { value: 'creative', label: '크리에이티브' },
    { value: 'ats', label: 'ATS 최적화' },
    { value: 'bold', label: '임팩트' },
  ],
  browseTab: '템플릿 둘러보기',
  myTemplatesTab: '내 템플릿',
  templatesAvailable: '{count}개 템플릿 이용 가능',
  templateAvailable: '{count}개 템플릿 이용 가능',
  createYourOwn: '나만의 이력서 만들기 \u2192',
  errorMessage: '템플릿을 불러오지 못했습니다. 다시 시도해 주세요.',
  tryAgain: '다시 시도',
  noTemplatesTitle: '아직 템플릿이 없습니다',
  noTemplatesSub: '커뮤니티에 첫 번째 이력서 템플릿을 공유해 보세요!',
  createTemplate: '템플릿 만들기',
  pageOf: '{page} / {total} 페이지',
  templatesPosted: '{count}개 템플릿 게시됨',
  templatePosted: '{count}개 템플릿 게시됨',
  createNewTemplate: '새 템플릿 만들기 \u2192',
  noPostedTitle: '아직 게시한 템플릿이 없습니다',
  noPostedSub: '캔버스 에디터에서 이력서를 디자인하고 커뮤니티와 공유하세요!',
  publicLabel: '공개',
  privateLabel: '비공개',
  noPreview: '미리보기 없음',
  downloads: '다운로드',
  download: '다운로드',
  signInTitle: '내 템플릿을 보려면 로그인하세요',
  signInSub: '게시한 이력서 템플릿을 확인하고 관리하려면 로그인이 필요합니다.',
  signIn: '로그인',
  deleteConfirm: '이 템플릿을 정말 삭제하시겠습니까? 삭제 후에는 복구할 수 없습니다.',
  deleteError: '템플릿 삭제에 실패했습니다. 다시 시도해 주세요.',
  visibilityError: '공개 설정 변경에 실패했습니다. 다시 시도해 주세요.',
  makePrivate: '비공개로 전환',
  makePublic: '공개로 전환',
  edit: '수정',
  deleteBtn: '삭제',
};

const vi: CommunityContent = {
  title: 'Mẫu CV Cộng Đồng',
  subtitle: 'Duyệt và sử dụng các mẫu CV được chia sẻ bởi cộng đồng',
  categories: [
    { value: '', label: 'Tất Cả' },
    { value: 'professional', label: 'Chuyên Nghiệp' },
    { value: 'creative', label: 'Sáng Tạo' },
    { value: 'ats', label: 'Thân Thiện ATS' },
    { value: 'bold', label: 'Nổi Bật' },
  ],
  browseTab: 'Duyệt Mẫu CV',
  myTemplatesTab: 'Mẫu Của Tôi',
  templatesAvailable: '{count} mẫu có sẵn',
  templateAvailable: '{count} mẫu có sẵn',
  createYourOwn: 'Tạo mẫu của bạn \u2192',
  errorMessage: 'Không thể tải mẫu CV. Vui lòng thử lại.',
  tryAgain: 'Thử Lại',
  noTemplatesTitle: 'Chưa có mẫu nào',
  noTemplatesSub: 'Hãy là người đầu tiên chia sẻ mẫu CV với cộng đồng!',
  createTemplate: 'Tạo Mẫu CV',
  pageOf: 'Trang {page} / {total}',
  templatesPosted: '{count} mẫu đã đăng',
  templatePosted: '{count} mẫu đã đăng',
  createNewTemplate: 'Tạo mẫu mới \u2192',
  noPostedTitle: 'Bạn chưa đăng mẫu nào',
  noPostedSub: 'Thiết kế CV trong trình soạn thảo và chia sẻ với cộng đồng!',
  publicLabel: 'Công Khai',
  privateLabel: 'Riêng Tư',
  noPreview: 'Không có bản xem trước',
  downloads: 'lượt tải',
  download: 'lượt tải',
  signInTitle: 'Đăng nhập để xem mẫu của bạn',
  signInSub: 'Bạn cần đăng nhập để xem và quản lý các mẫu CV đã đăng.',
  signIn: 'Đăng Nhập',
  deleteConfirm: 'Bạn có chắc chắn muốn xóa mẫu này? Hành động này không thể hoàn tác.',
  deleteError: 'Không thể xóa mẫu. Vui lòng thử lại.',
  visibilityError: 'Không thể cập nhật chế độ hiển thị. Vui lòng thử lại.',
  makePrivate: 'Chuyển sang riêng tư',
  makePublic: 'Chuyển sang công khai',
  edit: 'Sửa',
  deleteBtn: 'Xóa',
};

const th: CommunityContent = {
  title: 'เทมเพลตจากชุมชน',
  subtitle: 'เรียกดูและใช้เทมเพลตที่แชร์โดยสมาชิกในชุมชน',
  categories: [
    { value: '', label: 'ทั้งหมด' },
    { value: 'professional', label: 'มืออาชีพ' },
    { value: 'creative', label: 'สร้างสรรค์' },
    { value: 'ats', label: 'รองรับ ATS' },
    { value: 'bold', label: 'โดดเด่น' },
  ],
  browseTab: 'เรียกดูเทมเพลต',
  myTemplatesTab: 'เทมเพลตของฉัน',
  templatesAvailable: '{count} เทมเพลตที่ใช้งานได้',
  templateAvailable: '{count} เทมเพลตที่ใช้งานได้',
  createYourOwn: 'สร้างเทมเพลตของคุณเอง \u2192',
  errorMessage: 'ไม่สามารถโหลดเทมเพลตได้ กรุณาลองอีกครั้ง',
  tryAgain: 'ลองอีกครั้ง',
  noTemplatesTitle: 'ยังไม่มีเทมเพลต',
  noTemplatesSub: 'เป็นคนแรกที่แชร์เทมเพลตกับชุมชน!',
  createTemplate: 'สร้างเทมเพลต',
  pageOf: 'หน้า {page} จาก {total}',
  templatesPosted: '{count} เทมเพลตที่โพสต์แล้ว',
  templatePosted: '{count} เทมเพลตที่โพสต์แล้ว',
  createNewTemplate: 'สร้างเทมเพลตใหม่ \u2192',
  noPostedTitle: 'คุณยังไม่ได้โพสต์เทมเพลต',
  noPostedSub: 'สร้างดีไซน์ในตัวแก้ไขแคนวาสและแชร์กับชุมชน!',
  publicLabel: 'สาธารณะ',
  privateLabel: 'ส่วนตัว',
  noPreview: 'ไม่มีตัวอย่าง',
  downloads: 'ดาวน์โหลด',
  download: 'ดาวน์โหลด',
  signInTitle: 'เข้าสู่ระบบเพื่อดูเทมเพลตของคุณ',
  signInSub: 'คุณต้องเข้าสู่ระบบเพื่อดูและจัดการเทมเพลตที่โพสต์ไว้',
  signIn: 'เข้าสู่ระบบ',
  deleteConfirm: 'คุณแน่ใจหรือไม่ว่าต้องการลบเทมเพลตนี้? การดำเนินการนี้ไม่สามารถยกเลิกได้',
  deleteError: 'ไม่สามารถลบเทมเพลตได้ กรุณาลองอีกครั้ง',
  visibilityError: 'ไม่สามารถอัปเดตการแสดงผลได้ กรุณาลองอีกครั้ง',
  makePrivate: 'ตั้งเป็นส่วนตัว',
  makePublic: 'ตั้งเป็นสาธารณะ',
  edit: 'แก้ไข',
  deleteBtn: 'ลบ',
};

const pt: CommunityContent = {
  title: 'Modelos da Comunidade',
  subtitle: 'Explore e use modelos compartilhados pela comunidade',
  categories: [
    { value: '', label: 'Todos' },
    { value: 'professional', label: 'Profissional' },
    { value: 'creative', label: 'Criativo' },
    { value: 'ats', label: 'Otimizado ATS' },
    { value: 'bold', label: 'Ousado' },
  ],
  browseTab: 'Explorar Modelos',
  myTemplatesTab: 'Meus Modelos',
  templatesAvailable: '{count} modelos disponiveis',
  templateAvailable: '{count} modelo disponivel',
  createYourOwn: 'Crie o seu →',
  errorMessage: 'Nao foi possivel carregar os modelos. Tente novamente.',
  tryAgain: 'Tentar Novamente',
  noTemplatesTitle: 'Nenhum modelo ainda',
  noTemplatesSub: 'Seja o primeiro a compartilhar um modelo com a comunidade!',
  createTemplate: 'Criar Modelo',
  pageOf: 'Pagina {page} de {total}',
  templatesPosted: '{count} modelos publicados',
  templatePosted: '{count} modelo publicado',
  createNewTemplate: 'Criar novo modelo →',
  noPostedTitle: 'Voce ainda nao publicou modelos',
  noPostedSub: 'Crie um design no editor canvas e compartilhe com a comunidade!',
  publicLabel: 'Publico',
  privateLabel: 'Privado',
  noPreview: 'Sem previa',
  downloads: 'downloads',
  download: 'download',
  signInTitle: 'Faca login para ver seus modelos',
  signInSub: 'Voce precisa estar logado para ver e gerenciar os modelos que publicou.',
  signIn: 'Entrar',
  deleteConfirm: 'Tem certeza que deseja excluir este modelo? Esta acao nao pode ser desfeita.',
  deleteError: 'Nao foi possivel excluir o modelo. Tente novamente.',
  visibilityError: 'Nao foi possivel atualizar a visibilidade. Tente novamente.',
  makePrivate: 'Tornar privado',
  makePublic: 'Tornar publico',
  edit: 'Editar',
  deleteBtn: 'Excluir',
};

const tr: CommunityContent = {
  title: 'Topluluk Şablonları',
  subtitle: 'Topluluk tarafından paylaşılan şablonları keşfedin ve kullanın',
  categories: [
    { value: '', label: 'Tümü' },
    { value: 'professional', label: 'Profesyonel' },
    { value: 'creative', label: 'Yaratıcı' },
    { value: 'ats', label: 'ATS Optimize' },
    { value: 'bold', label: 'Dikkat Çekici' },
  ],
  browseTab: 'Şablonları Keşfet',
  myTemplatesTab: 'Şablonlarım',
  templatesAvailable: '{count} şablon mevcut',
  templateAvailable: '{count} şablon mevcut',
  createYourOwn: 'Kendinizinkini Oluşturun →',
  errorMessage: 'Şablonlar yüklenemedi. Lütfen tekrar deneyin.',
  tryAgain: 'Tekrar Dene',
  noTemplatesTitle: 'Henüz şablon yok',
  noTemplatesSub: 'Toplulukla ilk şablonu paylaşan siz olun!',
  createTemplate: 'Şablon Oluştur',
  pageOf: 'Sayfa {page} / {total}',
  templatesPosted: '{count} şablon yayınlandı',
  templatePosted: '{count} şablon yayınlandı',
  createNewTemplate: 'Yeni şablon oluştur →',
  noPostedTitle: 'Henüz şablon yayınlamadınız',
  noPostedSub: 'Canvas editörde bir tasarım oluşturun ve toplulukla paylaşın!',
  publicLabel: 'Herkese Açık',
  privateLabel: 'Özel',
  noPreview: 'Önizleme yok',
  downloads: 'indirme',
  download: 'indir',
  signInTitle: 'Şablonlarınızı görmek için giriş yapın',
  signInSub: 'Yayınladığınız şablonları görmek ve yönetmek için giriş yapmanız gerekiyor.',
  signIn: 'Giriş Yap',
  deleteConfirm: 'Bu şablonu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
  deleteError: 'Şablon silinemedi. Lütfen tekrar deneyin.',
  visibilityError: 'Görünürlük güncellenemedi. Lütfen tekrar deneyin.',
  makePrivate: 'Özel Yap',
  makePublic: 'Herkese Açık Yap',
  edit: 'Düzenle',
  deleteBtn: 'Sil',
};

const id: CommunityContent = {
  title: 'Template Komunitas',
  subtitle: 'Temukan dan gunakan template yang dibagikan oleh komunitas',
  categories: [
    { value: '', label: 'Semua' },
    { value: 'professional', label: 'Profesional' },
    { value: 'creative', label: 'Kreatif' },
    { value: 'ats', label: 'Teroptimasi ATS' },
    { value: 'bold', label: 'Mencolok' },
  ],
  browseTab: 'Jelajahi Template',
  myTemplatesTab: 'Template Saya',
  templatesAvailable: '{count} template tersedia',
  templateAvailable: '{count} template tersedia',
  createYourOwn: 'Buat milik Anda →',
  errorMessage: 'Gagal memuat template. Silakan coba lagi.',
  tryAgain: 'Coba Lagi',
  noTemplatesTitle: 'Belum ada template',
  noTemplatesSub: 'Jadilah yang pertama berbagi template dengan komunitas!',
  createTemplate: 'Buat Template',
  pageOf: 'Halaman {page} / {total}',
  templatesPosted: '{count} template dipublikasikan',
  templatePosted: '{count} template dipublikasikan',
  createNewTemplate: 'Buat template baru →',
  noPostedTitle: 'Anda belum memposting template',
  noPostedSub: 'Buat desain di editor Canvas dan bagikan dengan komunitas!',
  publicLabel: 'Publik',
  privateLabel: 'Privat',
  noPreview: 'Tidak ada pratinjau',
  downloads: 'unduhan',
  download: 'unduh',
  signInTitle: 'Masuk untuk melihat template Anda',
  signInSub: 'Anda perlu masuk untuk melihat dan mengelola template yang telah Anda publikasikan.',
  signIn: 'Masuk',
  deleteConfirm: 'Apakah Anda yakin ingin menghapus template ini? Tindakan ini tidak dapat dibatalkan.',
  deleteError: 'Gagal menghapus template. Silakan coba lagi.',
  visibilityError: 'Gagal memperbarui visibilitas. Silakan coba lagi.',
  makePrivate: 'Jadikan Privat',
  makePublic: 'Jadikan Publik',
  edit: 'Edit',
  deleteBtn: 'Hapus',
};

const pl: CommunityContent = {
  title: 'Szablony Społeczności',
  subtitle: 'Odkryj i użyj szablonów udostępnionych przez społeczność',
  categories: [
    { value: '', label: 'Wszystkie' },
    { value: 'professional', label: 'Profesjonalne' },
    { value: 'creative', label: 'Kreatywne' },
    { value: 'ats', label: 'Zoptymalizowane pod ATS' },
    { value: 'bold', label: 'Odważne' },
  ],
  browseTab: 'Przeglądaj szablony',
  myTemplatesTab: 'Moje szablony',
  templatesAvailable: '{count} dostępnych szablonów',
  templateAvailable: '{count} dostępny szablon',
  createYourOwn: 'Stwórz własny →',
  errorMessage: 'Nie udało się załadować szablonów. Spróbuj ponownie.',
  tryAgain: 'Spróbuj ponownie',
  noTemplatesTitle: 'Brak szablonów',
  noTemplatesSub: 'Bądź pierwszym, który udostępni szablon społeczności!',
  createTemplate: 'Utwórz szablon',
  pageOf: 'Strona {page} / {total}',
  templatesPosted: '{count} opublikowanych szablonów',
  templatePosted: '{count} opublikowany szablon',
  createNewTemplate: 'Utwórz nowy szablon →',
  noPostedTitle: 'Nie opublikowano jeszcze żadnych szablonów',
  noPostedSub: 'Stwórz projekt w edytorze Canvas i udostępnij go społeczności!',
  publicLabel: 'Publiczny',
  privateLabel: 'Prywatny',
  noPreview: 'Brak podglądu',
  downloads: 'pobrania',
  download: 'pobierz',
  signInTitle: 'Zaloguj się, aby zobaczyć swoje szablony',
  signInSub: 'Musisz się zalogować, aby zobaczyć i zarządzać opublikowanymi szablonami.',
  signIn: 'Zaloguj się',
  deleteConfirm: 'Czy na pewno chcesz usunąć ten szablon? Tej akcji nie można cofnąć.',
  deleteError: 'Nie udało się usunąć szablonu. Spróbuj ponownie.',
  visibilityError: 'Nie udało się zaktualizować widoczności. Spróbuj ponownie.',
  makePrivate: 'Ustaw jako prywatny',
  makePublic: 'Ustaw jako publiczny',
  edit: 'Edytuj',
  deleteBtn: 'Usuń',
};

const nl: CommunityContent = {
  title: 'Community Sjablonen',
  subtitle: 'Bekijk en gebruik sjablonen gedeeld door de community',
  categories: [
    { value: '', label: 'Alle' },
    { value: 'professional', label: 'Professioneel' },
    { value: 'creative', label: 'Creatief' },
    { value: 'ats', label: 'ATS-vriendelijk' },
    { value: 'bold', label: 'Gedurfd' },
  ],
  browseTab: 'Sjablonen Bekijken',
  myTemplatesTab: 'Mijn Sjablonen',
  templatesAvailable: '{count} sjablonen beschikbaar',
  templateAvailable: '{count} sjabloon beschikbaar',
  createYourOwn: 'Maak je eigen \u2192',
  errorMessage: 'Laden van sjablonen mislukt. Probeer het opnieuw.',
  tryAgain: 'Opnieuw Proberen',
  noTemplatesTitle: 'Nog geen sjablonen',
  noTemplatesSub: 'Wees de eerste die een sjabloon deelt met de community!',
  createTemplate: 'Sjabloon Maken',
  pageOf: 'Pagina {page} van {total}',
  templatesPosted: '{count} sjablonen geplaatst',
  templatePosted: '{count} sjabloon geplaatst',
  createNewTemplate: 'Nieuw sjabloon maken \u2192',
  noPostedTitle: 'Nog geen sjablonen geplaatst',
  noPostedSub: 'Maak een ontwerp in de canvas editor en deel het met de community!',
  publicLabel: 'Openbaar',
  privateLabel: 'Privé',
  noPreview: 'Geen voorbeeld',
  downloads: 'downloads',
  download: 'download',
  signInTitle: 'Log in om je sjablonen te bekijken',
  signInSub: 'Je moet ingelogd zijn om je geplaatste sjablonen te zien en te beheren.',
  signIn: 'Inloggen',
  deleteConfirm: 'Weet je zeker dat je dit sjabloon wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
  deleteError: 'Verwijderen van sjabloon mislukt. Probeer het opnieuw.',
  visibilityError: 'Zichtbaarheid bijwerken mislukt. Probeer het opnieuw.',
  makePrivate: 'Privé maken',
  makePublic: 'Openbaar maken',
  edit: 'Bewerken',
  deleteBtn: 'Verwijderen',
};

const contentMap: Record<string, CommunityContent> = { en, es, fr, de, ar, ja, it, ko, vi, th, pt, tr, id, pl, nl };

export function getContent(locale: string) { return selectContent(contentMap, locale); }
