import { selectContent } from './types';

export interface TermsContent {
  hero: { badge: string; title: string; titleHighlight: string; subtitle: string };
  highlights: { title: string; text: string }[];
  sections: {
    heading: string;
    intro?: string;
    subsections?: { subheading: string; items: string[] }[];
    items?: string[];
  }[];
  contactText: string;
  cta: { title: string; titleHighlight: string; subtitle: string; primaryBtn: string; secondaryBtn: string };
  lastUpdated: string;
}

const en: TermsContent = {
  hero: {
    badge: 'Terms & Conditions',
    title: 'Simple, transparent',
    titleHighlight: 'terms of service',
    subtitle: 'We believe in transparency and simplicity. Our terms are written in plain language so you know exactly what to expect when using Best AI Resume.',
  },
  highlights: [
    { title: 'No Hidden Fees', text: 'What you see is what you pay. Our pricing is straightforward with no surprise charges or hidden costs.' },
    { title: 'Your Data, Your Control', text: 'We only store your email and name for login purposes. Your resume content stays in your browser\u2014never on our servers.' },
    { title: '7-Day Free Trial', text: 'Try all premium features free for 7 days. No charge until trial ends, cancel anytime with no fees.' },
  ],
  sections: [
    {
      heading: 'Service Overview',
      intro: 'Best AI Resume is an online resume builder that helps you create professional resumes using AI-powered tools. By using our service, you agree to these terms.',
      items: ['Create unlimited resumes with our builder tools', 'Access AI-powered content suggestions and improvements', 'Download your resumes in PDF format', 'Choose from professionally designed templates'],
    },
    {
      heading: 'Account & Data Transparency',
      subsections: [
        { subheading: 'What We Store on Our Servers', items: ['**Email address** \u2014 For account login and important notifications', '**Name** \u2014 To personalize your experience', '**Password (encrypted)** \u2014 Securely hashed for authentication', '**Subscription status** \u2014 To manage your plan benefits'] },
        { subheading: 'What We Do NOT Store', items: ['Your resume content (stored locally in your browser)', 'Your work history or employment details', 'Your education or skills information', 'Your personal address or phone number'] },
      ],
      intro: "We are committed to minimal data collection. We only store what\u2019s absolutely necessary for your account to function:",
    },
    {
      heading: 'Subscription & Payments',
      subsections: [
        { subheading: 'Monthly Subscription', items: ['**Billing cycle** \u2014 You are billed monthly on the same date you subscribed', '**Auto-renewal** \u2014 Subscriptions automatically renew unless cancelled', '**Price transparency** \u2014 The price shown at checkout is the price you pay (plus applicable taxes)'] },
        { subheading: 'Cancellation Policy', items: ['Cancel anytime from your account dashboard\u2014no questions asked', 'Access continues until the end of your current billing period', 'No cancellation fees or penalties', 'Your local data remains intact after cancellation'] },
        { subheading: '7-Day Free Trial', items: ['**Full access** \u2014 Try all premium features free for 7 days', "**No charge during trial** \u2014 You won\u2019t be billed until your trial ends", '**Cancel anytime** \u2014 Cancel before trial ends and pay nothing', "**Reminder email** \u2014 We\u2019ll notify you before your trial ends"] },
      ],
    },
    {
      heading: 'Free Access & Paid Plans',
      intro: 'Before subscribing, you can:',
      items: ['Browse and preview all templates', 'Create and save resumes to your account', 'View resume examples and career tips'],
    },
    {
      heading: 'User Responsibilities',
      intro: 'By using our service, you agree to:',
      items: ['Provide accurate information in your account registration', 'Keep your account credentials secure', 'Use the service for lawful purposes only', 'Not attempt to circumvent or abuse the service'],
    },
    {
      heading: 'Intellectual Property',
      items: ['**Your content** \u2014 You retain full ownership of all content you create using our service', '**Our templates** \u2014 Template designs are licensed to you for personal and professional use', '**AI-generated content** \u2014 Text generated by our AI becomes yours to use freely'],
    },
    {
      heading: 'Service Availability',
      intro: 'We strive to maintain high service availability, but:',
      items: ['Occasional maintenance may cause temporary interruptions', 'We will notify users of planned maintenance when possible', 'Your local data remains accessible even when our servers are down'],
    },
    {
      heading: 'Changes to Terms',
      intro: 'We may update these terms from time to time. We will notify you of significant changes via email or through our service. Continued use of the service after changes constitutes acceptance of the new terms.',
    },
    {
      heading: 'Contact Us',
    },
  ],
  contactText: 'Questions about these terms? Contact us at',
  cta: {
    title: 'Ready to build your',
    titleHighlight: 'professional resume?',
    subtitle: 'Simple pricing, transparent terms, and your data stays yours.',
    primaryBtn: 'Get Started Free',
    secondaryBtn: 'View Pricing',
  },
  lastUpdated: 'Last updated: January 2026',
};

const es: TermsContent = {
  hero: {
    badge: 'T\u00e9rminos y Condiciones',
    title: 'T\u00e9rminos de servicio',
    titleHighlight: 'simples y transparentes',
    subtitle: 'Creemos en la transparencia y la simplicidad. Nuestros t\u00e9rminos est\u00e1n escritos en un lenguaje sencillo para que sepas exactamente qu\u00e9 esperar al usar Best AI Resume.',
  },
  highlights: [
    { title: 'Sin Costos Ocultos', text: 'Lo que ves es lo que pagas. Nuestros precios son directos, sin cargos sorpresa ni costos ocultos.' },
    { title: 'Tus Datos, Tu Control', text: 'Solo almacenamos tu correo electr\u00f3nico y nombre para iniciar sesi\u00f3n. El contenido de tu curr\u00edculum permanece en tu navegador, nunca en nuestros servidores.' },
    { title: 'Prueba Gratuita de 7 D\u00edas', text: 'Prueba todas las funciones premium gratis durante 7 d\u00edas. Sin cargos hasta que termine la prueba, cancela en cualquier momento sin comisiones.' },
  ],
  sections: [
    {
      heading: 'Descripci\u00f3n del Servicio',
      intro: 'Best AI Resume es un creador de curr\u00edculums en l\u00ednea que te ayuda a crear curr\u00edculums profesionales usando herramientas impulsadas por IA. Al usar nuestro servicio, aceptas estos t\u00e9rminos.',
      items: ['Crea curr\u00edculums ilimitados con nuestras herramientas de creaci\u00f3n', 'Accede a sugerencias y mejoras de contenido impulsadas por IA', 'Descarga tus curr\u00edculums en formato PDF', 'Elige entre plantillas dise\u00f1adas profesionalmente'],
    },
    {
      heading: 'Cuenta y Transparencia de Datos',
      subsections: [
        { subheading: 'Lo Que Almacenamos en Nuestros Servidores', items: ['**Direcci\u00f3n de correo electr\u00f3nico** \u2014 Para iniciar sesi\u00f3n y notificaciones importantes', '**Nombre** \u2014 Para personalizar tu experiencia', '**Contrase\u00f1a (encriptada)** \u2014 Hasheada de forma segura para la autenticaci\u00f3n', '**Estado de suscripci\u00f3n** \u2014 Para gestionar los beneficios de tu plan'] },
        { subheading: 'Lo Que NO Almacenamos', items: ['El contenido de tu curr\u00edculum (almacenado localmente en tu navegador)', 'Tu historial laboral o detalles de empleo', 'Tu informaci\u00f3n educativa o de habilidades', 'Tu direcci\u00f3n personal o n\u00famero de tel\u00e9fono'] },
      ],
      intro: 'Estamos comprometidos con la recopilaci\u00f3n m\u00ednima de datos. Solo almacenamos lo absolutamente necesario para que tu cuenta funcione:',
    },
    {
      heading: 'Suscripci\u00f3n y Pagos',
      subsections: [
        { subheading: 'Suscripci\u00f3n Mensual', items: ['**Ciclo de facturaci\u00f3n** \u2014 Se te cobra mensualmente en la misma fecha en que te suscribiste', '**Renovaci\u00f3n autom\u00e1tica** \u2014 Las suscripciones se renuevan autom\u00e1ticamente a menos que se cancelen', '**Transparencia de precios** \u2014 El precio mostrado al pagar es el precio que pagas (m\u00e1s impuestos aplicables)'] },
        { subheading: 'Pol\u00edtica de Cancelaci\u00f3n', items: ['Cancela en cualquier momento desde el panel de tu cuenta, sin preguntas', 'El acceso contin\u00faa hasta el final de tu per\u00edodo de facturaci\u00f3n actual', 'Sin comisiones ni penalizaciones por cancelaci\u00f3n', 'Tus datos locales permanecen intactos despu\u00e9s de la cancelaci\u00f3n'] },
        { subheading: 'Prueba Gratuita de 7 D\u00edas', items: ['**Acceso completo** \u2014 Prueba todas las funciones premium gratis durante 7 d\u00edas', '**Sin cargo durante la prueba** \u2014 No se te cobrar\u00e1 hasta que termine tu prueba', '**Cancela en cualquier momento** \u2014 Cancela antes de que termine la prueba y no pagues nada', '**Correo de recordatorio** \u2014 Te notificaremos antes de que termine tu prueba'] },
      ],
    },
    {
      heading: 'Acceso Gratuito y Planes de Pago',
      intro: 'Antes de suscribirte, puedes:',
      items: ['Explorar y previsualizar todas las plantillas', 'Crear y guardar curr\u00edculums en tu cuenta', 'Ver ejemplos de curr\u00edculum y consejos profesionales'],
    },
    {
      heading: 'Responsabilidades del Usuario',
      intro: 'Al usar nuestro servicio, aceptas:',
      items: ['Proporcionar informaci\u00f3n precisa en el registro de tu cuenta', 'Mantener seguras tus credenciales de cuenta', 'Usar el servicio solo para fines l\u00edcitos', 'No intentar eludir o abusar del servicio'],
    },
    {
      heading: 'Propiedad Intelectual',
      items: ['**Tu contenido** \u2014 Conservas la propiedad total de todo el contenido que crees usando nuestro servicio', '**Nuestras plantillas** \u2014 Los dise\u00f1os de plantillas te son licenciados para uso personal y profesional', '**Contenido generado por IA** \u2014 El texto generado por nuestra IA es tuyo para usarlo libremente'],
    },
    {
      heading: 'Disponibilidad del Servicio',
      intro: 'Nos esforzamos por mantener una alta disponibilidad del servicio, pero:',
      items: ['El mantenimiento ocasional puede causar interrupciones temporales', 'Notificaremos a los usuarios del mantenimiento planificado cuando sea posible', 'Tus datos locales permanecen accesibles incluso cuando nuestros servidores est\u00e1n inactivos'],
    },
    {
      heading: 'Cambios en los T\u00e9rminos',
      intro: 'Podemos actualizar estos términos de vez en cuando. Te notificaremos de cambios significativos por correo electrónico o a través de nuestro servicio. El uso continuado del servicio después de los cambios constituye la aceptación de los nuevos términos.',
    },
    {
      heading: 'Cont\u00e1ctanos',
    },
  ],
  contactText: '\u00bfPreguntas sobre estos t\u00e9rminos? Cont\u00e1ctanos en',
  cta: {
    title: '\u00bfListo para crear tu',
    titleHighlight: 'curr\u00edculum profesional?',
    subtitle: 'Precios simples, t\u00e9rminos transparentes y tus datos siguen siendo tuyos.',
    primaryBtn: 'Comenzar Gratis',
    secondaryBtn: 'Ver Precios',
  },
  lastUpdated: '\u00daltima actualizaci\u00f3n: enero 2026',
};

const contentMap: Record<string, TermsContent> = { en, es };

export function getContent(locale: string) { return selectContent(contentMap, locale); }
