import { selectContent } from './types';

export interface TermsContent {
  hero: { badge: string; title: string; titleHighlight: string; subtitle: string };
  highlights: { title: string; text: string }[];
  sections: {
    heading: string;
    intro?: string;
    subsections?: { subheading: string; items: string[] }[];
    items?: string[];
  }[];
  contactText: string;
  cta: { title: string; titleHighlight: string; subtitle: string; primaryBtn: string; secondaryBtn: string };
  lastUpdated: string;
}

const en: TermsContent = {
  hero: {
    badge: 'Terms & Conditions',
    title: 'Simple, transparent',
    titleHighlight: 'terms of service',
    subtitle: 'We believe in transparency and simplicity. Our terms are written in plain language so you know exactly what to expect when using Best AI Resume.',
  },
  highlights: [
    { title: 'No Hidden Fees', text: 'What you see is what you pay. Our pricing is straightforward with no surprise charges or hidden costs.' },
    { title: 'Your Data, Your Control', text: 'We only store your email and name for login purposes. Your resume content stays in your browser\u2014never on our servers.' },
    { title: '7-Day Free Trial', text: 'Try all premium features free for 7 days. No charge until trial ends, cancel anytime with no fees.' },
  ],
  sections: [
    {
      heading: 'Service Overview',
      intro: 'Best AI Resume is an online resume builder that helps you create professional resumes using AI-powered tools. By using our service, you agree to these terms.',
      items: ['Create unlimited resumes with our builder tools', 'Access AI-powered content suggestions and improvements', 'Download your resumes in PDF format', 'Choose from professionally designed templates'],
    },
    {
      heading: 'Account & Data Transparency',
      subsections: [
        { subheading: 'What We Store on Our Servers', items: ['**Email address** \u2014 For account login and important notifications', '**Name** \u2014 To personalize your experience', '**Password (encrypted)** \u2014 Securely hashed for authentication', '**Subscription status** \u2014 To manage your plan benefits'] },
        { subheading: 'What We Do NOT Store', items: ['Your resume content (stored locally in your browser)', 'Your work history or employment details', 'Your education or skills information', 'Your personal address or phone number'] },
      ],
      intro: "We are committed to minimal data collection. We only store what\u2019s absolutely necessary for your account to function:",
    },
    {
      heading: 'Subscription & Payments',
      subsections: [
        { subheading: 'Monthly Subscription', items: ['**Billing cycle** \u2014 You are billed monthly on the same date you subscribed', '**Auto-renewal** \u2014 Subscriptions automatically renew unless cancelled', '**Price transparency** \u2014 The price shown at checkout is the price you pay (plus applicable taxes)'] },
        { subheading: 'Cancellation Policy', items: ['Cancel anytime from your account dashboard\u2014no questions asked', 'Access continues until the end of your current billing period', 'No cancellation fees or penalties', 'Your local data remains intact after cancellation'] },
        { subheading: '7-Day Free Trial', items: ['**Full access** \u2014 Try all premium features free for 7 days', "**No charge during trial** \u2014 You won\u2019t be billed until your trial ends", '**Cancel anytime** \u2014 Cancel before trial ends and pay nothing', "**Reminder email** \u2014 We\u2019ll notify you before your trial ends"] },
      ],
    },
    {
      heading: 'Free Access & Paid Plans',
      intro: 'Before subscribing, you can:',
      items: ['Browse and preview all templates', 'Create and save resumes to your account', 'View resume examples and career tips'],
    },
    {
      heading: 'User Responsibilities',
      intro: 'By using our service, you agree to:',
      items: ['Provide accurate information in your account registration', 'Keep your account credentials secure', 'Use the service for lawful purposes only', 'Not attempt to circumvent or abuse the service'],
    },
    {
      heading: 'Intellectual Property',
      items: ['**Your content** \u2014 You retain full ownership of all content you create using our service', '**Our templates** \u2014 Template designs are licensed to you for personal and professional use', '**AI-generated content** \u2014 Text generated by our AI becomes yours to use freely'],
    },
    {
      heading: 'Service Availability',
      intro: 'We strive to maintain high service availability, but:',
      items: ['Occasional maintenance may cause temporary interruptions', 'We will notify users of planned maintenance when possible', 'Your local data remains accessible even when our servers are down'],
    },
    {
      heading: 'Changes to Terms',
      intro: 'We may update these terms from time to time. We will notify you of significant changes via email or through our service. Continued use of the service after changes constitutes acceptance of the new terms.',
    },
    {
      heading: 'Contact Us',
    },
  ],
  contactText: 'Questions about these terms? Contact us at',
  cta: {
    title: 'Ready to build your',
    titleHighlight: 'professional resume?',
    subtitle: 'Simple pricing, transparent terms, and your data stays yours.',
    primaryBtn: 'Get Started Free',
    secondaryBtn: 'View Pricing',
  },
  lastUpdated: 'Last updated: January 2026',
};

const es: TermsContent = {
  hero: {
    badge: 'T\u00e9rminos y Condiciones',
    title: 'T\u00e9rminos de servicio',
    titleHighlight: 'simples y transparentes',
    subtitle: 'Creemos en la transparencia y la simplicidad. Nuestros t\u00e9rminos est\u00e1n escritos en un lenguaje sencillo para que sepas exactamente qu\u00e9 esperar al usar Best AI Resume.',
  },
  highlights: [
    { title: 'Sin Costos Ocultos', text: 'Lo que ves es lo que pagas. Nuestros precios son directos, sin cargos sorpresa ni costos ocultos.' },
    { title: 'Tus Datos, Tu Control', text: 'Solo almacenamos tu correo electr\u00f3nico y nombre para iniciar sesi\u00f3n. El contenido de tu curr\u00edculum permanece en tu navegador, nunca en nuestros servidores.' },
    { title: 'Prueba Gratuita de 7 D\u00edas', text: 'Prueba todas las funciones premium gratis durante 7 d\u00edas. Sin cargos hasta que termine la prueba, cancela en cualquier momento sin comisiones.' },
  ],
  sections: [
    {
      heading: 'Descripci\u00f3n del Servicio',
      intro: 'Best AI Resume es un creador de curr\u00edculums en l\u00ednea que te ayuda a crear curr\u00edculums profesionales usando herramientas impulsadas por IA. Al usar nuestro servicio, aceptas estos t\u00e9rminos.',
      items: ['Crea curr\u00edculums ilimitados con nuestras herramientas de creaci\u00f3n', 'Accede a sugerencias y mejoras de contenido impulsadas por IA', 'Descarga tus curr\u00edculums en formato PDF', 'Elige entre plantillas dise\u00f1adas profesionalmente'],
    },
    {
      heading: 'Cuenta y Transparencia de Datos',
      subsections: [
        { subheading: 'Lo Que Almacenamos en Nuestros Servidores', items: ['**Direcci\u00f3n de correo electr\u00f3nico** \u2014 Para iniciar sesi\u00f3n y notificaciones importantes', '**Nombre** \u2014 Para personalizar tu experiencia', '**Contrase\u00f1a (encriptada)** \u2014 Hasheada de forma segura para la autenticaci\u00f3n', '**Estado de suscripci\u00f3n** \u2014 Para gestionar los beneficios de tu plan'] },
        { subheading: 'Lo Que NO Almacenamos', items: ['El contenido de tu curr\u00edculum (almacenado localmente en tu navegador)', 'Tu historial laboral o detalles de empleo', 'Tu informaci\u00f3n educativa o de habilidades', 'Tu direcci\u00f3n personal o n\u00famero de tel\u00e9fono'] },
      ],
      intro: 'Estamos comprometidos con la recopilaci\u00f3n m\u00ednima de datos. Solo almacenamos lo absolutamente necesario para que tu cuenta funcione:',
    },
    {
      heading: 'Suscripci\u00f3n y Pagos',
      subsections: [
        { subheading: 'Suscripci\u00f3n Mensual', items: ['**Ciclo de facturaci\u00f3n** \u2014 Se te cobra mensualmente en la misma fecha en que te suscribiste', '**Renovaci\u00f3n autom\u00e1tica** \u2014 Las suscripciones se renuevan autom\u00e1ticamente a menos que se cancelen', '**Transparencia de precios** \u2014 El precio mostrado al pagar es el precio que pagas (m\u00e1s impuestos aplicables)'] },
        { subheading: 'Pol\u00edtica de Cancelaci\u00f3n', items: ['Cancela en cualquier momento desde el panel de tu cuenta, sin preguntas', 'El acceso contin\u00faa hasta el final de tu per\u00edodo de facturaci\u00f3n actual', 'Sin comisiones ni penalizaciones por cancelaci\u00f3n', 'Tus datos locales permanecen intactos despu\u00e9s de la cancelaci\u00f3n'] },
        { subheading: 'Prueba Gratuita de 7 D\u00edas', items: ['**Acceso completo** \u2014 Prueba todas las funciones premium gratis durante 7 d\u00edas', '**Sin cargo durante la prueba** \u2014 No se te cobrar\u00e1 hasta que termine tu prueba', '**Cancela en cualquier momento** \u2014 Cancela antes de que termine la prueba y no pagues nada', '**Correo de recordatorio** \u2014 Te notificaremos antes de que termine tu prueba'] },
      ],
    },
    {
      heading: 'Acceso Gratuito y Planes de Pago',
      intro: 'Antes de suscribirte, puedes:',
      items: ['Explorar y previsualizar todas las plantillas', 'Crear y guardar curr\u00edculums en tu cuenta', 'Ver ejemplos de curr\u00edculum y consejos profesionales'],
    },
    {
      heading: 'Responsabilidades del Usuario',
      intro: 'Al usar nuestro servicio, aceptas:',
      items: ['Proporcionar informaci\u00f3n precisa en el registro de tu cuenta', 'Mantener seguras tus credenciales de cuenta', 'Usar el servicio solo para fines l\u00edcitos', 'No intentar eludir o abusar del servicio'],
    },
    {
      heading: 'Propiedad Intelectual',
      items: ['**Tu contenido** \u2014 Conservas la propiedad total de todo el contenido que crees usando nuestro servicio', '**Nuestras plantillas** \u2014 Los dise\u00f1os de plantillas te son licenciados para uso personal y profesional', '**Contenido generado por IA** \u2014 El texto generado por nuestra IA es tuyo para usarlo libremente'],
    },
    {
      heading: 'Disponibilidad del Servicio',
      intro: 'Nos esforzamos por mantener una alta disponibilidad del servicio, pero:',
      items: ['El mantenimiento ocasional puede causar interrupciones temporales', 'Notificaremos a los usuarios del mantenimiento planificado cuando sea posible', 'Tus datos locales permanecen accesibles incluso cuando nuestros servidores est\u00e1n inactivos'],
    },
    {
      heading: 'Cambios en los T\u00e9rminos',
      intro: 'Podemos actualizar estos términos de vez en cuando. Te notificaremos de cambios significativos por correo electrónico o a través de nuestro servicio. El uso continuado del servicio después de los cambios constituye la aceptación de los nuevos términos.',
    },
    {
      heading: 'Cont\u00e1ctanos',
    },
  ],
  contactText: '\u00bfPreguntas sobre estos t\u00e9rminos? Cont\u00e1ctanos en',
  cta: {
    title: '\u00bfListo para crear tu',
    titleHighlight: 'curr\u00edculum profesional?',
    subtitle: 'Precios simples, t\u00e9rminos transparentes y tus datos siguen siendo tuyos.',
    primaryBtn: 'Comenzar Gratis',
    secondaryBtn: 'Ver Precios',
  },
  lastUpdated: '\u00daltima actualizaci\u00f3n: enero 2026',
};

const fr: TermsContent = {
  hero: {
    badge: 'Conditions Générales',
    title: 'Des conditions de service',
    titleHighlight: 'simples et transparentes',
    subtitle: 'Nous croyons en la transparence et la simplicité. Nos conditions sont rédigées dans un langage clair pour que vous sachiez exactement à quoi vous attendre en utilisant Best AI Resume.',
  },
  highlights: [
    { title: 'Aucun Frais Caché', text: 'Ce que vous voyez est ce que vous payez. Nos tarifs sont clairs, sans frais surprise ni coûts cachés.' },
    { title: 'Vos Données, Votre Contrôle', text: 'Nous ne stockons que votre adresse e-mail et votre nom pour la connexion. Le contenu de votre CV reste dans votre navigateur — jamais sur nos serveurs.' },
    { title: 'Essai Gratuit de 7 Jours', text: 'Essayez toutes les fonctionnalités premium gratuitement pendant 7 jours. Aucun frais jusqu\u2019à la fin de l\u2019essai, annulez à tout moment sans pénalité.' },
  ],
  sections: [
    {
      heading: 'Présentation du Service',
      intro: 'Best AI Resume est un créateur de CV en ligne qui vous aide à concevoir des CV professionnels grâce à des outils alimentés par l\u2019IA. En utilisant notre service, vous acceptez ces conditions.',
      items: ['Créez un nombre illimité de CV avec nos outils de création', 'Accédez à des suggestions et améliorations de contenu générées par l\u2019IA', 'Téléchargez vos CV au format PDF', 'Choisissez parmi des modèles conçus par des professionnels'],
    },
    {
      heading: 'Compte et Transparence des Données',
      subsections: [
        { subheading: 'Ce Que Nous Stockons sur Nos Serveurs', items: ['**Adresse e-mail** — Pour la connexion et les notifications importantes', '**Nom** — Pour personnaliser votre expérience', '**Mot de passe (chiffré)** — Haché de manière sécurisée pour l\u2019authentification', '**Statut d\u2019abonnement** — Pour gérer les avantages de votre forfait'] },
        { subheading: 'Ce Que Nous Ne Stockons PAS', items: ['Le contenu de votre CV (stocké localement dans votre navigateur)', 'Votre historique professionnel ou vos détails d\u2019emploi', 'Vos informations sur votre formation ou vos compétences', 'Votre adresse personnelle ou numéro de téléphone'] },
      ],
      intro: 'Nous nous engageons à collecter un minimum de données. Nous ne stockons que ce qui est absolument nécessaire au fonctionnement de votre compte :',
    },
    {
      heading: 'Abonnement et Paiements',
      subsections: [
        { subheading: 'Abonnement Mensuel', items: ['**Cycle de facturation** — Vous êtes facturé mensuellement à la même date que votre inscription', '**Renouvellement automatique** — Les abonnements se renouvellent automatiquement sauf annulation', '**Transparence des prix** — Le prix affiché lors du paiement est le prix que vous payez (plus taxes applicables)'] },
        { subheading: 'Politique d\u2019Annulation', items: ['Annulez à tout moment depuis votre tableau de bord — sans justification', 'L\u2019accès continue jusqu\u2019à la fin de votre période de facturation en cours', 'Aucun frais ni pénalité d\u2019annulation', 'Vos données locales restent intactes après l\u2019annulation'] },
        { subheading: 'Essai Gratuit de 7 Jours', items: ['**Accès complet** — Essayez toutes les fonctionnalités premium gratuitement pendant 7 jours', '**Aucun frais pendant l\u2019essai** — Vous ne serez pas facturé avant la fin de votre essai', '**Annulez à tout moment** — Annulez avant la fin de l\u2019essai et ne payez rien', '**E-mail de rappel** — Nous vous préviendrons avant la fin de votre essai'] },
      ],
    },
    {
      heading: 'Accès Gratuit et Forfaits Payants',
      intro: 'Avant de vous abonner, vous pouvez :',
      items: ['Parcourir et prévisualiser tous les modèles', 'Créer et enregistrer des CV dans votre compte', 'Consulter des exemples de CV et des conseils de carrière'],
    },
    {
      heading: 'Responsabilités de l\u2019Utilisateur',
      intro: 'En utilisant notre service, vous acceptez de :',
      items: ['Fournir des informations exactes lors de l\u2019inscription de votre compte', 'Garder vos identifiants de compte en sécurité', 'Utiliser le service uniquement à des fins légales', 'Ne pas tenter de contourner ou d\u2019abuser du service'],
    },
    {
      heading: 'Propriété Intellectuelle',
      items: ['**Votre contenu** — Vous conservez l\u2019entière propriété de tout le contenu que vous créez avec notre service', '**Nos modèles** — Les designs de modèles vous sont concédés sous licence pour un usage personnel et professionnel', '**Contenu généré par l\u2019IA** — Le texte généré par notre IA vous appartient et vous pouvez l\u2019utiliser librement'],
    },
    {
      heading: 'Disponibilité du Service',
      intro: 'Nous nous efforçons de maintenir une haute disponibilité du service, mais :',
      items: ['Des maintenances occasionnelles peuvent entraîner des interruptions temporaires', 'Nous informerons les utilisateurs des maintenances planifiées lorsque possible', 'Vos données locales restent accessibles même lorsque nos serveurs sont indisponibles'],
    },
    {
      heading: 'Modifications des Conditions',
      intro: 'Nous pouvons mettre à jour ces conditions de temps à autre. Nous vous informerons des changements importants par e-mail ou via notre service. L\u2019utilisation continue du service après les modifications vaut acceptation des nouvelles conditions.',
    },
    {
      heading: 'Nous Contacter',
    },
  ],
  contactText: 'Des questions sur ces conditions ? Contactez-nous à',
  cta: {
    title: 'Prêt à créer votre',
    titleHighlight: 'CV professionnel ?',
    subtitle: 'Des tarifs simples, des conditions transparentes et vos données restent les vôtres.',
    primaryBtn: 'Commencer Gratuitement',
    secondaryBtn: 'Voir les Tarifs',
  },
  lastUpdated: 'Dernière mise à jour : janvier 2026',
};

const de: TermsContent = {
  hero: {
    badge: 'Allgemeine Geschäftsbedingungen',
    title: 'Einfache, transparente',
    titleHighlight: 'Nutzungsbedingungen',
    subtitle: 'Wir glauben an Transparenz und Einfachheit. Unsere Bedingungen sind in verständlicher Sprache verfasst, damit Sie genau wissen, was Sie bei der Nutzung von Best AI Resume erwartet.',
  },
  highlights: [
    { title: 'Keine Versteckten Gebühren', text: 'Was Sie sehen, ist das, was Sie zahlen. Unsere Preise sind transparent — ohne überraschende Kosten oder versteckte Gebühren.' },
    { title: 'Ihre Daten, Ihre Kontrolle', text: 'Wir speichern nur Ihre E-Mail-Adresse und Ihren Namen für die Anmeldung. Ihr Lebenslauf-Inhalt bleibt in Ihrem Browser — niemals auf unseren Servern.' },
    { title: '7-Tage Kostenlose Testphase', text: 'Testen Sie alle Premium-Funktionen 7 Tage lang kostenlos. Keine Kosten bis zum Ende der Testphase, jederzeit kündbar ohne Gebühren.' },
  ],
  sections: [
    {
      heading: 'Serviceübersicht',
      intro: 'Best AI Resume ist ein Online-Lebenslauf-Editor, der Ihnen hilft, professionelle Lebensläufe mit KI-gestützten Werkzeugen zu erstellen. Durch die Nutzung unseres Services stimmen Sie diesen Bedingungen zu.',
      items: ['Erstellen Sie unbegrenzt viele Lebensläufe mit unseren Erstellungstools', 'Nutzen Sie KI-gestützte Inhaltsvorschläge und Verbesserungen', 'Laden Sie Ihre Lebensläufe im PDF-Format herunter', 'Wählen Sie aus professionell gestalteten Vorlagen'],
    },
    {
      heading: 'Konto und Datentransparenz',
      subsections: [
        { subheading: 'Was Wir auf Unseren Servern Speichern', items: ['**E-Mail-Adresse** — Für die Kontoanmeldung und wichtige Benachrichtigungen', '**Name** — Zur Personalisierung Ihres Erlebnisses', '**Passwort (verschlüsselt)** — Sicher gehasht für die Authentifizierung', '**Abonnementstatus** — Zur Verwaltung Ihrer Planvorteile'] },
        { subheading: 'Was Wir NICHT Speichern', items: ['Ihren Lebenslauf-Inhalt (lokal in Ihrem Browser gespeichert)', 'Ihren beruflichen Werdegang oder Beschäftigungsdetails', 'Ihre Ausbildungs- oder Qualifikationsdaten', 'Ihre persönliche Adresse oder Telefonnummer'] },
      ],
      intro: 'Wir verpflichten uns zur minimalen Datenerfassung. Wir speichern nur das, was für die Funktion Ihres Kontos absolut notwendig ist:',
    },
    {
      heading: 'Abonnement und Zahlungen',
      subsections: [
        { subheading: 'Monatliches Abonnement', items: ['**Abrechnungszyklus** — Sie werden monatlich am selben Datum Ihrer Anmeldung abgerechnet', '**Automatische Verlängerung** — Abonnements verlängern sich automatisch, sofern sie nicht gekündigt werden', '**Preistransparenz** — Der beim Bezahlen angezeigte Preis ist der Preis, den Sie zahlen (zzgl. anfallender Steuern)'] },
        { subheading: 'Kündigungsrichtlinie', items: ['Kündigen Sie jederzeit über Ihr Konto-Dashboard — ohne Rückfragen', 'Der Zugang bleibt bis zum Ende Ihres aktuellen Abrechnungszeitraums bestehen', 'Keine Kündigungsgebühren oder Strafen', 'Ihre lokalen Daten bleiben nach der Kündigung erhalten'] },
        { subheading: '7-Tage Kostenlose Testphase', items: ['**Voller Zugang** — Testen Sie alle Premium-Funktionen 7 Tage lang kostenlos', '**Keine Kosten während der Testphase** — Sie werden erst nach Ablauf der Testphase belastet', '**Jederzeit kündbar** — Kündigen Sie vor Ende der Testphase und zahlen Sie nichts', '**Erinnerungs-E-Mail** — Wir benachrichtigen Sie vor Ablauf Ihrer Testphase'] },
      ],
    },
    {
      heading: 'Kostenloser Zugang und Bezahlpläne',
      intro: 'Vor der Anmeldung können Sie:',
      items: ['Alle Vorlagen durchsuchen und in der Vorschau ansehen', 'Lebensläufe erstellen und in Ihrem Konto speichern', 'Lebenslauf-Beispiele und Karrieretipps ansehen'],
    },
    {
      heading: 'Pflichten des Nutzers',
      intro: 'Durch die Nutzung unseres Services stimmen Sie zu:',
      items: ['Korrekte Angaben bei der Kontoregistrierung zu machen', 'Ihre Zugangsdaten sicher aufzubewahren', 'Den Service nur für rechtmäßige Zwecke zu nutzen', 'Nicht zu versuchen, den Service zu umgehen oder zu missbrauchen'],
    },
    {
      heading: 'Geistiges Eigentum',
      items: ['**Ihre Inhalte** — Sie behalten das vollständige Eigentum an allen Inhalten, die Sie mit unserem Service erstellen', '**Unsere Vorlagen** — Vorlagendesigns werden Ihnen für den persönlichen und beruflichen Gebrauch lizenziert', '**KI-generierte Inhalte** — Von unserer KI generierter Text gehört Ihnen und kann frei verwendet werden'],
    },
    {
      heading: 'Serviceverfügbarkeit',
      intro: 'Wir bemühen uns um eine hohe Verfügbarkeit des Services, jedoch:',
      items: ['Gelegentliche Wartungsarbeiten können zu vorübergehenden Unterbrechungen führen', 'Wir informieren die Nutzer nach Möglichkeit über geplante Wartungsarbeiten', 'Ihre lokalen Daten bleiben auch dann zugänglich, wenn unsere Server nicht erreichbar sind'],
    },
    {
      heading: 'Änderungen der Bedingungen',
      intro: 'Wir können diese Bedingungen von Zeit zu Zeit aktualisieren. Über wesentliche Änderungen informieren wir Sie per E-Mail oder über unseren Service. Die fortgesetzte Nutzung des Services nach Änderungen gilt als Annahme der neuen Bedingungen.',
    },
    {
      heading: 'Kontakt',
    },
  ],
  contactText: 'Fragen zu diesen Bedingungen? Kontaktieren Sie uns unter',
  cta: {
    title: 'Bereit, Ihren',
    titleHighlight: 'professionellen Lebenslauf zu erstellen?',
    subtitle: 'Einfache Preise, transparente Bedingungen und Ihre Daten gehören Ihnen.',
    primaryBtn: 'Kostenlos Starten',
    secondaryBtn: 'Preise Ansehen',
  },
  lastUpdated: 'Letzte Aktualisierung: Januar 2026',
};

const ar: TermsContent = {
  hero: {
    badge: 'الشروط والأحكام',
    title: 'شروط خدمة',
    titleHighlight: 'بسيطة وشفافة',
    subtitle: 'نؤمن بالشفافية والبساطة. شروطنا مكتوبة بلغة واضحة حتى تعرف بالضبط ما يمكنك توقعه عند استخدام Best AI Resume.',
  },
  highlights: [
    { title: 'بدون رسوم مخفية', text: 'ما تراه هو ما تدفعه. أسعارنا واضحة بدون رسوم مفاجئة أو تكاليف مخفية.' },
    { title: 'بياناتك تحت سيطرتك', text: 'نحن نخزّن فقط بريدك الإلكتروني واسمك لتسجيل الدخول. محتوى سيرتك الذاتية يبقى في متصفحك — وليس على خوادمنا أبداً.' },
    { title: 'تجربة مجانية لمدة 7 أيام', text: 'جرّب جميع الميزات المميزة مجاناً لمدة 7 أيام. لا رسوم حتى نهاية الفترة التجريبية، ويمكنك الإلغاء في أي وقت بدون أي رسوم.' },
  ],
  sections: [
    {
      heading: 'نظرة عامة على الخدمة',
      intro: 'Best AI Resume هو منشئ سير ذاتية عبر الإنترنت يساعدك في إنشاء سير ذاتية احترافية باستخدام أدوات مدعومة بالذكاء الاصطناعي. باستخدامك لخدمتنا، فإنك توافق على هذه الشروط.',
      items: ['أنشئ عدداً غير محدود من السير الذاتية باستخدام أدوات البناء لدينا', 'استفد من اقتراحات وتحسينات المحتوى المدعومة بالذكاء الاصطناعي', 'حمّل سيرتك الذاتية بصيغة PDF', 'اختر من بين قوالب مصممة باحترافية'],
    },
    {
      heading: 'الحساب وشفافية البيانات',
      subsections: [
        { subheading: 'ما نخزّنه على خوادمنا', items: ['**البريد الإلكتروني** — لتسجيل الدخول والإشعارات المهمة', '**الاسم** — لتخصيص تجربتك', '**كلمة المرور (مشفّرة)** — مُجزّأة بشكل آمن للمصادقة', '**حالة الاشتراك** — لإدارة مزايا خطتك'] },
        { subheading: 'ما لا نخزّنه', items: ['محتوى سيرتك الذاتية (يُخزّن محلياً في متصفحك)', 'تاريخك المهني أو تفاصيل التوظيف', 'معلومات تعليمك أو مهاراتك', 'عنوانك الشخصي أو رقم هاتفك'] },
      ],
      intro: 'نحن ملتزمون بجمع الحد الأدنى من البيانات. نحن نخزّن فقط ما هو ضروري لعمل حسابك:',
    },
    {
      heading: 'الاشتراك والمدفوعات',
      subsections: [
        { subheading: 'الاشتراك الشهري', items: ['**دورة الفوترة** — تتم محاسبتك شهرياً في نفس تاريخ اشتراكك', '**التجديد التلقائي** — تتجدد الاشتراكات تلقائياً ما لم يتم إلغاؤها', '**شفافية الأسعار** — السعر المعروض عند الدفع هو السعر الذي تدفعه (بالإضافة إلى الضرائب المطبقة)'] },
        { subheading: 'سياسة الإلغاء', items: ['ألغِ في أي وقت من لوحة تحكم حسابك — بدون أي أسئلة', 'يستمر الوصول حتى نهاية فترة الفوترة الحالية', 'لا رسوم إلغاء أو غرامات', 'تبقى بياناتك المحلية سليمة بعد الإلغاء'] },
        { subheading: 'تجربة مجانية لمدة 7 أيام', items: ['**وصول كامل** — جرّب جميع الميزات المميزة مجاناً لمدة 7 أيام', '**لا رسوم خلال الفترة التجريبية** — لن تتم محاسبتك حتى نهاية الفترة التجريبية', '**ألغِ في أي وقت** — ألغِ قبل نهاية الفترة التجريبية ولن تدفع شيئاً', '**بريد تذكيري** — سنُخطرك قبل انتهاء فترتك التجريبية'] },
      ],
    },
    {
      heading: 'الوصول المجاني والخطط المدفوعة',
      intro: 'قبل الاشتراك، يمكنك:',
      items: ['تصفح ومعاينة جميع القوالب', 'إنشاء وحفظ السير الذاتية في حسابك', 'عرض أمثلة السير الذاتية ونصائح مهنية'],
    },
    {
      heading: 'مسؤوليات المستخدم',
      intro: 'باستخدامك لخدمتنا، فإنك توافق على:',
      items: ['تقديم معلومات دقيقة عند تسجيل حسابك', 'الحفاظ على أمان بيانات تسجيل الدخول الخاصة بك', 'استخدام الخدمة لأغراض قانونية فقط', 'عدم محاولة التحايل على الخدمة أو إساءة استخدامها'],
    },
    {
      heading: 'الملكية الفكرية',
      items: ['**محتواك** — تحتفظ بالملكية الكاملة لجميع المحتوى الذي تنشئه باستخدام خدمتنا', '**قوالبنا** — تصاميم القوالب مرخّصة لك للاستخدام الشخصي والمهني', '**المحتوى المُنشأ بالذكاء الاصطناعي** — النص الذي ينشئه الذكاء الاصطناعي لدينا يصبح ملكاً لك ويمكنك استخدامه بحرية'],
    },
    {
      heading: 'توفر الخدمة',
      intro: 'نسعى جاهدين للحفاظ على توفر عالٍ للخدمة، ولكن:',
      items: ['قد تتسبب الصيانة الدورية في انقطاعات مؤقتة', 'سنُخطر المستخدمين بالصيانة المجدولة عندما يكون ذلك ممكناً', 'تبقى بياناتك المحلية متاحة حتى عندما تكون خوادمنا معطّلة'],
    },
    {
      heading: 'تعديلات على الشروط',
      intro: 'قد نقوم بتحديث هذه الشروط من حين لآخر. سنُخطرك بالتغييرات المهمة عبر البريد الإلكتروني أو من خلال خدمتنا. يُعتبر استمرارك في استخدام الخدمة بعد التغييرات قبولاً للشروط الجديدة.',
    },
    {
      heading: 'اتصل بنا',
    },
  ],
  contactText: 'هل لديك أسئلة حول هذه الشروط؟ تواصل معنا على',
  cta: {
    title: 'هل أنت مستعد لإنشاء',
    titleHighlight: 'سيرتك الذاتية الاحترافية؟',
    subtitle: 'أسعار بسيطة، شروط شفافة، وبياناتك تبقى ملكاً لك.',
    primaryBtn: 'ابدأ مجاناً',
    secondaryBtn: 'عرض الأسعار',
  },
  lastUpdated: 'آخر تحديث: يناير 2026',
};

// ── Japanese ──────────────────────────────────────────────────────────

const ja: TermsContent = {
  hero: {
    badge: '利用規約',
    title: 'シンプルで透明な',
    titleHighlight: '利用規約',
    subtitle: '私たちは透明性とシンプルさを大切にしています。Best AI Resumeをご利用いただく際に何を期待できるか、分かりやすい言葉で規約を記載しています。',
  },
  highlights: [
    { title: '隠れた料金なし', text: '表示価格がお支払い金額です。サプライズ課金や隠れたコストのない、明確な料金体系です。' },
    { title: 'あなたのデータはあなたのもの', text: 'ログイン用のメールアドレスと氏名のみを保存します。履歴書の内容はお客様のブラウザに保存され、当社のサーバーには保存されません。' },
    { title: '7日間無料トライアル', text: 'すべてのプレミアム機能を7日間無料でお試しいただけます。トライアル終了まで課金なし、いつでも手数料なしで解約可能。' },
  ],
  sections: [
    {
      heading: 'サービス概要',
      intro: 'Best AI Resumeは、AI搭載ツールを使用してプロフェッショナルな履歴書の作成を支援するオンライン履歴書作成ツールです。本サービスをご利用いただくことで、以下の規約に同意したものとみなされます。',
      items: ['当ツールで無制限の履歴書を作成', 'AI搭載のコンテンツ提案・改善機能を利用', '履歴書をPDF形式でダウンロード', 'プロがデザインしたテンプレートから選択'],
    },
    {
      heading: 'アカウントとデータの透明性',
      subsections: [
        { subheading: 'サーバーに保存する情報', items: ['**メールアドレス** — アカウントログインと重要な通知のため', '**氏名** — 体験のパーソナライズのため', '**パスワード（暗号化）** — 認証のために安全にハッシュ化', '**サブスクリプション状況** — プラン特典の管理のため'] },
        { subheading: '保存しない情報', items: ['履歴書の内容（ブラウザにローカル保存）', '職歴や雇用の詳細', '学歴やスキル情報', '個人住所や電話番号'] },
      ],
      intro: '最小限のデータ収集に取り組んでいます。アカウント機能に必要不可欠なもののみを保存します：',
    },
    {
      heading: 'サブスクリプションと支払い',
      subsections: [
        { subheading: '月額サブスクリプション', items: ['**請求サイクル** — 登録日と同じ日に毎月請求', '**自動更新** — 解約しない限り自動的に更新', '**価格の透明性** — チェックアウト時の表示価格がお支払い金額（税別）'] },
        { subheading: '解約ポリシー', items: ['アカウントダッシュボードからいつでも解約可能——質問なし', '現在の請求期間の終了までアクセス継続', '解約手数料やペナルティなし', '解約後もローカルデータはそのまま保持'] },
        { subheading: '7日間無料トライアル', items: ['**フルアクセス** — すべてのプレミアム機能を7日間無料で試用', '**トライアル中は課金なし** — トライアル終了まで請求されません', '**いつでも解約可能** — トライアル終了前に解約すれば料金ゼロ', '**リマインダーメール** — トライアル終了前にお知らせします'] },
      ],
    },
    {
      heading: '無料アクセスと有料プラン',
      intro: 'サブスクリプション登録前にできること：',
      items: ['すべてのテンプレートの閲覧とプレビュー', '履歴書の作成とアカウントへの保存', '履歴書サンプルとキャリアアドバイスの閲覧'],
    },
    {
      heading: 'ユーザーの責任',
      intro: '本サービスをご利用いただくことで、以下に同意したものとみなされます：',
      items: ['アカウント登録時に正確な情報を提供すること', 'アカウント認証情報を安全に管理すること', '合法的な目的でのみサービスを利用すること', 'サービスの回避や悪用を試みないこと'],
    },
    {
      heading: '知的財産権',
      items: ['**お客様のコンテンツ** — 本サービスを使用して作成したすべてのコンテンツの完全な所有権はお客様に帰属します', '**当社のテンプレート** — テンプレートデザインは個人的および職業的使用のためにライセンスされます', '**AI生成コンテンツ** — 当社のAIが生成したテキストはお客様のものとして自由にご利用いただけます'],
    },
    {
      heading: 'サービスの可用性',
      intro: 'サービスの高い可用性の維持に努めていますが：',
      items: ['定期メンテナンスにより一時的な中断が発生する場合があります', '計画的なメンテナンスは可能な限り事前にお知らせします', 'サーバーがダウンしている場合でもローカルデータにはアクセス可能です'],
    },
    {
      heading: '規約の変更',
      intro: '本規約は随時更新される場合があります。重要な変更については、メールまたはサービスを通じてお知らせします。変更後のサービス利用継続は、新しい規約への同意とみなされます。',
    },
    {
      heading: 'お問い合わせ',
    },
  ],
  contactText: 'これらの規約についてご質問がありますか？お問い合わせ先：',
  cta: {
    title: 'プロフェッショナルな',
    titleHighlight: '履歴書を作成しませんか？',
    subtitle: 'シンプルな料金、透明な規約、データはあなたのもの。',
    primaryBtn: '無料で始める',
    secondaryBtn: '料金を見る',
  },
  lastUpdated: '最終更新：2026年1月',
};

// ── Italian ──────────────────────────────────────────────────────────

const it: TermsContent = {
  hero: {
    badge: 'Termini e Condizioni',
    title: 'Condizioni di servizio',
    titleHighlight: 'semplici e trasparenti',
    subtitle: 'Crediamo nella trasparenza e nella semplicit\u00e0. I nostri termini sono scritti in un linguaggio chiaro affinch\u00e9 tu sappia esattamente cosa aspettarti utilizzando Best AI Resume.',
  },
  highlights: [
    { title: 'Nessun Costo Nascosto', text: 'Quello che vedi \u00e8 quello che paghi. I nostri prezzi sono chiari, senza addebiti a sorpresa n\u00e9 costi nascosti.' },
    { title: 'I Tuoi Dati, il Tuo Controllo', text: 'Conserviamo solo la tua e-mail e il tuo nome per il login. I contenuti del tuo curriculum vitae restano nel tuo browser\u2014mai sui nostri server.' },
    { title: 'Prova Gratuita di 7 Giorni', text: 'Prova tutte le funzionalit\u00e0 premium gratis per 7 giorni. Nessun addebito fino al termine della prova, cancella in qualsiasi momento senza costi aggiuntivi.' },
  ],
  sections: [
    {
      heading: 'Panoramica del Servizio',
      intro: 'Best AI Resume \u00e8 un builder di curriculum vitae online che ti aiuta a creare CV professionali con strumenti basati sull\u2019intelligenza artificiale. Utilizzando il nostro servizio, accetti i presenti termini.',
      items: ['Crea un numero illimitato di curriculum vitae con i nostri strumenti', 'Accedi a suggerimenti e miglioramenti dei contenuti generati dall\u2019AI', 'Scarica i tuoi CV in formato PDF', 'Scegli tra modelli progettati da professionisti'],
    },
    {
      heading: 'Account e Trasparenza dei Dati',
      subsections: [
        { subheading: 'Cosa Conserviamo sui Nostri Server', items: ['**Indirizzo e-mail** \u2014 Per il login e le notifiche importanti', '**Nome** \u2014 Per personalizzare la tua esperienza', '**Password (crittografata)** \u2014 Salvata in forma di hash sicuro per l\u2019autenticazione', '**Stato dell\u2019abbonamento** \u2014 Per gestire i vantaggi del tuo piano'] },
        { subheading: 'Cosa NON Conserviamo', items: ['I contenuti del tuo curriculum vitae (salvati localmente nel browser)', 'La tua storia lavorativa o i dettagli sull\u2019impiego', 'Le tue informazioni su istruzione e competenze', 'Il tuo indirizzo personale o numero di telefono'] },
      ],
      intro: 'Ci impegniamo a raccogliere il minimo indispensabile di dati. Conserviamo solo ci\u00f2 che \u00e8 strettamente necessario al funzionamento del tuo account:',
    },
    {
      heading: 'Abbonamento e Pagamenti',
      subsections: [
        { subheading: 'Abbonamento Mensile', items: ['**Ciclo di fatturazione** \u2014 La fatturazione avviene mensilmente nella stessa data della sottoscrizione', '**Rinnovo automatico** \u2014 Gli abbonamenti si rinnovano automaticamente salvo disdetta', '**Trasparenza dei prezzi** \u2014 Il prezzo mostrato al momento del pagamento \u00e8 il prezzo che paghi (oltre le imposte applicabili)'] },
        { subheading: 'Politica di Cancellazione', items: ['Cancella in qualsiasi momento dalla dashboard del tuo account\u2014senza bisogno di giustificazioni', 'L\u2019accesso prosegue fino alla fine del periodo di fatturazione in corso', 'Nessuna penale o costo di cancellazione', 'I tuoi dati locali restano intatti dopo la cancellazione'] },
        { subheading: 'Prova Gratuita di 7 Giorni', items: ['**Accesso completo** \u2014 Prova tutte le funzionalit\u00e0 premium gratis per 7 giorni', '**Nessun addebito durante la prova** \u2014 Non verrai addebitato fino al termine del periodo di prova', '**Cancella in qualsiasi momento** \u2014 Cancella prima della fine della prova e non pagherai nulla', '**E-mail di promemoria** \u2014 Ti avviseremo prima della scadenza del periodo di prova'] },
      ],
    },
    {
      heading: 'Accesso Gratuito e Piani a Pagamento',
      intro: 'Prima di abbonarti, puoi:',
      items: ['Sfogliare e visualizzare in anteprima tutti i modelli', 'Creare e salvare curriculum vitae nel tuo account', 'Consultare esempi di CV e consigli di carriera'],
    },
    {
      heading: 'Responsabilit\u00e0 dell\u2019Utente',
      intro: 'Utilizzando il nostro servizio, accetti di:',
      items: ['Fornire informazioni accurate durante la registrazione dell\u2019account', 'Mantenere sicure le tue credenziali di accesso', 'Utilizzare il servizio esclusivamente per scopi leciti', 'Non tentare di eludere o abusare del servizio'],
    },
    {
      heading: 'Propriet\u00e0 Intellettuale',
      items: ['**I tuoi contenuti** \u2014 Mantieni la piena titolarit\u00e0 di tutti i contenuti che crei utilizzando il nostro servizio', '**I nostri modelli** \u2014 I design dei modelli sono concessi in licenza per uso personale e professionale', '**Contenuti generati dall\u2019AI** \u2014 Il testo generato dalla nostra intelligenza artificiale diventa tuo e puoi utilizzarlo liberamente'],
    },
    {
      heading: 'Disponibilit\u00e0 del Servizio',
      intro: 'Ci impegniamo a garantire un\u2019elevata disponibilit\u00e0 del servizio, tuttavia:',
      items: ['Interventi di manutenzione occasionali possono causare interruzioni temporanee', 'Informeremo gli utenti della manutenzione programmata quando possibile', 'I tuoi dati locali restano accessibili anche quando i nostri server non sono disponibili'],
    },
    {
      heading: 'Modifiche ai Termini',
      intro: 'Potremmo aggiornare questi termini periodicamente. Ti notificheremo le modifiche significative via e-mail o tramite il nostro servizio. L\u2019uso continuativo del servizio dopo le modifiche costituisce accettazione dei nuovi termini, ai sensi della normativa italiana e del Codice del Consumo (D.lgs. 206/2005).',
    },
    {
      heading: 'Contattaci',
    },
  ],
  contactText: 'Domande su questi termini? Contattaci all\u2019indirizzo',
  cta: {
    title: 'Pronto a creare il tuo',
    titleHighlight: 'curriculum vitae professionale?',
    subtitle: 'Prezzi semplici, termini trasparenti e i tuoi dati restano tuoi.',
    primaryBtn: 'Inizia Gratis',
    secondaryBtn: 'Vedi i Prezzi',
  },
  lastUpdated: 'Ultimo aggiornamento: gennaio 2026',
};

const vi: TermsContent = {
  hero: {
    badge: 'Điều Khoản Sử Dụng',
    title: 'Điều khoản dịch vụ',
    titleHighlight: 'đơn giản, minh bạch',
    subtitle: 'Chúng tôi tin vào sự minh bạch và đơn giản. Điều khoản được viết bằng ngôn ngữ dễ hiểu để bạn biết chính xác những gì mong đợi khi sử dụng Best AI Resume.',
  },
  highlights: [
    { title: 'Không Phí Ẩn', text: 'Bạn thấy gì trả nấy. Bảng giá rõ ràng, không có khoản phí bất ngờ hay chi phí ẩn.' },
    { title: 'Dữ Liệu Của Bạn, Bạn Kiểm Soát', text: 'Chúng tôi chỉ lưu email và tên để đăng nhập. Nội dung CV được lưu trên trình duyệt—không bao giờ lên server.' },
    { title: 'Dùng Thử 7 Ngày Miễn Phí', text: 'Trải nghiệm tất cả tính năng cao cấp miễn phí trong 7 ngày. Không tính phí cho đến khi hết thời gian dùng thử, hủy bất kỳ lúc nào.' },
  ],
  sections: [
    {
      heading: 'Tổng Quan Dịch Vụ',
      intro: 'Best AI Resume là công cụ tạo CV online giúp bạn xây dựng CV chuyên nghiệp bằng các công cụ hỗ trợ bởi AI. Khi sử dụng dịch vụ, bạn đồng ý với các điều khoản này.',
      items: ['Tạo không giới hạn CV với các công cụ của chúng tôi', 'Truy cập gợi ý nội dung và cải thiện CV bằng AI', 'Tải CV xuống dạng PDF', 'Chọn từ nhiều mẫu CV được thiết kế chuyên nghiệp'],
    },
    {
      heading: 'Tài Khoản & Minh Bạch Dữ Liệu',
      subsections: [
        { subheading: 'Những Gì Chúng Tôi Lưu Trên Server', items: ['**Địa chỉ email** \u2014 Để đăng nhập và nhận thông báo quan trọng', '**Tên** \u2014 Để cá nhân hóa trải nghiệm', '**Mật khẩu (đã mã hóa)** \u2014 Được băm an toàn để xác thực', '**Trạng thái đăng ký** \u2014 Để quản lý quyền lợi gói dịch vụ'] },
        { subheading: 'Những Gì Chúng Tôi KHÔNG Lưu', items: ['Nội dung CV (lưu trên trình duyệt của bạn)', 'Lịch sử công tác hay chi tiết việc làm', 'Thông tin học vấn hay kỹ năng', 'Địa chỉ cá nhân hay số điện thoại'] },
      ],
      intro: 'Chúng tôi cam kết thu thập dữ liệu tối thiểu. Chỉ lưu những gì thực sự cần thiết cho tài khoản hoạt động:',
    },
    {
      heading: 'Đăng Ký & Thanh Toán',
      subsections: [
        { subheading: 'Đăng Ký Hàng Tháng', items: ['**Chu kỳ thanh toán** \u2014 Thanh toán hàng tháng vào cùng ngày bạn đăng ký', '**Tự động gia hạn** \u2014 Đăng ký tự động gia hạn trừ khi bạn hủy', '**Minh bạch giá** \u2014 Giá hiển thị khi thanh toán là giá bạn trả (cộng thuế nếu có)'] },
        { subheading: 'Chính Sách Hủy', items: ['Hủy bất kỳ lúc nào từ bảng điều khiển tài khoản—không cần lý do', 'Tiếp tục truy cập cho đến hết chu kỳ thanh toán hiện tại', 'Không phí phạt hay chi phí hủy', 'Dữ liệu trên trình duyệt không bị ảnh hưởng sau khi hủy'] },
        { subheading: 'Dùng Thử 7 Ngày Miễn Phí', items: ['**Truy cập đầy đủ** \u2014 Dùng tất cả tính năng cao cấp miễn phí 7 ngày', '**Không tính phí trong thời gian thử** \u2014 Bạn không bị tính phí cho đến khi hết thời gian dùng thử', '**Hủy bất kỳ lúc nào** \u2014 Hủy trước khi hết thử nghiệm và không phải trả gì', '**Email nhắc nhở** \u2014 Chúng tôi sẽ thông báo trước khi hết thời gian dùng thử'] },
      ],
    },
    {
      heading: 'Truy Cập Miễn Phí và Gói Trả Phí',
      intro: 'Trước khi đăng ký, bạn có thể:',
      items: ['Duyệt và xem trước tất cả mẫu CV', 'Tạo và lưu CV trong tài khoản', 'Tham khảo ví dụ CV và mẹo nghề nghiệp'],
    },
    {
      heading: 'Trách Nhiệm Người Dùng',
      intro: 'Khi sử dụng dịch vụ, bạn đồng ý:',
      items: ['Cung cấp thông tin chính xác khi đăng ký tài khoản', 'Bảo mật thông tin đăng nhập', 'Chỉ sử dụng dịch vụ cho mục đích hợp pháp', 'Không cố gắng vượt qua hoặc lạm dụng dịch vụ'],
    },
    {
      heading: 'Sở Hữu Trí Tuệ',
      items: ['**Nội dung của bạn** \u2014 Bạn sở hữu hoàn toàn mọi nội dung bạn tạo bằng dịch vụ', '**Mẫu CV của chúng tôi** \u2014 Thiết kế mẫu được cấp phép cho mục đích cá nhân và chuyên nghiệp', '**Nội dung do AI tạo** \u2014 Văn bản do AI tạo thuộc về bạn và bạn tự do sử dụng'],
    },
    {
      heading: 'Tính Khả Dụng Dịch Vụ',
      intro: 'Chúng tôi cam kết duy trì dịch vụ ổn định, tuy nhiên:',
      items: ['Bảo trì định kỳ có thể gây gián đoạn tạm thời', 'Chúng tôi sẽ thông báo trước khi bảo trì theo lịch khi có thể', 'Dữ liệu trên trình duyệt vẫn truy cập được ngay cả khi server không khả dụng'],
    },
    {
      heading: 'Thay Đổi Điều Khoản',
      intro: 'Chúng tôi có thể cập nhật điều khoản định kỳ. Chúng tôi sẽ thông báo các thay đổi quan trọng qua email hoặc trên dịch vụ. Việc tiếp tục sử dụng dịch vụ sau khi thay đổi đồng nghĩa với việc chấp nhận điều khoản mới.',
    },
    {
      heading: 'Liên Hệ',
    },
  ],
  contactText: 'Có câu hỏi về điều khoản? Liên hệ chúng tôi tại',
  cta: {
    title: 'Sẵn sàng tạo',
    titleHighlight: 'CV chuyên nghiệp?',
    subtitle: 'Giá minh bạch, điều khoản rõ ràng và dữ liệu thuộc về bạn.',
    primaryBtn: 'Bắt Đầu Miễn Phí',
    secondaryBtn: 'Xem Bảng Giá',
  },
  lastUpdated: 'Cập nhật lần cuối: tháng 1 năm 2026',
};

// ── Korean ───────────────────────────────────────────────────────────

const ko: TermsContent = {
  hero: {
    badge: '이용약관',
    title: '간결하고 투명한',
    titleHighlight: '서비스 이용약관',
    subtitle: '저희는 투명성과 간결함을 중요시합니다. Best AI Resume 이용 시 무엇을 기대할 수 있는지 명확하게 안내드리기 위해, 이용약관을 쉬운 언어로 작성하였습니다.',
  },
  highlights: [
    { title: '숨겨진 비용 없음', text: '표시된 금액이 결제 금액입니다. 추가 요금이나 숨겨진 비용 없이 명확한 가격 정책을 운영합니다.' },
    { title: '개인정보는 본인이 관리', text: '로그인을 위한 이메일 주소와 이름만 저장합니다. 이력서 내용은 사용자의 브라우저에만 저장되며 서버에는 보관하지 않습니다.' },
    { title: '7일 무료 체험', text: '모든 프리미엄 기능을 7일간 무료로 체험하세요. 체험 기간 종료 전까지 요금이 부과되지 않으며, 언제든 수수료 없이 해지 가능합니다.' },
  ],
  sections: [
    {
      heading: '서비스 개요',
      intro: 'Best AI Resume는 AI 기반 도구를 활용하여 전문적인 이력서 작성을 지원하는 온라인 이력서 작성 서비스입니다. 본 서비스를 이용하시면 아래 이용약관에 동의하신 것으로 간주됩니다.',
      items: ['이력서 작성 도구를 사용하여 무제한 이력서 생성', 'AI 기반 콘텐츠 제안 및 개선 기능 이용', 'PDF 형식으로 이력서 다운로드', '전문 디자이너가 제작한 템플릿 중 선택'],
    },
    {
      heading: '계정 및 데이터 투명성',
      subsections: [
        { subheading: '서버에 저장하는 정보', items: ['**이메일 주소** — 계정 로그인 및 중요 알림을 위해 사용', '**이름** — 맞춤형 서비스 제공을 위해 사용', '**비밀번호(암호화)** — 인증을 위해 안전하게 해시 처리하여 저장', '**구독 상태** — 요금제 혜택 관리를 위해 사용'] },
        { subheading: '저장하지 않는 정보', items: ['이력서 내용(사용자의 브라우저에 로컬 저장)', '경력 사항 및 고용 세부 정보', '학력 또는 보유 기술 정보', '개인 주소 또는 전화번호'] },
      ],
      intro: '최소한의 데이터만 수집하는 것을 원칙으로 합니다. 계정 운영에 반드시 필요한 정보만 저장합니다:',
    },
    {
      heading: '구독 및 결제',
      subsections: [
        { subheading: '월간 구독', items: ['**결제 주기** — 구독 개시일과 동일한 날짜에 매월 결제', '**자동 갱신** — 해지하지 않는 한 구독이 자동으로 갱신됩니다', '**가격 투명성** — 결제 시 표시된 금액이 실제 결제 금액입니다(세금 별도)'] },
        { subheading: '해지 정책', items: ['계정 대시보드에서 언제든 즉시 해지 가능 — 사유를 묻지 않습니다', '현재 결제 기간 종료일까지 서비스 이용 가능', '해지 수수료 또는 위약금 없음', '해지 후에도 로컬에 저장된 데이터는 그대로 유지됩니다'] },
        { subheading: '7일 무료 체험', items: ['**전체 기능 이용** — 모든 프리미엄 기능을 7일간 무료 체험', '**체험 기간 중 무료** — 체험 종료 시까지 요금이 청구되지 않습니다', '**언제든 해지 가능** — 체험 종료 전 해지 시 비용 부담 없음', '**알림 메일 발송** — 체험 종료 전에 안내 메일을 보내드립니다'] },
      ],
    },
    {
      heading: '무료 이용 및 유료 요금제',
      intro: '구독 전에 다음을 이용하실 수 있습니다:',
      items: ['모든 이력서 템플릿 검색 및 미리보기', '이력서 작성 및 계정에 저장', '이력서 예시 및 취업 관련 팁 열람'],
    },
    {
      heading: '이용자의 의무',
      intro: '본 서비스를 이용함으로써 다음 사항에 동의하신 것으로 간주됩니다:',
      items: ['계정 등록 시 정확한 정보 제공', '계정 인증 정보를 안전하게 관리', '합법적인 목적으로만 서비스 이용', '서비스를 우회하거나 악용하는 행위를 하지 않을 것'],
    },
    {
      heading: '지적재산권',
      items: ['**사용자의 콘텐츠** — 본 서비스를 이용하여 작성한 모든 콘텐츠의 소유권은 사용자에게 귀속됩니다', '**당사의 템플릿** — 템플릿 디자인은 개인적 및 업무적 용도로 사용이 허가됩니다', '**AI 생성 콘텐츠** — 당사 AI가 생성한 텍스트는 사용자의 소유이며 자유롭게 활용하실 수 있습니다'],
    },
    {
      heading: '서비스 가용성',
      intro: '높은 서비스 가용성을 유지하기 위해 최선을 다하고 있으나:',
      items: ['정기 점검으로 인해 일시적으로 서비스가 중단될 수 있습니다', '예정된 점검은 가능한 한 사전에 공지합니다', '서버가 중단되더라도 로컬에 저장된 데이터에는 접근 가능합니다'],
    },
    {
      heading: '이용약관 변경',
      intro: '본 이용약관은 수시로 변경될 수 있습니다. 중요한 변경 사항은 이메일 또는 서비스 내 공지를 통해 안내드립니다. 변경 후 서비스를 계속 이용하시면 변경된 약관에 동의하신 것으로 간주됩니다.',
    },
    {
      heading: '문의하기',
    },
  ],
  contactText: '본 이용약관에 대해 궁금하신 점이 있으시면 아래로 연락해 주세요:',
  cta: {
    title: '전문적인',
    titleHighlight: '이력서를 작성해 보세요',
    subtitle: '명확한 가격, 투명한 약관, 데이터는 오직 본인의 것입니다.',
    primaryBtn: '무료로 시작하기',
    secondaryBtn: '요금제 보기',
  },
  lastUpdated: '최종 업데이트: 2026년 1월',
};

const th: TermsContent = {
  hero: {
    badge: 'ข้อกำหนดและเงื่อนไข',
    title: 'ข้อกำหนดการให้บริการที่',
    titleHighlight: 'เรียบง่ายและโปร่งใส',
    subtitle: 'เราเชื่อมั่นในความโปร่งใสและความเรียบง่าย ข้อกำหนดของเราเขียนด้วยภาษาที่เข้าใจง่าย เพื่อให้คุณทราบอย่างชัดเจนว่าจะได้รับอะไรจากการใช้ Best AI Resume',
  },
  highlights: [
    { title: 'ไม่มีค่าธรรมเนียมแอบแฝง', text: 'สิ่งที่คุณเห็นคือสิ่งที่คุณจ่าย ราคาของเราตรงไปตรงมา ไม่มีค่าใช้จ่ายเพิ่มเติมหรือค่าธรรมเนียมแอบแฝง' },
    { title: 'ข้อมูลของคุณ คุณควบคุม', text: 'เราจัดเก็บเฉพาะอีเมลและชื่อของคุณสำหรับการเข้าสู่ระบบ เนื้อหาเรซูเม่จะอยู่ในเบราว์เซอร์ของคุณเท่านั้น ไม่อยู่บนเซิร์ฟเวอร์ของเรา' },
    { title: 'ทดลองใช้ฟรี 7 วัน', text: 'ทดลองใช้ฟีเจอร์พรีเมียมทั้งหมดฟรี 7 วัน ไม่มีค่าใช้จ่ายจนกว่าจะหมดระยะทดลอง ยกเลิกได้ทุกเมื่อโดยไม่เสียค่าธรรมเนียม' },
  ],
  sections: [
    {
      heading: 'ภาพรวมบริการ',
      intro: 'Best AI Resume เป็นเครื่องมือสร้างเรซูเม่ออนไลน์ที่ช่วยให้คุณสร้างเรซูเม่มืออาชีพด้วยเครื่องมือที่ขับเคลื่อนโดย AI เมื่อใช้บริการของเรา ถือว่าคุณยอมรับข้อกำหนดเหล่านี้',
      items: ['สร้างเรซูเม่ได้ไม่จำกัดด้วยเครื่องมือของเรา', 'เข้าถึงคำแนะนำและการปรับปรุงเนื้อหาที่ขับเคลื่อนโดย AI', 'ดาวน์โหลดเรซูเม่ในรูปแบบ PDF', 'เลือกจากเทมเพลตที่ออกแบบอย่างมืออาชีพ'],
    },
    {
      heading: 'บัญชีผู้ใช้และความโปร่งใสของข้อมูล',
      subsections: [
        { subheading: 'ข้อมูลที่เราจัดเก็บบนเซิร์ฟเวอร์', items: ['**อีเมล** \u2014 สำหรับการเข้าสู่ระบบและการแจ้งเตือนสำคัญ', '**ชื่อ** \u2014 เพื่อปรับแต่งประสบการณ์การใช้งานของคุณ', '**รหัสผ่าน (เข้ารหัสแล้ว)** \u2014 เข้ารหัสอย่างปลอดภัยด้วย Hash เพื่อการยืนยันตัวตน', '**สถานะการสมัครสมาชิก** \u2014 เพื่อจัดการสิทธิประโยชน์ของแพ็กเกจของคุณ'] },
        { subheading: 'ข้อมูลที่เราไม่ได้จัดเก็บ', items: ['เนื้อหาเรซูเม่ของคุณ (จัดเก็บในเบราว์เซอร์ของคุณ)', 'ประวัติการทำงานหรือรายละเอียดการจ้างงาน', 'ข้อมูลการศึกษาหรือทักษะ', 'ที่อยู่ส่วนตัวหรือหมายเลขโทรศัพท์'] },
      ],
      intro: 'เรามุ่งมั่นในการเก็บรวบรวมข้อมูลให้น้อยที่สุด เราจัดเก็บเฉพาะสิ่งที่จำเป็นอย่างยิ่งสำหรับการทำงานของบัญชี:',
    },
    {
      heading: 'การสมัครสมาชิกและการชำระเงิน',
      subsections: [
        { subheading: 'การสมัครสมาชิกรายเดือน', items: ['**รอบการเรียกเก็บเงิน** \u2014 เรียกเก็บเงินรายเดือนในวันเดียวกับที่คุณสมัคร', '**ต่ออายุอัตโนมัติ** \u2014 การสมัครสมาชิกจะต่ออายุอัตโนมัติเว้นแต่จะยกเลิก', '**ความโปร่งใสด้านราคา** \u2014 ราคาที่แสดงขณะชำระเงินคือราคาที่คุณจ่าย (บวกภาษีที่เกี่ยวข้อง)'] },
        { subheading: 'นโยบายการยกเลิก', items: ['ยกเลิกได้ทุกเมื่อจากแดชบอร์ดบัญชีของคุณ โดยไม่ต้องให้เหตุผล', 'ยังคงเข้าใช้งานได้จนถึงสิ้นสุดรอบการเรียกเก็บเงินปัจจุบัน', 'ไม่มีค่าธรรมเนียมหรือค่าปรับสำหรับการยกเลิก', 'ข้อมูลในเครื่องของคุณจะยังคงอยู่หลังการยกเลิก'] },
        { subheading: 'ทดลองใช้ฟรี 7 วัน', items: ['**เข้าถึงเต็มรูปแบบ** \u2014 ทดลองใช้ฟีเจอร์พรีเมียมทั้งหมดฟรี 7 วัน', '**ไม่เสียค่าใช้จ่ายระหว่างทดลอง** \u2014 จะไม่มีการเรียกเก็บเงินจนกว่าจะสิ้นสุดระยะทดลอง', '**ยกเลิกได้ทุกเมื่อ** \u2014 ยกเลิกก่อนหมดระยะทดลองและไม่ต้องจ่ายอะไร', '**อีเมลเตือน** \u2014 เราจะแจ้งเตือนคุณก่อนหมดระยะทดลอง'] },
      ],
    },
    {
      heading: 'การใช้งานฟรีและแพ็กเกจเสียเงิน',
      intro: 'ก่อนสมัครสมาชิก คุณสามารถ:',
      items: ['เรียกดูและดูตัวอย่างเทมเพลตทั้งหมด', 'สร้างและบันทึกเรซูเม่ในบัญชีของคุณ', 'ดูตัวอย่างเรซูเม่และเคล็ดลับอาชีพ'],
    },
    {
      heading: 'ความรับผิดชอบของผู้ใช้',
      intro: 'เมื่อใช้บริการของเรา คุณยอมรับว่าจะ:',
      items: ['ให้ข้อมูลที่ถูกต้องในการลงทะเบียนบัญชี', 'รักษาความปลอดภัยของข้อมูลยืนยันตัวตนบัญชี', 'ใช้บริการเพื่อวัตถุประสงค์ที่ชอบด้วยกฎหมายเท่านั้น', 'ไม่พยายามหลีกเลี่ยงหรือใช้บริการในทางที่ผิด'],
    },
    {
      heading: 'ทรัพย์สินทางปัญญา',
      items: ['**เนื้อหาของคุณ** \u2014 คุณเป็นเจ้าของเนื้อหาทั้งหมดที่สร้างขึ้นโดยใช้บริการของเราอย่างสมบูรณ์', '**เทมเพลตของเรา** \u2014 การออกแบบเทมเพลตได้รับอนุญาตให้คุณใช้ส่วนบุคคลและเพื่อวัตถุประสงค์ทางวิชาชีพ', '**เนื้อหาที่สร้างโดย AI** \u2014 ข้อความที่สร้างโดย AI ของเราเป็นของคุณและใช้ได้อย่างอิสระ'],
    },
    {
      heading: 'ความพร้อมใช้งานของบริการ',
      intro: 'เรามุ่งมั่นรักษาความพร้อมใช้งานของบริการให้สูงอยู่เสมอ แต่:',
      items: ['การบำรุงรักษาเป็นครั้งคราวอาจทำให้เกิดการหยุดชะงักชั่วคราว', 'เราจะแจ้งผู้ใช้เกี่ยวกับการบำรุงรักษาตามกำหนดเมื่อเป็นไปได้', 'ข้อมูลในเครื่องของคุณยังคงเข้าถึงได้แม้เซิร์ฟเวอร์ของเราไม่พร้อมใช้งาน'],
    },
    {
      heading: 'การเปลี่ยนแปลงข้อกำหนด',
      intro: 'เราอาจปรับปรุงข้อกำหนดเหล่านี้เป็นครั้งคราว เราจะแจ้งให้คุณทราบเกี่ยวกับการเปลี่ยนแปลงที่สำคัญผ่านทางอีเมลหรือผ่านบริการของเรา การใช้บริการต่อหลังจากมีการเปลี่ยนแปลงถือเป็นการยอมรับข้อกำหนดใหม่',
    },
    {
      heading: 'ติดต่อเรา',
    },
  ],
  contactText: 'มีคำถามเกี่ยวกับข้อกำหนดเหล่านี้? ติดต่อเราที่',
  cta: {
    title: 'พร้อมสร้าง',
    titleHighlight: 'เรซูเม่มืออาชีพของคุณหรือยัง?',
    subtitle: 'ราคาเรียบง่าย ข้อกำหนดโปร่งใส และข้อมูลยังคงเป็นของคุณ',
    primaryBtn: 'เริ่มต้นฟรี',
    secondaryBtn: 'ดูราคา',
  },
  lastUpdated: 'อัปเดตล่าสุด: มกราคม 2569',
};

const pt: TermsContent = {
  hero: {
    badge: 'Termos e Condicoes',
    title: 'Termos de servico',
    titleHighlight: 'simples e transparentes',
    subtitle: 'Acreditamos em transparencia e simplicidade. Nossos termos sao escritos em linguagem clara para que voce saiba exatamente o que esperar ao usar o Best AI Resume.',
  },
  highlights: [
    { title: 'Sem Cobranças Ocultas', text: 'O que voce ve e o que voce paga. Nossos precos sao claros, sem cobranças surpresa nem taxas ocultas.' },
    { title: 'Seus Dados, Seu Controle', text: 'Armazenamos apenas seu e-mail e nome para login. O conteudo do seu curriculo fica no seu navegador — nunca em nossos servidores.' },
    { title: 'Teste Gratuito de 7 Dias', text: 'Experimente todos os recursos premium gratuitamente por 7 dias. Sem cobrança ate o fim do periodo de teste, cancele a qualquer momento sem custo.' },
  ],
  sections: [
    {
      heading: 'Visao Geral do Servico',
      intro: 'Best AI Resume e um criador de curriculos online que ajuda voce a criar curriculos profissionais com ferramentas baseadas em inteligencia artificial. Ao usar nosso servico, voce concorda com estes termos.',
      items: ['Crie curriculos ilimitados com nossas ferramentas', 'Acesse sugestoes de conteudo e melhorias geradas por IA', 'Baixe seus curriculos em formato PDF', 'Escolha entre modelos desenvolvidos por profissionais'],
    },
    {
      heading: 'Conta e Transparencia de Dados',
      subsections: [
        { subheading: 'O Que Armazenamos em Nossos Servidores', items: ['**Endereco de e-mail** \u2014 Para login e notificacoes importantes', '**Nome** \u2014 Para personalizar sua experiencia', '**Senha (criptografada)** \u2014 Armazenada com hash seguro para autenticacao', '**Status da assinatura** \u2014 Para gerenciar os beneficios do seu plano'] },
        { subheading: 'O Que NAO Armazenamos', items: ['Conteudo do curriculo (salvo localmente no seu navegador)', 'Historico profissional ou detalhes de emprego', 'Informacoes de formacao ou habilidades', 'Endereco pessoal ou numero de telefone'] },
      ],
      intro: 'Nos comprometemos a coletar o minimo de dados necessarios. Armazenamos apenas o que e essencial para o funcionamento da sua conta:',
    },
    {
      heading: 'Assinatura e Pagamentos',
      subsections: [
        { subheading: 'Assinatura Mensal', items: ['**Ciclo de cobranca** \u2014 A cobranca ocorre mensalmente na mesma data da assinatura', '**Renovacao automatica** \u2014 As assinaturas renovam automaticamente salvo cancelamento', '**Transparencia de precos** \u2014 O preco exibido no momento do pagamento e o valor cobrado (mais impostos, se aplicavel)'] },
        { subheading: 'Politica de Cancelamento', items: ['Cancele a qualquer momento pelo painel da conta — sem precisar justificar', 'O acesso continua ate o fim do periodo de cobranca vigente', 'Sem multa ou custo de cancelamento', 'Seus dados locais permanecem intactos apos o cancelamento'] },
        { subheading: 'Teste Gratuito de 7 Dias', items: ['**Acesso completo** \u2014 Experimente todos os recursos premium gratuitamente por 7 dias', '**Sem cobranca durante o teste** \u2014 Voce nao sera cobrado ate o fim do periodo de teste', '**Cancele a qualquer momento** \u2014 Cancele antes do fim do teste e nao pagara nada', '**E-mail de lembrete** \u2014 Avisaremos antes do fim do periodo de teste'] },
      ],
    },
    {
      heading: 'Acesso Gratuito e Planos Pagos',
      intro: 'Antes de assinar, voce pode:',
      items: ['Navegar e visualizar todos os modelos', 'Criar e salvar curriculos na sua conta', 'Consultar exemplos de curriculos e dicas de carreira'],
    },
    {
      heading: 'Responsabilidades do Usuario',
      intro: 'Ao usar nosso servico, voce concorda em:',
      items: ['Fornecer informacoes precisas no cadastro da conta', 'Manter suas credenciais de acesso em seguranca', 'Usar o servico apenas para fins licitos', 'Nao tentar contornar ou abusar do servico'],
    },
    {
      heading: 'Propriedade Intelectual',
      items: ['**Seu conteudo** \u2014 Voce mantem total propriedade de todo o conteudo criado com nosso servico', '**Nossos modelos** \u2014 Os designs dos modelos sao licenciados para uso pessoal e profissional', '**Conteudo gerado por IA** \u2014 O texto gerado por nossa IA pertence a voce e pode ser usado livremente'],
    },
    {
      heading: 'Disponibilidade do Servico',
      intro: 'Nos comprometemos a manter alta disponibilidade do servico, porem:',
      items: ['Manutencoes periodicas podem causar interrupcoes temporarias', 'Avisaremos sobre manutencoes programadas quando possivel', 'Seus dados locais permanecem acessiveis mesmo quando nossos servidores estiverem indisponiveis'],
    },
    {
      heading: 'Alteracoes nos Termos',
      intro: 'Podemos atualizar estes termos periodicamente. Notificaremos alteracoes significativas por e-mail ou pelo servico. O uso continuado apos as alteracoes implica aceitacao dos novos termos, nos termos do Codigo de Defesa do Consumidor (Lei n. 8.078/1990).',
    },
    {
      heading: 'Fale Conosco',
    },
  ],
  contactText: 'Duvidas sobre estes termos? Entre em contato conosco pelo e-mail',
  cta: {
    title: 'Pronto para criar seu',
    titleHighlight: 'curriculo profissional?',
    subtitle: 'Precos simples, termos transparentes e seus dados pertencem a voce.',
    primaryBtn: 'Comece Gratuitamente',
    secondaryBtn: 'Ver Planos',
  },
  lastUpdated: 'Ultima atualizacao: janeiro de 2026',
};

const tr: TermsContent = {
  hero: {
    badge: 'Kullanım Şartları',
    title: 'Şeffaf, adil',
    titleHighlight: 'kullanım şartları',
    subtitle: 'Bu şartlar, sizinle aramızdaki anlaşmayı açık bir dille tanımlar. Karmaşık hukuki jargon yok — sadece net ve dürüst koşullar.',
  },
  highlights: [
    { title: 'Gizli Ücret Yok', text: 'Gördüğünüz şey ödediğiniz şeydir. Fiyatlandırmamız nettir; sürpriz ücret veya gizli masraf yoktur.' },
    { title: 'Verileriniz, Kontrolünüz', text: 'Yalnızca giriş için e-posta adresinizi ve adınızı saklıyoruz. CV içeriğiniz tarayıcınızda kalır — sunucularımızda asla.' },
    { title: '7 Günlük Ücretsiz Deneme', text: 'Tüm premium özellikleri 7 gün boyunca ücretsiz deneyin. Deneme süresi boyunca ücretlendirme yapılmaz, istediğiniz zaman ücretsiz iptal edin.' },
  ],
  sections: [
    {
      heading: 'Hizmet Genel Bakış',
      intro: 'Best AI Resume, yapay zeka tabanlı araçlarla profesyonel CV\'ler oluşturmanıza yardımcı olan çevrimiçi bir CV oluşturucudur. Hizmetimizi kullanarak bu şartları kabul etmiş olursunuz.',
      items: ['Araçlarımızla sınırsız CV oluşturun', 'AI tarafından oluşturulan içerik önerilerine ve geliştirmelere erişin', 'CV\'lerinizi PDF formatında indirin', 'Profesyoneller tarafından tasarlanmış şablonlar arasından seçin'],
    },
    {
      heading: 'Hesap ve Veri Şeffaflığı',
      subsections: [
        { subheading: 'Sunucularımızda Sakladıklarımız', items: ['**E-posta adresi** — Giriş ve önemli bildirimler için', '**Ad** — Deneyiminizi kişiselleştirmek için', '**Şifre (şifrelenmiş)** — Kimlik doğrulama için güvenli hash ile saklanır', '**Abonelik durumu** — Plan avantajlarınızı yönetmek için'] },
        { subheading: 'Saklamadıklarımız', items: ['CV içeriği (tarayıcınızda yerel olarak kaydedilir)', 'İş geçmişi veya istihdam detayları', 'Eğitim bilgileri veya beceriler', 'Kişisel adres veya telefon numarası'] },
      ],
      intro: 'Minimum gerekli veriyi toplamayı taahhüt ediyoruz. Yalnızca hesabınızın işlevselliği için gerekli olanları saklıyoruz:',
    },
    {
      heading: 'Abonelik ve Ödemeler',
      subsections: [
        { subheading: 'Aylık Abonelik', items: ['**Faturalama döngüsü** — Abonelik tarihinden itibaren aylık olarak faturalandırılır', '**Otomatik yenileme** — İptal edilmedikçe abonelikler otomatik olarak yenilenir', '**Fiyat şeffaflığı** — Ödeme sırasında görüntülenen fiyat, uygulanan vergi dahil, tahsil edilen tutardır'] },
        { subheading: 'İptal Politikası', items: ['Hesap panelinizden istediğiniz zaman iptal edin — gerekçe belirtmenize gerek yok', 'Mevcut faturalama döneminin sonuna kadar erişim devam eder', 'İptal cezası veya ücreti yoktur', 'Yerel verileriniz iptalden sonra da bozulmadan kalır'] },
        { subheading: '7 Günlük Ücretsiz Deneme', items: ['**Tam erişim** — Tüm premium özellikleri 7 gün boyunca ücretsiz deneyin', '**Deneme sırasında ücretlendirme yok** — Deneme süresi dolana kadar ücretlendirilmezsiniz', '**İstediğiniz zaman iptal edin** — Deneme süresi dolmadan iptal edin ve hiçbir şey ödemezsiniz', '**Hatırlatma e-postası** — Deneme süreniz dolmadan önce size haber vereceğiz'] },
      ],
    },
    {
      heading: 'Ücretsiz Erişim ve Ücretli Planlar',
      intro: 'Abone olmadan önce şunları yapabilirsiniz:',
      items: ['Tüm şablonlara göz atın ve önizleyin', 'Hesabınızda CV\'ler oluşturun ve kaydedin', 'CV örneklerine ve kariyer ipuçlarına bakın'],
    },
    {
      heading: 'Kullanıcı Sorumlulukları',
      intro: 'Hizmetimizi kullanarak şunları kabul etmiş olursunuz:',
      items: ['Hesap kaydınızda doğru bilgi sağlamak', 'Giriş kimlik bilgilerinizi güvende tutmak', 'Hizmeti yalnızca yasal amaçlarla kullanmak', 'Hizmeti atlatmaya veya istismar etmeye çalışmamak'],
    },
    {
      heading: 'Fikri Mülkiyet',
      items: ['**İçeriğiniz** — Hizmetimizle oluşturduğunuz tüm içeriğin tam mülkiyetini elinde tutarsınız', '**Şablonlarımız** — Şablon tasarımları kişisel ve profesyonel kullanım için lisanslanmıştır', '**AI tarafından oluşturulan içerik** — AI\'mız tarafından oluşturulan metinler size aittir ve serbestçe kullanılabilir'],
    },
    {
      heading: 'Hizmet Kullanılabilirliği',
      intro: 'Yüksek hizmet kullanılabilirliğini sürdürmeyi taahhüt ediyoruz, ancak:',
      items: ['Periyodik bakımlar geçici kesintilere neden olabilir', 'Mümkün olduğunda planlı bakımlar hakkında önceden bilgi vereceğiz', 'Sunucularımız kullanılamadığında bile yerel verilerinize erişilebilir'],
    },
    {
      heading: 'Şartlardaki Değişiklikler',
      intro: 'Bu şartları zaman zaman güncelleyebiliriz. Önemli değişiklikleri e-posta veya hizmet aracılığıyla bildireceğiz. Değişikliklerden sonra hizmeti kullanmaya devam etmek yeni şartları kabul ettiğiniz anlamına gelir.',
    },
    {
      heading: 'Bize Ulaşın',
    },
  ],
  contactText: 'Bu şartlar hakkında sorularınız mı var? Bize e-posta ile ulaşın:',
  cta: {
    title: 'Profesyonel CV\'nizi',
    titleHighlight: 'oluşturmaya hazır mısınız?',
    subtitle: 'Basit fiyatlandırma, şeffaf şartlar ve verileriniz size aittir.',
    primaryBtn: 'Ücretsiz Başla',
    secondaryBtn: 'Planları Gör',
  },
  lastUpdated: 'Son güncelleme: Ocak 2026',
};

const id: TermsContent = {
  hero: {
    badge: 'Syarat dan Ketentuan',
    title: 'Transparan, adil',
    titleHighlight: 'syarat dan ketentuan',
    subtitle: 'Syarat ini mendefinisikan perjanjian antara Anda dan kami dalam bahasa yang jelas. Tidak ada jargon hukum yang rumit — hanya ketentuan yang bersih dan jujur.',
  },
  highlights: [
    { title: 'Tidak Ada Biaya Tersembunyi', text: 'Yang Anda lihat adalah yang Anda bayar. Harga kami transparan; tidak ada biaya kejutan atau biaya tersembunyi.' },
    { title: 'Data Anda, Kendali Anda', text: 'Kami hanya menyimpan alamat email dan nama Anda untuk login. Konten CV Anda tetap di browser — tidak pernah di server kami.' },
    { title: 'Uji Coba Gratis 7 Hari', text: 'Coba semua fitur premium selama 7 hari secara gratis. Tidak ada tagihan selama masa uji coba, batalkan kapan saja secara gratis.' },
  ],
  sections: [
    {
      heading: 'Gambaran Umum Layanan',
      intro: 'Best AI Resume adalah pembuat CV online yang membantu Anda membuat CV profesional dengan alat bertenaga AI. Dengan menggunakan layanan kami, Anda menyetujui syarat-syarat ini.',
      items: ['Buat CV tak terbatas dengan alat kami', 'Akses saran dan peningkatan konten yang dihasilkan AI', 'Unduh CV Anda dalam format PDF', 'Pilih dari template yang dirancang oleh para profesional'],
    },
    {
      heading: 'Akun dan Transparansi Data',
      subsections: [
        { subheading: 'Yang Kami Simpan di Server Kami', items: ['**Alamat email** — Untuk login dan notifikasi penting', '**Nama** — Untuk mempersonalisasi pengalaman Anda', '**Kata sandi (terenkripsi)** — Disimpan dengan hash aman untuk autentikasi', '**Status langganan** — Untuk mengelola manfaat paket Anda'] },
        { subheading: 'Yang Tidak Kami Simpan', items: ['Konten CV (disimpan secara lokal di browser Anda)', 'Riwayat pekerjaan atau detail pekerjaan', 'Informasi pendidikan atau keahlian', 'Alamat pribadi atau nomor telepon'] },
      ],
      intro: 'Kami berkomitmen untuk mengumpulkan data minimum yang diperlukan. Kami hanya menyimpan apa yang diperlukan untuk fungsionalitas akun Anda:',
    },
    {
      heading: 'Langganan dan Pembayaran',
      subsections: [
        { subheading: 'Langganan Bulanan', items: ['**Siklus penagihan** — Ditagih setiap bulan dari tanggal berlangganan', '**Perpanjangan otomatis** — Langganan diperpanjang otomatis kecuali dibatalkan', '**Transparansi harga** — Harga yang ditampilkan saat checkout, termasuk pajak yang berlaku, adalah jumlah yang dikenakan'] },
        { subheading: 'Kebijakan Pembatalan', items: ['Batalkan kapan saja dari panel akun Anda — tidak perlu alasan', 'Akses berlanjut hingga akhir periode penagihan saat ini', 'Tidak ada penalti atau biaya pembatalan', 'Data lokal Anda tetap utuh setelah pembatalan'] },
        { subheading: 'Uji Coba Gratis 7 Hari', items: ['**Akses penuh** — Coba semua fitur premium selama 7 hari secara gratis', '**Tidak ada tagihan selama uji coba** — Anda tidak akan ditagih sampai masa uji coba berakhir', '**Batalkan kapan saja** — Batalkan sebelum uji coba berakhir dan Anda tidak membayar apapun', '**Email pengingat** — Kami akan memberi tahu Anda sebelum masa uji coba berakhir'] },
      ],
    },
    {
      heading: 'Akses Gratis dan Paket Berbayar',
      intro: 'Sebelum berlangganan, Anda dapat:',
      items: ['Menelusuri dan melihat pratinjau semua template', 'Membuat dan menyimpan CV di akun Anda', 'Melihat contoh CV dan tips karier'],
    },
    {
      heading: 'Tanggung Jawab Pengguna',
      intro: 'Dengan menggunakan layanan kami, Anda setuju untuk:',
      items: ['Memberikan informasi akurat saat mendaftar akun', 'Menjaga keamanan kredensial login Anda', 'Menggunakan layanan hanya untuk tujuan yang sah', 'Tidak mencoba melewati atau menyalahgunakan layanan'],
    },
    {
      heading: 'Kekayaan Intelektual',
      items: ['**Konten Anda** — Anda mempertahankan kepemilikan penuh atas semua konten yang Anda buat dengan layanan kami', '**Template kami** — Desain template dilisensikan untuk penggunaan pribadi dan profesional', '**Konten yang dihasilkan AI** — Teks yang dihasilkan oleh AI kami adalah milik Anda dan dapat digunakan secara bebas'],
    },
    {
      heading: 'Ketersediaan Layanan',
      intro: 'Kami berkomitmen untuk mempertahankan ketersediaan layanan yang tinggi, namun:',
      items: ['Pemeliharaan berkala dapat menyebabkan gangguan sementara', 'Kami akan memberi pemberitahuan terlebih dahulu tentang pemeliharaan terjadwal bila memungkinkan', 'Data lokal Anda dapat diakses bahkan ketika server kami tidak tersedia'],
    },
    {
      heading: 'Perubahan pada Syarat',
      intro: 'Kami dapat memperbarui syarat ini dari waktu ke waktu. Kami akan memberi tahu Anda tentang perubahan penting melalui email atau layanan. Melanjutkan penggunaan layanan setelah perubahan berarti Anda menerima syarat baru.',
    },
    {
      heading: 'Hubungi Kami',
    },
  ],
  contactText: 'Ada pertanyaan tentang syarat ini? Hubungi kami melalui email:',
  cta: {
    title: 'Siap membuat CV',
    titleHighlight: 'profesional Anda?',
    subtitle: 'Harga sederhana, syarat transparan, dan data Anda adalah milik Anda.',
    primaryBtn: 'Mulai Gratis',
    secondaryBtn: 'Lihat Paket',
  },
  lastUpdated: 'Terakhir diperbarui: Januari 2026',
};

const pl: TermsContent = {
  hero: {
    badge: 'Regulamin',
    title: 'Proste, przejrzyste',
    titleHighlight: 'warunki użytkowania',
    subtitle: 'Wierzymy w transparentność i prostotę. Nasze warunki są napisane zrozumiałym językiem, abyś dokładnie wiedział, czego możesz oczekiwać korzystając z Best AI Resume.',
  },
  highlights: [
    { title: 'Brak Ukrytych Opłat', text: 'Co widzisz, to płacisz. Nasze ceny są transparentne — bez niespodzianek ani ukrytych kosztów.' },
    { title: 'Twoje Dane, Twoja Kontrola', text: 'Przechowujemy tylko Twój adres e-mail i nazwę do celów logowania. Zawartość CV pozostaje w Twojej przeglądarce — nigdy na naszych serwerach.' },
    { title: '7-dniowy Darmowy Okres Próbny', text: 'Wypróbuj wszystkie funkcje premium przez 7 dni za darmo. Żadnych opłat do końca okresu próbnego, anulowanie w dowolnym momencie bez kosztów.' },
  ],
  sections: [
    {
      heading: 'Przegląd Usługi',
      intro: 'Best AI Resume to kreator CV online, który umożliwia tworzenie profesjonalnych CV przy użyciu narzędzi opartych na AI. Korzystając z naszej usługi, akceptujesz niniejsze warunki.',
      items: ['Twórz nieograniczoną liczbę CV przy użyciu naszych narzędzi', 'Dostęp do sugestii treści i ulepszeń opartych na AI', 'Pobieraj CV w formacie PDF', 'Wybieraj spośród profesjonalnie zaprojektowanych szablonów'],
    },
    {
      heading: 'Konto i Transparentność Danych',
      subsections: [
        { subheading: 'Co Przechowujemy na Naszych Serwerach', items: ['**Adres e-mail** — Do logowania i ważnych powiadomień', '**Nazwa** — Aby spersonalizować Twoje doświadczenie', '**Hasło (zaszyfrowane)** — Bezpiecznie zahashowane do uwierzytelnienia', '**Status subskrypcji** — Do zarządzania korzyściami z planu'] },
        { subheading: 'Czego NIE Przechowujemy', items: ['Zawartości Twojego CV (przechowywana lokalnie w przeglądarce)', 'Historii pracy ani danych zatrudnienia', 'Informacji o wykształceniu ani umiejętnościach', 'Adresu ani numeru telefonu'] },
      ],
      intro: 'Jesteśmy zaangażowani w minimalne zbieranie danych. Przechowujemy tylko to, co absolutnie niezbędne do działania konta:',
    },
    {
      heading: 'Subskrypcja i Płatności',
      subsections: [
        { subheading: 'Subskrypcja Miesięczna', items: ['**Cykl rozliczeniowy** — Opłata jest pobierana miesięcznie w dniu subskrypcji', '**Automatyczne odnawianie** — Subskrypcje odnawiają się automatycznie, jeśli nie zostaną anulowane', '**Transparentność cen** — Cena pokazana przy kasie to cena, którą płacisz (plus ewentualne podatki)'] },
        { subheading: 'Polityka Anulowania', items: ['Anuluj w dowolnym momencie przez panel konta — bez pytań', 'Dostęp pozostaje aktywny do końca bieżącego okresu rozliczeniowego', 'Brak opłat za anulowanie ani kar', 'Twoje lokalne dane pozostają nienaruszone po anulowaniu'] },
        { subheading: '7-dniowy Darmowy Okres Próbny', items: ['**Pełny dostęp** — Wypróbuj wszystkie funkcje premium przez 7 dni za darmo', '**Bez opłat w trakcie próby** — Żadnych płatności do końca okresu próbnego', '**Anuluj w dowolnym momencie** — Anuluj przed końcem okresu próbnego i nic nie płacisz', '**E-mail przypominający** — Powiadomimy Cię przed końcem okresu próbnego'] },
      ],
    },
    {
      heading: 'Bezpłatny Dostęp i Płatne Subskrypcje',
      intro: 'Przed subskrypcją możesz:',
      items: ['Przeglądać wszystkie szablony i wyświetlać podglądy', 'Tworzyć i zapisywać CV na koncie', 'Przeglądać przykłady CV i porady kariery'],
    },
    {
      heading: 'Obowiązki Użytkownika',
      intro: 'Korzystając z naszej usługi, zgadzasz się:',
      items: ['Podawać dokładne informacje podczas rejestracji konta', 'Zabezpieczać dane logowania do konta', 'Używać usługi wyłącznie do legalnych celów', 'Nie próbować obchodzić ani nadużywać usługi'],
    },
    {
      heading: 'Własność Intelektualna',
      items: ['**Twoje treści** — Zachowujesz pełne prawo własności do wszystkich treści tworzonych w naszej usłudze', '**Nasze szablony** — Projekty szablonów są licencjonowane do użytku osobistego i zawodowego', '**Treści generowane przez AI** — Tekst wygenerowany przez nasz AI należy do Ciebie do swobodnego użytku'],
    },
    {
      heading: 'Dostępność Usługi',
      intro: 'Dążymy do wysokiej dostępności usługi, jednak:',
      items: ['Okazjonalna konserwacja może powodować tymczasowe przerwy', 'Informujemy użytkowników z wyprzedzeniem o planowanych pracach konserwacyjnych', 'Twoje lokalne dane pozostają dostępne nawet gdy nasze serwery są offline'],
    },
    {
      heading: 'Zmiany Warunków',
      intro: 'Możemy od czasu do czasu aktualizować niniejsze warunki. Powiadomimy Cię o istotnych zmianach przez e-mail lub w naszej usłudze. Dalsze korzystanie z usługi po zmianach oznacza akceptację nowych warunków.',
    },
    {
      heading: 'Skontaktuj Się z Nami',
    },
  ],
  contactText: 'Masz pytania dotyczące niniejszych warunków? Skontaktuj się z nami pod adresem',
  cta: {
    title: 'Gotowy, aby stworzyć',
    titleHighlight: 'profesjonalne CV?',
    subtitle: 'Proste ceny, przejrzyste warunki i Twoje dane należą do Ciebie.',
    primaryBtn: 'Zacznij za darmo',
    secondaryBtn: 'Zobacz plany',
  },
  lastUpdated: 'Ostatnia aktualizacja: styczeń 2026',
};

const nl: TermsContent = {
  hero: {
    badge: 'Algemene Voorwaarden',
    title: 'Eenvoudige, transparante',
    titleHighlight: 'gebruiksvoorwaarden',
    subtitle: 'Wij geloven in transparantie en eenvoud. Onze voorwaarden zijn geschreven in begrijpelijke taal, zodat u precies weet wat u kunt verwachten bij het gebruik van Best AI Resume.',
  },
  highlights: [
    { title: 'Geen Verborgen Kosten', text: 'Wat u ziet is wat u betaalt. Onze prijzen zijn transparant zonder verrassingen of verborgen kosten.' },
    { title: 'Uw Gegevens, Uw Controle', text: 'Wij slaan alleen uw e-mailadres en naam op voor inlogdoeleinden. Uw cv-inhoud blijft in uw browser — nooit op onze servers.' },
    { title: '7 Dagen Gratis Proefperiode', text: 'Probeer alle premium-functies 7 dagen gratis. Geen kosten tot het einde van de proefperiode, op elk moment opzegbaar zonder kosten.' },
  ],
  sections: [
    {
      heading: 'Overzicht van de Dienst',
      intro: 'Best AI Resume is een online cv-bouwer waarmee u professionele cv\'s kunt maken met behulp van AI-aangedreven tools. Door gebruik te maken van onze dienst gaat u akkoord met deze voorwaarden.',
      items: ['Maak onbeperkt cv\'s met onze bouwtools', 'Toegang tot AI-gestuurde inhoudsuggesties en verbeteringen', 'Download uw cv\'s in PDF-formaat', 'Kies uit professioneel ontworpen sjablonen'],
    },
    {
      heading: 'Account en Gegevenstransparantie',
      subsections: [
        { subheading: 'Wat Wij Opslaan op Onze Servers', items: ['**E-mailadres** — Voor account-login en belangrijke meldingen', '**Naam** — Om uw ervaring te personaliseren', '**Wachtwoord (versleuteld)** — Veilig gehashed voor authenticatie', '**Abonnementsstatus** — Om uw planvoordelen te beheren'] },
        { subheading: 'Wat Wij NIET Opslaan', items: ['Uw cv-inhoud (lokaal opgeslagen in uw browser)', 'Uw werkgeschiedenis of arbeidsgegevens', 'Uw opleidings- of vaardighedeninformatie', 'Uw persoonlijk adres of telefoonnummer'] },
      ],
      intro: 'Wij zijn toegewijd aan minimale gegevensverzameling. Wij slaan alleen op wat absoluut noodzakelijk is voor de werking van uw account:',
    },
    {
      heading: 'Abonnement en Betalingen',
      subsections: [
        { subheading: 'Maandelijks Abonnement', items: ['**Factureringscyclus** — U wordt maandelijks gefactureerd op de datum waarop u zich heeft geabonneerd', '**Automatische verlenging** — Abonnementen worden automatisch verlengd tenzij opgezegd', '**Prijstransparantie** — De prijs die wordt weergegeven bij het afrekenen is de prijs die u betaalt (plus eventuele belastingen)'] },
        { subheading: 'Opzeggingsbeleid', items: ['Op elk moment opzeggen via uw accountdashboard — geen vragen gesteld', 'Toegang blijft actief tot het einde van uw huidige factureringsperiode', 'Geen opzegkosten of boetes', 'Uw lokale gegevens blijven intact na opzegging'] },
        { subheading: '7 Dagen Gratis Proefperiode', items: ['**Volledige toegang** — Probeer alle premium-functies 7 dagen gratis', '**Geen kosten tijdens de proefperiode** — U wordt niet gefactureerd tot het einde van uw proefperiode', '**Op elk moment opzeggen** — Zeg op voor het einde van de proefperiode en u betaalt niets', '**Herinneringsmail** — Wij informeren u voor het einde van uw proefperiode'] },
      ],
    },
    {
      heading: 'Gratis Toegang en Betaalde Abonnementen',
      intro: 'Voordat u zich abonneert, kunt u:',
      items: ['Alle sjablonen bekijken en als voorbeeld weergeven', 'Cv\'s aanmaken en opslaan in uw account', 'Cv-voorbeelden en carrièretips bekijken'],
    },
    {
      heading: 'Verantwoordelijkheden van de Gebruiker',
      intro: 'Door gebruik te maken van onze dienst gaat u akkoord met:',
      items: ['Het verstrekken van nauwkeurige informatie bij het registreren van uw account', 'Het veilig houden van uw accountgegevens', 'Het uitsluitend gebruiken van de dienst voor wettige doeleinden', 'Het niet proberen de dienst te omzeilen of misbruiken'],
    },
    {
      heading: 'Intellectueel Eigendom',
      items: ['**Uw inhoud** — U behoudt het volledige eigendom van alle inhoud die u met onze dienst maakt', '**Onze sjablonen** — Sjabloonontwerpen zijn aan u in licentie gegeven voor persoonlijk en professioneel gebruik', '**AI-gegenereerde inhoud** — Tekst gegenereerd door onze AI is van u om vrij te gebruiken'],
    },
    {
      heading: 'Beschikbaarheid van de Dienst',
      intro: 'Wij streven naar een hoge beschikbaarheid van de dienst, maar:',
      items: ['Incidenteel onderhoud kan tijdelijke onderbrekingen veroorzaken', 'Wij informeren gebruikers waar mogelijk over gepland onderhoud', 'Uw lokale gegevens blijven toegankelijk zelfs wanneer onze servers offline zijn'],
    },
    {
      heading: 'Wijzigingen in de Voorwaarden',
      intro: 'Wij kunnen deze voorwaarden van tijd tot tijd bijwerken. Wij zullen u op de hoogte stellen van belangrijke wijzigingen via e-mail of via onze dienst. Voortgezet gebruik van de dienst na wijzigingen betekent dat u de nieuwe voorwaarden aanvaardt.',
    },
    {
      heading: 'Neem Contact Op',
    },
  ],
  contactText: 'Vragen over deze voorwaarden? Neem contact met ons op via',
  cta: {
    title: 'Klaar om uw',
    titleHighlight: 'professionele cv te maken?',
    subtitle: 'Eenvoudige prijzen, transparante voorwaarden en uw gegevens zijn van u.',
    primaryBtn: 'Gratis Beginnen',
    secondaryBtn: 'Bekijk Abonnementen',
  },
  lastUpdated: 'Laatste update: januari 2026',
};

const contentMap: Record<string, TermsContent> = { en, es, fr, de, ar, ja, it, vi, ko, th, pt, tr, id, pl, nl };

export function getContent(locale: string) { return selectContent(contentMap, locale); }
