// Canvas Template: Classic Professional
import type { CanvasTemplate } from '@/store/useCanvasStore';
import { createText, createShape, createIcon } from '../helpers';

export const classicProfessionalTemplate: CanvasTemplate = {
    id: 'classic-professional',
    name: 'Classic Professional',
    thumbnail: '/templates/classic-professional.png',
    category: 'professional',
    backgroundColor: '#ffffff',
    elements: [
        // Header section
        createText({
            text: 'ALEXANDER MITCHELL',
            x: 40,
            y: 40,
            width: 515,
            fontSize: 32,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            align: 'left',
        }),
        createText({
            text: 'Senior Software Engineer',
            x: 40,
            y: 82,
            width: 515,
            fontSize: 16,
            fill: '#4a4a68',
            letterSpacing: 2,
        }),

        // Divider line
        createShape({
            x: 40,
            y: 115,
            width: 515,
            height: 2,
            fill: '#e0e0e0',
        }),

        // Contact info row with icons
        createIcon({ iconName: 'Email', x: 40, y: 130, fill: '#4a4a68' }),
        createText({
            text: 'alex.mitchell@email.com',
            x: 68,
            y: 130,
            width: 180,
            fontSize: 11,
            fill: '#4a4a68',
        }),
        createIcon({ iconName: 'Phone', x: 230, y: 130, fill: '#4a4a68' }),
        createText({
            text: '+1 (555) 123-4567',
            x: 258,
            y: 130,
            width: 140,
            fontSize: 11,
            fill: '#4a4a68',
        }),
        createIcon({ iconName: 'Location', x: 400, y: 130, fill: '#4a4a68' }),
        createText({
            text: 'San Francisco, CA',
            x: 428,
            y: 130,
            width: 140,
            fontSize: 11,
            fill: '#4a4a68',
        }),

        // Professional Summary section
        createText({
            text: 'PROFESSIONAL SUMMARY',
            x: 40,
            y: 170,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 188,
            width: 180,
            height: 2,
            fill: '#00dc82',
        }),
        createText({
            text: 'Results-driven Senior Software Engineer with 8+ years of experience designing and implementing scalable web applications. Expert in React, Node.js, and cloud architecture. Led teams of 5-10 engineers, delivering projects that increased user engagement by 40% and reduced infrastructure costs by 25%.',
            x: 40,
            y: 200,
            width: 515,
            height: 80,
            fontSize: 11,
            fill: '#4a4a68',
            lineHeight: 1.6,
        }),

        // Experience section
        createText({
            text: 'WORK EXPERIENCE',
            x: 40,
            y: 295,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 313,
            width: 140,
            height: 2,
            fill: '#00dc82',
        }),

        // Job 1
        createText({
            text: 'Senior Software Engineer',
            x: 40,
            y: 328,
            width: 300,
            fontSize: 13,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'TechCorp Inc.',
            x: 40,
            y: 346,
            width: 200,
            fontSize: 11,
            fill: '#00dc82',
            fontWeight: 'bold',
        }),
        createText({
            text: 'Jan 2020 - Present',
            x: 420,
            y: 328,
            width: 135,
            fontSize: 10,
            fill: '#777777',
            align: 'right',
        }),
        createText({
            text: '• Architected microservices platform handling 10M+ daily requests\n• Mentored junior developers and conducted code reviews\n• Implemented CI/CD pipelines reducing deployment time by 60%\n• Led migration from monolith to microservices architecture',
            x: 40,
            y: 368,
            width: 515,
            height: 75,
            fontSize: 10,
            fill: '#4a4a68',
            lineHeight: 1.7,
        }),

        // Job 2
        createText({
            text: 'Software Engineer',
            x: 40,
            y: 455,
            width: 300,
            fontSize: 13,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'StartupXYZ',
            x: 40,
            y: 473,
            width: 200,
            fontSize: 11,
            fill: '#00dc82',
            fontWeight: 'bold',
        }),
        createText({
            text: 'Mar 2017 - Dec 2019',
            x: 420,
            y: 455,
            width: 135,
            fontSize: 10,
            fill: '#777777',
            align: 'right',
        }),
        createText({
            text: '• Built real-time collaboration features using WebSockets\n• Developed RESTful APIs serving 500K+ monthly active users\n• Optimized database queries improving response time by 45%',
            x: 40,
            y: 495,
            width: 515,
            height: 60,
            fontSize: 10,
            fill: '#4a4a68',
            lineHeight: 1.7,
        }),

        // Education section
        createText({
            text: 'EDUCATION',
            x: 40,
            y: 575,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 593,
            width: 90,
            height: 2,
            fill: '#00dc82',
        }),
        createText({
            text: 'Master of Science in Computer Science',
            x: 40,
            y: 608,
            width: 350,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'Stanford University',
            x: 40,
            y: 626,
            width: 200,
            fontSize: 11,
            fill: '#4a4a68',
        }),
        createText({
            text: '2015 - 2017',
            x: 420,
            y: 608,
            width: 135,
            fontSize: 10,
            fill: '#777777',
            align: 'right',
        }),

        // Skills section
        createText({
            text: 'TECHNICAL SKILLS',
            x: 40,
            y: 675,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 693,
            width: 130,
            height: 2,
            fill: '#00dc82',
        }),
        createText({
            text: 'Languages:',
            x: 40,
            y: 710,
            width: 80,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'JavaScript, TypeScript, Python, Go, SQL',
            x: 120,
            y: 710,
            width: 350,
            fontSize: 10,
            fill: '#4a4a68',
        }),
        createText({
            text: 'Frameworks:',
            x: 40,
            y: 728,
            width: 80,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'React, Next.js, Node.js, Express, FastAPI',
            x: 120,
            y: 728,
            width: 350,
            fontSize: 10,
            fill: '#4a4a68',
        }),
        createText({
            text: 'Cloud & Tools:',
            x: 40,
            y: 746,
            width: 80,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'AWS, Docker, Kubernetes, PostgreSQL, Redis, Git',
            x: 120,
            y: 746,
            width: 400,
            fontSize: 10,
            fill: '#4a4a68',
        }),

        // Social links at bottom
        createIcon({ iconName: 'LinkedIn', x: 40, y: 790, width: 16, height: 16, fill: '#0077b5' }),
        createText({
            text: 'linkedin.com/in/alexmitchell',
            x: 62,
            y: 790,
            width: 180,
            fontSize: 10,
            fill: '#0077b5',
        }),
        createIcon({ iconName: 'GitHub', x: 240, y: 790, width: 16, height: 16, fill: '#333333' }),
        createText({
            text: 'github.com/alexmitchell',
            x: 262,
            y: 790,
            width: 180,
            fontSize: 10,
            fill: '#333333',
        }),
    ],
};
