// Canvas Template: Modern Sidebar
import type { CanvasTemplate } from '@/store/useCanvasStore';
import { createText, createShape, createIcon } from '../helpers';

export const modernSidebarTemplate: CanvasTemplate = {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    thumbnail: '/templates/modern-sidebar.png',
    category: 'creative',
    backgroundColor: '#ffffff',
    elements: [
        // Left sidebar background
        createShape({
            x: 0,
            y: 0,
            width: 200,
            height: 842,
            fill: '#1a1a2e',
        }),

        // Profile photo placeholder (click → upload to fill)
        createShape({
            x: 50,
            y: 40,
            width: 100,
            height: 100,
            shapeType: 'circle',
            fill: '#2d2d44',
            stroke: '#00dc82',
            strokeWidth: 3,
            imageSrc: '/Img/sarah-johnson-canvas.png',
            imageFit: 'cover',
        }),

        // Name on sidebar
        createText({
            text: 'SARAH',
            x: 10,
            y: 160,
            width: 180,
            fontSize: 26,
            fontWeight: 'bold',
            fill: '#ffffff',
            align: 'center',
        }),
        createText({
            text: 'JOHNSON',
            x: 10,
            y: 190,
            width: 180,
            fontSize: 26,
            fontWeight: 'bold',
            fill: '#00dc82',
            align: 'center',
        }),
        createText({
            text: 'UX Designer',
            x: 10,
            y: 225,
            width: 180,
            fontSize: 12,
            fill: '#aaaaaa',
            align: 'center',
            letterSpacing: 2,
        }),

        // Sidebar divider
        createShape({
            x: 30,
            y: 255,
            width: 140,
            height: 1,
            fill: '#3d3d5c',
        }),

        // Contact section in sidebar
        createText({
            text: 'CONTACT',
            x: 20,
            y: 275,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createIcon({ iconName: 'Email', x: 20, y: 300, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: 'sarah.j@email.com',
            x: 40,
            y: 300,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),
        createIcon({ iconName: 'Phone', x: 20, y: 322, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: '+1 (555) 987-6543',
            x: 40,
            y: 322,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),
        createIcon({ iconName: 'Location', x: 20, y: 344, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: 'New York, NY',
            x: 40,
            y: 344,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),
        createIcon({ iconName: 'Website', x: 20, y: 366, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: 'sarahjohnson.design',
            x: 40,
            y: 366,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),

        // Skills section in sidebar
        createText({
            text: 'SKILLS',
            x: 20,
            y: 410,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createText({
            text: 'Figma\nSketch\nAdobe XD\nPrototyping\nUser Research\nWireframing\nDesign Systems\nHTML/CSS',
            x: 20,
            y: 435,
            width: 160,
            height: 150,
            fontSize: 10,
            fill: '#cccccc',
            lineHeight: 1.8,
        }),

        // Languages in sidebar
        createText({
            text: 'LANGUAGES',
            x: 20,
            y: 600,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createText({
            text: 'English - Native',
            x: 20,
            y: 625,
            width: 160,
            fontSize: 10,
            fill: '#cccccc',
        }),
        createText({
            text: 'Spanish - Fluent',
            x: 20,
            y: 645,
            width: 160,
            fontSize: 10,
            fill: '#cccccc',
        }),

        // Social links in sidebar
        createText({
            text: 'CONNECT',
            x: 20,
            y: 690,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createIcon({ iconName: 'LinkedIn', x: 55, y: 720, width: 20, height: 20, fill: '#0077b5' }),
        createIcon({ iconName: 'X', x: 90, y: 720, width: 20, height: 20, fill: '#1da1f2' }),
        createIcon({ iconName: 'GitHub', x: 125, y: 720, width: 20, height: 20, fill: '#888888' }),

        // Main content - Right side
        // About section
        createText({
            text: 'ABOUT ME',
            x: 230,
            y: 40,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 60,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'Creative UX Designer with 6+ years of experience crafting user-centered digital experiences. Passionate about solving complex problems through intuitive design solutions. Strong background in user research, prototyping, and design systems.',
            x: 230,
            y: 75,
            width: 330,
            height: 70,
            fontSize: 10,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Experience section
        createText({
            text: 'EXPERIENCE',
            x: 230,
            y: 165,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 185,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),

        // Job 1
        createText({
            text: 'Lead UX Designer',
            x: 230,
            y: 200,
            width: 250,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'DesignHub Agency',
            x: 230,
            y: 218,
            width: 200,
            fontSize: 10,
            fill: '#00dc82',
        }),
        createText({
            text: '2021 - Present',
            x: 460,
            y: 200,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),
        createText({
            text: '• Lead design team of 4 designers across multiple client projects\n• Established design system reducing design-to-dev time by 35%\n• Increased client NPS score from 45 to 72',
            x: 230,
            y: 238,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Job 2
        createText({
            text: 'Senior UX Designer',
            x: 230,
            y: 310,
            width: 250,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'TechStart Inc.',
            x: 230,
            y: 328,
            width: 200,
            fontSize: 10,
            fill: '#00dc82',
        }),
        createText({
            text: '2019 - 2021',
            x: 460,
            y: 310,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),
        createText({
            text: '• Redesigned core product increasing user engagement by 52%\n• Conducted user research with 200+ participants\n• Created comprehensive design documentation',
            x: 230,
            y: 348,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Job 3
        createText({
            text: 'UX Designer',
            x: 230,
            y: 420,
            width: 250,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'Creative Solutions',
            x: 230,
            y: 438,
            width: 200,
            fontSize: 10,
            fill: '#00dc82',
        }),
        createText({
            text: '2017 - 2019',
            x: 460,
            y: 420,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),
        createText({
            text: '• Designed mobile apps with 100K+ downloads\n• Collaborated with developers on design implementation\n• Created user personas and journey maps',
            x: 230,
            y: 458,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Education section
        createText({
            text: 'EDUCATION',
            x: 230,
            y: 540,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 560,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'Bachelor of Fine Arts in Graphic Design',
            x: 230,
            y: 575,
            width: 300,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'Rhode Island School of Design (RISD)',
            x: 230,
            y: 593,
            width: 250,
            fontSize: 10,
            fill: '#555555',
        }),
        createText({
            text: '2013 - 2017',
            x: 460,
            y: 575,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),

        // Certifications
        createText({
            text: 'CERTIFICATIONS',
            x: 230,
            y: 640,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 660,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: '• Google UX Design Professional Certificate (2022)\n• Nielsen Norman Group UX Certification (2021)\n• Interaction Design Foundation - UX Management (2020)',
            x: 230,
            y: 675,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Projects/Portfolio highlight
        createText({
            text: 'FEATURED PROJECTS',
            x: 230,
            y: 750,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 770,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'E-commerce Redesign - 45% conversion increase | Banking App - 4.8 App Store rating',
            x: 230,
            y: 785,
            width: 330,
            fontSize: 9,
            fill: '#555555',
        }),
    ],
};
