import { CanvasTemplate, TextElement, ShapeElement, IconElement, ImageElement } from '@/store/useCanvasStore';

// A4 dimensions for reference
const A4_WIDTH = 595;
const A4_HEIGHT = 842;

// Helper to create text element
const createText = (
    overrides: Partial<TextElement> & { text: string; x: number; y: number }
): TextElement => ({
    id: crypto.randomUUID(),
    type: 'text',
    width: 200,
    height: 30,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    fontSize: 16,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fill: '#333333',
    align: 'left',
    lineHeight: 1.4,
    letterSpacing: 0,
    ...overrides,
});

// Helper to create shape element
const createShape = (
    overrides: Partial<ShapeElement> & { x: number; y: number; width: number; height: number }
): ShapeElement => ({
    id: crypto.randomUUID(),
    type: 'shape',
    shapeType: 'rectangle',
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    fill: '#00dc82',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    ...overrides,
});

// Helper to create icon element
const createIcon = (
    overrides: Partial<IconElement> & { iconName: string; x: number; y: number }
): IconElement => ({
    id: crypto.randomUUID(),
    type: 'icon',
    width: 20,
    height: 20,
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    fill: '#333333',
    stroke: 'transparent',
    strokeWidth: 0,
    ...overrides,
});

// Helper to create image element
const createImage = (
    overrides: Partial<ImageElement> & { src: string; x: number; y: number; width: number; height: number }
): ImageElement => ({
    id: crypto.randomUUID(),
    type: 'image',
    rotation: 0,
    opacity: 1,
    locked: false,
    visible: true,
    ...overrides,
});

// ============================================
// Template 1: Classic Professional
// ============================================
const classicProfessionalTemplate: CanvasTemplate = {
    id: 'classic-professional',
    name: 'Classic Professional',
    thumbnail: '/templates/classic-professional.png',
    category: 'professional',
    backgroundColor: '#ffffff',
    elements: [
        // Header section
        createText({
            text: 'ALEXANDER MITCHELL',
            x: 40,
            y: 40,
            width: 515,
            fontSize: 32,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            align: 'left',
        }),
        createText({
            text: 'Senior Software Engineer',
            x: 40,
            y: 82,
            width: 515,
            fontSize: 16,
            fill: '#4a4a68',
            letterSpacing: 2,
        }),

        // Divider line
        createShape({
            x: 40,
            y: 115,
            width: 515,
            height: 2,
            fill: '#e0e0e0',
        }),

        // Contact info row with icons
        createIcon({ iconName: 'Email', x: 40, y: 130, fill: '#4a4a68' }),
        createText({
            text: 'alex.mitchell@email.com',
            x: 68,
            y: 130,
            width: 180,
            fontSize: 11,
            fill: '#4a4a68',
        }),
        createIcon({ iconName: 'Phone', x: 230, y: 130, fill: '#4a4a68' }),
        createText({
            text: '+1 (555) 123-4567',
            x: 258,
            y: 130,
            width: 140,
            fontSize: 11,
            fill: '#4a4a68',
        }),
        createIcon({ iconName: 'Location', x: 400, y: 130, fill: '#4a4a68' }),
        createText({
            text: 'San Francisco, CA',
            x: 428,
            y: 130,
            width: 140,
            fontSize: 11,
            fill: '#4a4a68',
        }),

        // Professional Summary section
        createText({
            text: 'PROFESSIONAL SUMMARY',
            x: 40,
            y: 170,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 188,
            width: 180,
            height: 2,
            fill: '#00dc82',
        }),
        createText({
            text: 'Results-driven Senior Software Engineer with 8+ years of experience designing and implementing scalable web applications. Expert in React, Node.js, and cloud architecture. Led teams of 5-10 engineers, delivering projects that increased user engagement by 40% and reduced infrastructure costs by 25%.',
            x: 40,
            y: 200,
            width: 515,
            height: 80,
            fontSize: 11,
            fill: '#4a4a68',
            lineHeight: 1.6,
        }),

        // Experience section
        createText({
            text: 'WORK EXPERIENCE',
            x: 40,
            y: 295,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 313,
            width: 140,
            height: 2,
            fill: '#00dc82',
        }),

        // Job 1
        createText({
            text: 'Senior Software Engineer',
            x: 40,
            y: 328,
            width: 300,
            fontSize: 13,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'TechCorp Inc.',
            x: 40,
            y: 346,
            width: 200,
            fontSize: 11,
            fill: '#00dc82',
            fontWeight: 'bold',
        }),
        createText({
            text: 'Jan 2020 - Present',
            x: 420,
            y: 328,
            width: 135,
            fontSize: 10,
            fill: '#777777',
            align: 'right',
        }),
        createText({
            text: '• Architected microservices platform handling 10M+ daily requests\n• Mentored junior developers and conducted code reviews\n• Implemented CI/CD pipelines reducing deployment time by 60%\n• Led migration from monolith to microservices architecture',
            x: 40,
            y: 368,
            width: 515,
            height: 75,
            fontSize: 10,
            fill: '#4a4a68',
            lineHeight: 1.7,
        }),

        // Job 2
        createText({
            text: 'Software Engineer',
            x: 40,
            y: 455,
            width: 300,
            fontSize: 13,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'StartupXYZ',
            x: 40,
            y: 473,
            width: 200,
            fontSize: 11,
            fill: '#00dc82',
            fontWeight: 'bold',
        }),
        createText({
            text: 'Mar 2017 - Dec 2019',
            x: 420,
            y: 455,
            width: 135,
            fontSize: 10,
            fill: '#777777',
            align: 'right',
        }),
        createText({
            text: '• Built real-time collaboration features using WebSockets\n• Developed RESTful APIs serving 500K+ monthly active users\n• Optimized database queries improving response time by 45%',
            x: 40,
            y: 495,
            width: 515,
            height: 60,
            fontSize: 10,
            fill: '#4a4a68',
            lineHeight: 1.7,
        }),

        // Education section
        createText({
            text: 'EDUCATION',
            x: 40,
            y: 575,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 593,
            width: 90,
            height: 2,
            fill: '#00dc82',
        }),
        createText({
            text: 'Master of Science in Computer Science',
            x: 40,
            y: 608,
            width: 350,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'Stanford University',
            x: 40,
            y: 626,
            width: 200,
            fontSize: 11,
            fill: '#4a4a68',
        }),
        createText({
            text: '2015 - 2017',
            x: 420,
            y: 608,
            width: 135,
            fontSize: 10,
            fill: '#777777',
            align: 'right',
        }),

        // Skills section
        createText({
            text: 'TECHNICAL SKILLS',
            x: 40,
            y: 675,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 693,
            width: 130,
            height: 2,
            fill: '#00dc82',
        }),
        createText({
            text: 'Languages:',
            x: 40,
            y: 710,
            width: 80,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'JavaScript, TypeScript, Python, Go, SQL',
            x: 120,
            y: 710,
            width: 350,
            fontSize: 10,
            fill: '#4a4a68',
        }),
        createText({
            text: 'Frameworks:',
            x: 40,
            y: 728,
            width: 80,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'React, Next.js, Node.js, Express, FastAPI',
            x: 120,
            y: 728,
            width: 350,
            fontSize: 10,
            fill: '#4a4a68',
        }),
        createText({
            text: 'Cloud & Tools:',
            x: 40,
            y: 746,
            width: 80,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'AWS, Docker, Kubernetes, PostgreSQL, Redis, Git',
            x: 120,
            y: 746,
            width: 400,
            fontSize: 10,
            fill: '#4a4a68',
        }),

        // Social links at bottom
        createIcon({ iconName: 'LinkedIn', x: 40, y: 790, width: 16, height: 16, fill: '#0077b5' }),
        createText({
            text: 'linkedin.com/in/alexmitchell',
            x: 62,
            y: 790,
            width: 180,
            fontSize: 10,
            fill: '#0077b5',
        }),
        createIcon({ iconName: 'GitHub', x: 240, y: 790, width: 16, height: 16, fill: '#333333' }),
        createText({
            text: 'github.com/alexmitchell',
            x: 262,
            y: 790,
            width: 180,
            fontSize: 10,
            fill: '#333333',
        }),
    ],
};

// ============================================
// Template 2: Modern Sidebar
// ============================================
const modernSidebarTemplate: CanvasTemplate = {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    thumbnail: '/templates/modern-sidebar.png',
    category: 'creative',
    backgroundColor: '#ffffff',
    elements: [
        // Left sidebar background
        createShape({
            x: 0,
            y: 0,
            width: 200,
            height: 842,
            fill: '#1a1a2e',
        }),

        // Profile photo placeholder (circle)
        createShape({
            x: 50,
            y: 40,
            width: 100,
            height: 100,
            shapeType: 'circle',
            fill: '#2d2d44',
            stroke: '#00dc82',
            strokeWidth: 3,
        }),
        // Profile image
        createImage({
            src: '/Img/headshot.png',
            x: 50,
            y: 40,
            width: 100,
            height: 100,
        }),

        // Name on sidebar
        createText({
            text: 'SARAH',
            x: 10,
            y: 160,
            width: 180,
            fontSize: 26,
            fontWeight: 'bold',
            fill: '#ffffff',
            align: 'center',
        }),
        createText({
            text: 'JOHNSON',
            x: 10,
            y: 190,
            width: 180,
            fontSize: 26,
            fontWeight: 'bold',
            fill: '#00dc82',
            align: 'center',
        }),
        createText({
            text: 'UX Designer',
            x: 10,
            y: 225,
            width: 180,
            fontSize: 12,
            fill: '#aaaaaa',
            align: 'center',
            letterSpacing: 2,
        }),

        // Sidebar divider
        createShape({
            x: 30,
            y: 255,
            width: 140,
            height: 1,
            fill: '#3d3d5c',
        }),

        // Contact section in sidebar
        createText({
            text: 'CONTACT',
            x: 20,
            y: 275,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createIcon({ iconName: 'Email', x: 20, y: 300, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: 'sarah.j@email.com',
            x: 40,
            y: 300,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),
        createIcon({ iconName: 'Phone', x: 20, y: 322, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: '+1 (555) 987-6543',
            x: 40,
            y: 322,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),
        createIcon({ iconName: 'Location', x: 20, y: 344, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: 'New York, NY',
            x: 40,
            y: 344,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),
        createIcon({ iconName: 'Website', x: 20, y: 366, width: 14, height: 14, fill: '#888888' }),
        createText({
            text: 'sarahjohnson.design',
            x: 40,
            y: 366,
            width: 150,
            fontSize: 9,
            fill: '#cccccc',
        }),

        // Skills section in sidebar
        createText({
            text: 'SKILLS',
            x: 20,
            y: 410,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createText({
            text: 'Figma\nSketch\nAdobe XD\nPrototyping\nUser Research\nWireframing\nDesign Systems\nHTML/CSS',
            x: 20,
            y: 435,
            width: 160,
            height: 150,
            fontSize: 10,
            fill: '#cccccc',
            lineHeight: 1.8,
        }),

        // Languages in sidebar
        createText({
            text: 'LANGUAGES',
            x: 20,
            y: 600,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createText({
            text: 'English - Native',
            x: 20,
            y: 625,
            width: 160,
            fontSize: 10,
            fill: '#cccccc',
        }),
        createText({
            text: 'Spanish - Fluent',
            x: 20,
            y: 645,
            width: 160,
            fontSize: 10,
            fill: '#cccccc',
        }),

        // Social links in sidebar
        createText({
            text: 'CONNECT',
            x: 20,
            y: 690,
            width: 160,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createIcon({ iconName: 'LinkedIn', x: 55, y: 720, width: 20, height: 20, fill: '#0077b5' }),
        createIcon({ iconName: 'Twitter', x: 90, y: 720, width: 20, height: 20, fill: '#1da1f2' }),
        createIcon({ iconName: 'GitHub', x: 125, y: 720, width: 20, height: 20, fill: '#888888' }),

        // Main content - Right side
        // About section
        createText({
            text: 'ABOUT ME',
            x: 230,
            y: 40,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 60,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'Creative UX Designer with 6+ years of experience crafting user-centered digital experiences. Passionate about solving complex problems through intuitive design solutions. Strong background in user research, prototyping, and design systems.',
            x: 230,
            y: 75,
            width: 330,
            height: 70,
            fontSize: 10,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Experience section
        createText({
            text: 'EXPERIENCE',
            x: 230,
            y: 165,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 185,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),

        // Job 1
        createText({
            text: 'Lead UX Designer',
            x: 230,
            y: 200,
            width: 250,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'DesignHub Agency',
            x: 230,
            y: 218,
            width: 200,
            fontSize: 10,
            fill: '#00dc82',
        }),
        createText({
            text: '2021 - Present',
            x: 460,
            y: 200,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),
        createText({
            text: '• Lead design team of 4 designers across multiple client projects\n• Established design system reducing design-to-dev time by 35%\n• Increased client NPS score from 45 to 72',
            x: 230,
            y: 238,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Job 2
        createText({
            text: 'Senior UX Designer',
            x: 230,
            y: 310,
            width: 250,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'TechStart Inc.',
            x: 230,
            y: 328,
            width: 200,
            fontSize: 10,
            fill: '#00dc82',
        }),
        createText({
            text: '2019 - 2021',
            x: 460,
            y: 310,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),
        createText({
            text: '• Redesigned core product increasing user engagement by 52%\n• Conducted user research with 200+ participants\n• Created comprehensive design documentation',
            x: 230,
            y: 348,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Job 3
        createText({
            text: 'UX Designer',
            x: 230,
            y: 420,
            width: 250,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'Creative Solutions',
            x: 230,
            y: 438,
            width: 200,
            fontSize: 10,
            fill: '#00dc82',
        }),
        createText({
            text: '2017 - 2019',
            x: 460,
            y: 420,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),
        createText({
            text: '• Designed mobile apps with 100K+ downloads\n• Collaborated with developers on design implementation\n• Created user personas and journey maps',
            x: 230,
            y: 458,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Education section
        createText({
            text: 'EDUCATION',
            x: 230,
            y: 540,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 560,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'Bachelor of Fine Arts in Graphic Design',
            x: 230,
            y: 575,
            width: 300,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#1a1a2e',
        }),
        createText({
            text: 'Rhode Island School of Design (RISD)',
            x: 230,
            y: 593,
            width: 250,
            fontSize: 10,
            fill: '#555555',
        }),
        createText({
            text: '2013 - 2017',
            x: 460,
            y: 575,
            width: 100,
            fontSize: 9,
            fill: '#888888',
            align: 'right',
        }),

        // Certifications
        createText({
            text: 'CERTIFICATIONS',
            x: 230,
            y: 640,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 660,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: '• Google UX Design Professional Certificate (2022)\n• Nielsen Norman Group UX Certification (2021)\n• Interaction Design Foundation - UX Management (2020)',
            x: 230,
            y: 675,
            width: 330,
            height: 55,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.7,
        }),

        // Projects/Portfolio highlight
        createText({
            text: 'FEATURED PROJECTS',
            x: 230,
            y: 750,
            width: 330,
            fontSize: 14,
            fontWeight: 'bold',
            fill: '#1a1a2e',
            letterSpacing: 1,
        }),
        createShape({
            x: 230,
            y: 770,
            width: 50,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'E-commerce Redesign - 45% conversion increase | Banking App - 4.8 App Store rating',
            x: 230,
            y: 785,
            width: 330,
            fontSize: 9,
            fill: '#555555',
        }),
    ],
};

// ============================================
// Template 3: Minimal Clean
// ============================================
const minimalCleanTemplate: CanvasTemplate = {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    thumbnail: '/templates/minimal-clean.png',
    category: 'minimal',
    backgroundColor: '#fafafa',
    elements: [
        // Name
        createText({
            text: 'DAVID CHEN',
            x: 40,
            y: 50,
            width: 515,
            fontSize: 36,
            fontWeight: 'bold',
            fill: '#222222',
            letterSpacing: 3,
        }),
        createText({
            text: 'Product Manager',
            x: 40,
            y: 95,
            width: 515,
            fontSize: 14,
            fill: '#666666',
            letterSpacing: 1,
        }),

        // Contact row
        createText({
            text: 'david.chen@email.com  |  +1 (555) 456-7890  |  San Jose, CA  |  linkedin.com/in/davidchen',
            x: 40,
            y: 130,
            width: 515,
            fontSize: 10,
            fill: '#888888',
        }),

        // Main divider
        createShape({
            x: 40,
            y: 160,
            width: 515,
            height: 1,
            fill: '#dddddd',
        }),

        // Summary
        createText({
            text: 'SUMMARY',
            x: 40,
            y: 185,
            width: 100,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#222222',
            letterSpacing: 1,
        }),
        createText({
            text: 'Strategic Product Manager with 7 years of experience driving product development from concept to launch. Proven track record of increasing revenue by 30%+ through data-driven product decisions. Strong technical background with expertise in agile methodologies.',
            x: 40,
            y: 210,
            width: 515,
            height: 55,
            fontSize: 10,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Experience
        createText({
            text: 'EXPERIENCE',
            x: 40,
            y: 285,
            width: 100,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#222222',
            letterSpacing: 1,
        }),

        // Job 1
        createText({
            text: 'Senior Product Manager',
            x: 40,
            y: 310,
            width: 300,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Google  •  2021 - Present',
            x: 40,
            y: 328,
            width: 300,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'Led product strategy for Google Workspace collaboration features serving 3B+ users. Managed cross-functional team of 25 engineers, designers, and researchers. Launched 5 major features resulting in 15% increase in daily active users.',
            x: 40,
            y: 350,
            width: 515,
            height: 50,
            fontSize: 10,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Job 2
        createText({
            text: 'Product Manager',
            x: 40,
            y: 415,
            width: 300,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Stripe  •  2018 - 2021',
            x: 40,
            y: 433,
            width: 300,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'Owned the payments dashboard product, growing merchant adoption by 40%. Defined product roadmap balancing customer needs with business objectives. Partnered with engineering to reduce payment processing latency by 25%.',
            x: 40,
            y: 455,
            width: 515,
            height: 50,
            fontSize: 10,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Job 3
        createText({
            text: 'Associate Product Manager',
            x: 40,
            y: 520,
            width: 300,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Microsoft  •  2016 - 2018',
            x: 40,
            y: 538,
            width: 300,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'Launched new features for Microsoft Teams during rapid growth phase. Conducted user research and competitive analysis to inform product decisions. Collaborated with UX team to improve onboarding flow, increasing activation by 20%.',
            x: 40,
            y: 560,
            width: 515,
            height: 50,
            fontSize: 10,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Education
        createText({
            text: 'EDUCATION',
            x: 40,
            y: 635,
            width: 100,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#222222',
            letterSpacing: 1,
        }),
        createText({
            text: 'MBA, Business Administration',
            x: 40,
            y: 660,
            width: 300,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Harvard Business School  •  2014 - 2016',
            x: 40,
            y: 678,
            width: 300,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'BS, Computer Science',
            x: 40,
            y: 705,
            width: 300,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'UC Berkeley  •  2010 - 2014',
            x: 40,
            y: 723,
            width: 300,
            fontSize: 10,
            fill: '#888888',
        }),

        // Skills row at bottom
        createText({
            text: 'SKILLS',
            x: 40,
            y: 765,
            width: 100,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#222222',
            letterSpacing: 1,
        }),
        createText({
            text: 'Product Strategy  •  A/B Testing  •  SQL  •  Jira  •  Figma  •  Roadmapping  •  User Research  •  Agile/Scrum  •  Data Analysis',
            x: 40,
            y: 790,
            width: 515,
            fontSize: 10,
            fill: '#666666',
        }),
    ],
};

// ============================================
// Template 4: Bold Creative
// ============================================
const boldCreativeTemplate: CanvasTemplate = {
    id: 'bold-creative',
    name: 'Bold Creative',
    thumbnail: '/templates/bold-creative.png',
    category: 'bold',
    backgroundColor: '#0f0f23',
    elements: [
        // Accent shape
        createShape({
            x: 0,
            y: 0,
            width: 595,
            height: 180,
            fill: '#00dc82',
        }),

        // Profile circle placeholder
        createShape({
            x: 40,
            y: 90,
            width: 140,
            height: 140,
            shapeType: 'circle',
            fill: '#0f0f23',
            stroke: '#ffffff',
            strokeWidth: 4,
        }),
        // Profile image
        createImage({
            src: '/Img/headshot.png',
            x: 40,
            y: 90,
            width: 140,
            height: 140,
        }),

        // Name
        createText({
            text: 'EMMA',
            x: 200,
            y: 50,
            width: 355,
            fontSize: 48,
            fontWeight: 'bold',
            fill: '#0f0f23',
        }),
        createText({
            text: 'RODRIGUEZ',
            x: 200,
            y: 100,
            width: 355,
            fontSize: 48,
            fontWeight: 'bold',
            fill: '#ffffff',
        }),
        createText({
            text: 'MARKETING DIRECTOR',
            x: 200,
            y: 155,
            width: 355,
            fontSize: 14,
            fill: '#0f0f23',
            letterSpacing: 3,
        }),

        // Contact info
        createIcon({ iconName: 'Email', x: 40, y: 250, width: 18, height: 18, fill: '#00dc82' }),
        createText({
            text: 'emma.rodriguez@email.com',
            x: 68,
            y: 250,
            width: 200,
            fontSize: 11,
            fill: '#ffffff',
        }),
        createIcon({ iconName: 'Phone', x: 40, y: 278, width: 18, height: 18, fill: '#00dc82' }),
        createText({
            text: '+1 (555) 234-5678',
            x: 68,
            y: 278,
            width: 200,
            fontSize: 11,
            fill: '#ffffff',
        }),
        createIcon({ iconName: 'Location', x: 40, y: 306, width: 18, height: 18, fill: '#00dc82' }),
        createText({
            text: 'Los Angeles, CA',
            x: 68,
            y: 306,
            width: 200,
            fontSize: 11,
            fill: '#ffffff',
        }),

        // Social icons
        createIcon({ iconName: 'LinkedIn', x: 40, y: 350, width: 20, height: 20, fill: '#00dc82' }),
        createIcon({ iconName: 'Twitter', x: 75, y: 350, width: 20, height: 20, fill: '#00dc82' }),
        createIcon({ iconName: 'Website', x: 110, y: 350, width: 20, height: 20, fill: '#00dc82' }),

        // About section
        createText({
            text: 'ABOUT',
            x: 300,
            y: 210,
            width: 255,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createText({
            text: 'Award-winning Marketing Director with 10+ years driving brand growth for Fortune 500 companies. Expert in digital transformation, brand strategy, and team leadership. Generated $50M+ in campaign revenue.',
            x: 300,
            y: 235,
            width: 255,
            height: 80,
            fontSize: 10,
            fill: '#cccccc',
            lineHeight: 1.6,
        }),

        // Experience
        createText({
            text: 'EXPERIENCE',
            x: 40,
            y: 400,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),

        // Job 1
        createShape({
            x: 40,
            y: 425,
            width: 4,
            height: 70,
            fill: '#00dc82',
        }),
        createText({
            text: 'Marketing Director',
            x: 55,
            y: 425,
            width: 250,
            fontSize: 13,
            fontWeight: 'bold',
            fill: '#ffffff',
        }),
        createText({
            text: 'Nike Inc.  |  2020 - Present',
            x: 55,
            y: 443,
            width: 250,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'Lead global marketing initiatives for $15B brand. Increased social media engagement by 200%. Launched viral campaigns with 500M+ impressions.',
            x: 55,
            y: 463,
            width: 240,
            height: 45,
            fontSize: 9,
            fill: '#aaaaaa',
            lineHeight: 1.5,
        }),

        // Job 2
        createShape({
            x: 310,
            y: 425,
            width: 4,
            height: 70,
            fill: '#00dc82',
        }),
        createText({
            text: 'Senior Marketing Manager',
            x: 325,
            y: 425,
            width: 230,
            fontSize: 13,
            fontWeight: 'bold',
            fill: '#ffffff',
        }),
        createText({
            text: 'Apple  |  2016 - 2020',
            x: 325,
            y: 443,
            width: 230,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'Managed $30M annual marketing budget. Built team of 12 marketers. Drove 45% YoY growth in key product categories.',
            x: 325,
            y: 463,
            width: 220,
            height: 45,
            fontSize: 9,
            fill: '#aaaaaa',
            lineHeight: 1.5,
        }),

        // Job 3
        createShape({
            x: 40,
            y: 520,
            width: 4,
            height: 70,
            fill: '#00dc82',
        }),
        createText({
            text: 'Marketing Manager',
            x: 55,
            y: 520,
            width: 250,
            fontSize: 13,
            fontWeight: 'bold',
            fill: '#ffffff',
        }),
        createText({
            text: 'Coca-Cola  |  2013 - 2016',
            x: 55,
            y: 538,
            width: 250,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'Developed integrated marketing campaigns across 20 markets. Increased brand awareness by 35% in target demographics.',
            x: 55,
            y: 558,
            width: 240,
            height: 45,
            fontSize: 9,
            fill: '#aaaaaa',
            lineHeight: 1.5,
        }),

        // Education
        createText({
            text: 'EDUCATION',
            x: 40,
            y: 620,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        createText({
            text: 'MBA, Marketing',
            x: 40,
            y: 645,
            width: 200,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#ffffff',
        }),
        createText({
            text: 'Wharton School, UPenn  •  2011-2013',
            x: 40,
            y: 663,
            width: 250,
            fontSize: 10,
            fill: '#888888',
        }),
        createText({
            text: 'BA, Communications',
            x: 310,
            y: 645,
            width: 200,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#ffffff',
        }),
        createText({
            text: 'UCLA  •  2007-2011',
            x: 310,
            y: 663,
            width: 250,
            fontSize: 10,
            fill: '#888888',
        }),

        // Skills
        createText({
            text: 'SKILLS',
            x: 40,
            y: 710,
            width: 515,
            fontSize: 12,
            fontWeight: 'bold',
            fill: '#00dc82',
            letterSpacing: 2,
        }),
        // Skill pills
        createShape({
            x: 40,
            y: 735,
            width: 100,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Brand Strategy',
            x: 45,
            y: 742,
            width: 90,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
        createShape({
            x: 150,
            y: 735,
            width: 95,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Digital Marketing',
            x: 150,
            y: 742,
            width: 95,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
        createShape({
            x: 255,
            y: 735,
            width: 80,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Team Lead',
            x: 255,
            y: 742,
            width: 80,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
        createShape({
            x: 345,
            y: 735,
            width: 70,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Analytics',
            x: 345,
            y: 742,
            width: 70,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
        createShape({
            x: 425,
            y: 735,
            width: 50,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'SEO',
            x: 425,
            y: 742,
            width: 50,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
        createShape({
            x: 485,
            y: 735,
            width: 65,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Content',
            x: 485,
            y: 742,
            width: 65,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),

        // Second row of skills
        createShape({
            x: 40,
            y: 770,
            width: 75,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Budgeting',
            x: 40,
            y: 777,
            width: 75,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
        createShape({
            x: 125,
            y: 770,
            width: 90,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Social Media',
            x: 125,
            y: 777,
            width: 90,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
        createShape({
            x: 225,
            y: 770,
            width: 100,
            height: 28,
            fill: '#1a1a3e',
            cornerRadius: 14,
        }),
        createText({
            text: 'Public Relations',
            x: 225,
            y: 777,
            width: 100,
            fontSize: 9,
            fill: '#ffffff',
            align: 'center',
        }),
    ],
};

// ============================================
// Template 5: Two Column
// ============================================
const twoColumnTemplate: CanvasTemplate = {
    id: 'two-column',
    name: 'Two Column',
    thumbnail: '/templates/two-column.png',
    category: 'professional',
    backgroundColor: '#ffffff',
    elements: [
        // Header bar
        createShape({
            x: 0,
            y: 0,
            width: 595,
            height: 120,
            fill: '#2c3e50',
        }),

        // Name and title
        createText({
            text: 'MICHAEL THOMPSON',
            x: 40,
            y: 35,
            width: 515,
            fontSize: 28,
            fontWeight: 'bold',
            fill: '#ffffff',
            letterSpacing: 2,
        }),
        createText({
            text: 'Data Scientist | Machine Learning Engineer',
            x: 40,
            y: 75,
            width: 515,
            fontSize: 13,
            fill: '#bdc3c7',
        }),

        // Contact info in header
        createIcon({ iconName: 'Email', x: 40, y: 98, width: 14, height: 14, fill: '#00dc82' }),
        createText({
            text: 'm.thompson@email.com',
            x: 60,
            y: 98,
            width: 150,
            fontSize: 9,
            fill: '#ecf0f1',
        }),
        createIcon({ iconName: 'Phone', x: 210, y: 98, width: 14, height: 14, fill: '#00dc82' }),
        createText({
            text: '+1 (555) 789-0123',
            x: 230,
            y: 98,
            width: 120,
            fontSize: 9,
            fill: '#ecf0f1',
        }),
        createIcon({ iconName: 'LinkedIn', x: 350, y: 98, width: 14, height: 14, fill: '#00dc82' }),
        createText({
            text: 'linkedin.com/in/mthompson',
            x: 370,
            y: 98,
            width: 170,
            fontSize: 9,
            fill: '#ecf0f1',
        }),

        // Left column
        // Summary
        createText({
            text: 'PROFESSIONAL SUMMARY',
            x: 40,
            y: 145,
            width: 250,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 162,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'Data Scientist with 5+ years specializing in ML and predictive analytics. Built models generating $20M+ annual value. Expert in Python, TensorFlow, and cloud ML platforms.',
            x: 40,
            y: 175,
            width: 250,
            height: 65,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Experience (left)
        createText({
            text: 'EXPERIENCE',
            x: 40,
            y: 260,
            width: 250,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 277,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),

        // Job 1
        createText({
            text: 'Senior Data Scientist',
            x: 40,
            y: 292,
            width: 250,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Amazon  |  2021 - Present',
            x: 40,
            y: 308,
            width: 250,
            fontSize: 9,
            fill: '#00dc82',
        }),
        createText({
            text: '• Built recommendation engine improving CTR by 25%\n• Led ML infrastructure modernization\n• Mentored team of 4 junior data scientists',
            x: 40,
            y: 325,
            width: 250,
            height: 50,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Job 2
        createText({
            text: 'Data Scientist',
            x: 40,
            y: 390,
            width: 250,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Netflix  |  2019 - 2021',
            x: 40,
            y: 406,
            width: 250,
            fontSize: 9,
            fill: '#00dc82',
        }),
        createText({
            text: '• Developed content recommendation models\n• Reduced customer churn by 15%\n• Automated reporting saving 20 hrs/week',
            x: 40,
            y: 423,
            width: 250,
            height: 50,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Job 3
        createText({
            text: 'Junior Data Scientist',
            x: 40,
            y: 488,
            width: 250,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'IBM  |  2018 - 2019',
            x: 40,
            y: 504,
            width: 250,
            fontSize: 9,
            fill: '#00dc82',
        }),
        createText({
            text: '• Created NLP models for sentiment analysis\n• Built dashboards for C-suite executives\n• Contributed to open-source ML tools',
            x: 40,
            y: 521,
            width: 250,
            height: 50,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Right column divider
        createShape({
            x: 307,
            y: 140,
            width: 1,
            height: 680,
            fill: '#e0e0e0',
        }),

        // Right column
        // Education
        createText({
            text: 'EDUCATION',
            x: 330,
            y: 145,
            width: 230,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 330,
            y: 162,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'Ph.D. Computer Science (ML)',
            x: 330,
            y: 177,
            width: 230,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'MIT  •  2015 - 2018',
            x: 330,
            y: 193,
            width: 230,
            fontSize: 9,
            fill: '#888888',
        }),
        createText({
            text: 'MS Computer Science',
            x: 330,
            y: 218,
            width: 230,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Carnegie Mellon  •  2013 - 2015',
            x: 330,
            y: 234,
            width: 230,
            fontSize: 9,
            fill: '#888888',
        }),
        createText({
            text: 'BS Mathematics',
            x: 330,
            y: 259,
            width: 230,
            fontSize: 10,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'UCLA  •  2009 - 2013',
            x: 330,
            y: 275,
            width: 230,
            fontSize: 9,
            fill: '#888888',
        }),

        // Technical Skills
        createText({
            text: 'TECHNICAL SKILLS',
            x: 330,
            y: 315,
            width: 230,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 330,
            y: 332,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'Languages',
            x: 330,
            y: 347,
            width: 80,
            fontSize: 9,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'Python, R, SQL, Scala',
            x: 330,
            y: 362,
            width: 230,
            fontSize: 9,
            fill: '#555555',
        }),
        createText({
            text: 'ML Frameworks',
            x: 330,
            y: 385,
            width: 80,
            fontSize: 9,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'TensorFlow, PyTorch, scikit-learn',
            x: 330,
            y: 400,
            width: 230,
            fontSize: 9,
            fill: '#555555',
        }),
        createText({
            text: 'Cloud & Tools',
            x: 330,
            y: 423,
            width: 80,
            fontSize: 9,
            fontWeight: 'bold',
            fill: '#333333',
        }),
        createText({
            text: 'AWS SageMaker, GCP, Spark, Airflow',
            x: 330,
            y: 438,
            width: 230,
            fontSize: 9,
            fill: '#555555',
        }),

        // Certifications
        createText({
            text: 'CERTIFICATIONS',
            x: 330,
            y: 480,
            width: 230,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 330,
            y: 497,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: '• AWS ML Specialty (2023)\n• Google Cloud Professional ML (2022)\n• TensorFlow Developer Certificate (2021)',
            x: 330,
            y: 512,
            width: 230,
            height: 50,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Publications
        createText({
            text: 'PUBLICATIONS',
            x: 330,
            y: 580,
            width: 230,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 330,
            y: 597,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: '• "Deep Learning for Recommendations" - NeurIPS 2022\n• "Scalable ML Pipelines" - KDD 2021\n• 500+ citations on Google Scholar',
            x: 330,
            y: 612,
            width: 230,
            height: 50,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Projects
        createText({
            text: 'KEY PROJECTS',
            x: 330,
            y: 680,
            width: 230,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 330,
            y: 697,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: '• Real-time fraud detection (99.2% accuracy)\n• Customer lifetime value prediction\n• Open-source AutoML library (2K+ stars)',
            x: 330,
            y: 712,
            width: 230,
            height: 50,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Awards at bottom left
        createText({
            text: 'AWARDS',
            x: 40,
            y: 600,
            width: 250,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 617,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: '• Data Scientist of the Year, Amazon (2023)\n• Best Paper Award, KDD 2021\n• NSF Graduate Research Fellowship',
            x: 40,
            y: 632,
            width: 250,
            height: 50,
            fontSize: 9,
            fill: '#555555',
            lineHeight: 1.6,
        }),

        // Languages
        createText({
            text: 'LANGUAGES',
            x: 40,
            y: 710,
            width: 250,
            fontSize: 11,
            fontWeight: 'bold',
            fill: '#2c3e50',
            letterSpacing: 1,
        }),
        createShape({
            x: 40,
            y: 727,
            width: 40,
            height: 3,
            fill: '#00dc82',
        }),
        createText({
            text: 'English (Native)  •  Mandarin (Fluent)  •  Spanish (Intermediate)',
            x: 40,
            y: 742,
            width: 250,
            fontSize: 9,
            fill: '#555555',
        }),
    ],
};

// Export all templates
export const canvasTemplates: CanvasTemplate[] = [
    classicProfessionalTemplate,
    modernSidebarTemplate,
    minimalCleanTemplate,
    boldCreativeTemplate,
    twoColumnTemplate,
];

// Export individual templates for direct access
export {
    classicProfessionalTemplate,
    modernSidebarTemplate,
    minimalCleanTemplate,
    boldCreativeTemplate,
    twoColumnTemplate,
};
